//! Conformance Layer 3 — ferrotorch-jit graph IR, trace, symbolic, and codegen_ir (C7.1).
//!
//! Tracking issue: #806 (C7.1 graph+tracing conformance)
//! Reference: torch == 2.11.0 (torch.jit.trace + torch.fx + torch.export semantics)
//!
//! Fixtures: tests/conformance/fixtures_graph.json
//! Generated by: scripts/regenerate_jit_fixtures.py
//!
//! ## Coverage
//!
//! ### graph.rs
//! - [`IrGraph`] construction, node/value counts, input/output lists
//! - [`IrGraph::topological_order`] invariant (producers before consumers)
//! - [`IrGraph::is_constant`] distinguishes constants from inputs
//! - [`IrGraph::remove_node`] decrements node and value counts
//! - [`Dtype`] name + from_type_name round-trip
//! - Default F32 and explicit F64 dtype propagation
//!
//! ### trace.rs
//! - [`trace`] graph structure for x+x, relu(x*y), mm(A,B).sum()
//! - `trace` with `requires_grad=false` returns an error containing "no grad_fn"
//! - `trace` topological order is valid on the produced graph
//!
//! ### symbolic.rs
//! - [`Guard`] accepts / rejects inputs per symbolic vs concrete dims
//! - [`Guard`] enforces min/max range on symbolic dims
//! - [`patch_reshape_for_symbolic_dims`] rewrites single-match reshape targets
//! - Ambiguous reshape target (value appears twice) is left unchanged
//!
//! ### codegen_ir.rs
//! - [`lower_to_loops`]: Neg, Add → single flat loop
//! - [`lower_to_loops`]: Sum, Mean, Prod → accumulator pattern
//! - [`lower_to_loops`]: fused [Neg, Relu, Sigmoid] → single loop with 6-stmt body
//! - [`lower_matmul`]: triple-nested i,j,k loop
//! - [`apply_op_expr`]: Pow → FnCall("powf", [...])
//! - Op classification: `is_unary_elementwise`, `is_binary_elementwise`, `is_reduction`
//!
//! ## Layer 4
//! Surface-coverage gate is deferred to C7.4 wrap-up.
//!
//! ## cascade_skip convention
//! `cascade_skip!(label, issue)` prints a diagnostic and returns early.
//! This is NOT `#[ignore]` — the test runs and emits the notice so CI
//! counts skips separately from passes.

#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_sign_loss,
    clippy::uninlined_format_args,
    clippy::explicit_iter_loop
)]

use std::path::PathBuf;

use ferrotorch_core::error::FerrotorchResult;
use ferrotorch_core::grad_fns::activation::relu;
use ferrotorch_core::grad_fns::arithmetic::{add, mul};
use ferrotorch_core::grad_fns::linalg::mm_differentiable;
use ferrotorch_core::grad_fns::reduction::sum;
use ferrotorch_core::storage::TensorStorage;
use ferrotorch_core::tensor::Tensor;
use ferrotorch_jit::codegen_ir::{
    BinOpKind, Expr, LoopIR, apply_binary_op_expr, apply_op_expr, ir_op_to_binary, ir_op_to_unary,
    is_binary_elementwise, is_elementwise, is_reduction, is_unary_elementwise, lower_matmul,
    lower_to_loops,
};
use ferrotorch_jit::graph::{Dtype, IrGraph, IrNodeId, IrOpKind};
use ferrotorch_jit::symbolic::{Guard, ShapeSignature};
use ferrotorch_jit::trace::trace;

// ---------------------------------------------------------------------------
// cascade_skip macro
// ---------------------------------------------------------------------------

/// Print a skip diagnostic and return early. Never panics.
/// Usage: `cascade_skip!("reason", "CL-NNN")`.
#[allow(unused_macros)]
macro_rules! cascade_skip {
    ($reason:expr, $issue:expr) => {{
        eprintln!(
            "  [cascade_skip] {} — {} (tracking: {})",
            module_path!(),
            $reason,
            $issue
        );
        return;
    }};
}

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("conformance")
        .join("fixtures_graph.json")
}

fn load_fixtures() -> serde_json::Value {
    let path = fixture_path();
    let body = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("read fixtures_graph.json: {e}. Run scripts/regenerate_jit_fixtures.py")
    });
    serde_json::from_str(&body).expect("parse fixtures_graph.json")
}

fn fixture_by_case<'a>(
    fixtures: &'a serde_json::Value,
    case: &str,
) -> Option<&'a serde_json::Value> {
    fixtures["fixtures"]
        .as_array()?
        .iter()
        .find(|f| f["case"].as_str() == Some(case))
}

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

fn grad_vec_f32(data: Vec<f32>) -> Tensor<f32> {
    let n = data.len();
    Tensor::from_storage(TensorStorage::cpu(data), vec![n], true)
        .unwrap()
        .requires_grad_(true)
}

fn grad_mat_f32(data: Vec<f32>, rows: usize, cols: usize) -> Tensor<f32> {
    Tensor::from_storage(TensorStorage::cpu(data), vec![rows, cols], true)
        .unwrap()
        .requires_grad_(true)
}

// ---------------------------------------------------------------------------
// Verify that the fixtures file exists and has the expected metadata.
// ---------------------------------------------------------------------------

#[test]
fn fixtures_file_exists_and_is_c7_1() {
    let fixtures = load_fixtures();
    let phase = fixtures["metadata"]["sub_phase"]
        .as_str()
        .expect("sub_phase in metadata");
    assert_eq!(phase, "C7.1", "fixture sub_phase must be C7.1");
    let n = fixtures["fixtures"]
        .as_array()
        .expect("fixtures array")
        .len();
    assert!(n >= 20, "expected at least 20 C7.1 fixtures, got {n}");
}

// ===========================================================================
// GRAPH — IrGraph construction and structural invariants
// ===========================================================================

/// graph_add_relu_node_count: input -> add(x,x) -> relu -> output.
/// Expected: 3 nodes, 3 values, 1 input, 1 output.
#[test]
fn graph_add_relu_node_count() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "graph_add_relu_node_count").expect("fixture missing");
    let expected = &fx["expected"];

    let mut g = IrGraph::new();
    let x = g.add_input(vec![2, 3]);
    let (_, add_outs) = g.add_node(IrOpKind::Add, vec![x, x], vec![vec![2, 3]]);
    let (_, relu_outs) = g.add_node(IrOpKind::Relu, vec![add_outs[0]], vec![vec![2, 3]]);
    g.set_outputs(vec![relu_outs[0]]);

    let expected_nc = expected["node_count"].as_u64().unwrap() as usize;
    let expected_vc = expected["value_count"].as_u64().unwrap() as usize;
    let expected_ic = expected["input_count"].as_u64().unwrap() as usize;
    let expected_oc = expected["output_count"].as_u64().unwrap() as usize;

    assert_eq!(g.node_count(), expected_nc, "node_count mismatch");
    assert_eq!(g.value_count(), expected_vc, "value_count mismatch");
    assert_eq!(g.input_values.len(), expected_ic, "input_count mismatch");
    assert_eq!(g.output_values.len(), expected_oc, "output_count mismatch");

    // Verify op sequence via topological order.
    let order = g.topological_order();
    assert_eq!(order.len(), expected_nc);

    let node_for = |id: IrNodeId| g.nodes.iter().find(|n| n.id == id).unwrap();
    assert!(matches!(node_for(order[0]).op, IrOpKind::Input { .. }));
    assert!(matches!(node_for(order[1]).op, IrOpKind::Add));
    assert!(matches!(node_for(order[2]).op, IrOpKind::Relu));
}

/// graph_two_inputs_mm_sum: A[2,3], B[3,2] -> mm -> sum -> output.
/// Expected: 4 nodes, 4 values, 2 inputs, 1 output.
#[test]
fn graph_two_inputs_mm_sum() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "graph_two_inputs_mm_sum").expect("fixture missing");
    let expected = &fx["expected"];

    let mut g = IrGraph::new();
    let a = g.add_input(vec![2, 3]);
    let b = g.add_input(vec![3, 2]);
    let (_, mm_outs) = g.add_node(IrOpKind::Mm, vec![a, b], vec![vec![2, 2]]);
    let (_, sum_outs) = g.add_node(IrOpKind::Sum, vec![mm_outs[0]], vec![vec![]]);
    g.set_outputs(vec![sum_outs[0]]);

    assert_eq!(
        g.node_count(),
        expected["node_count"].as_u64().unwrap() as usize
    );
    assert_eq!(
        g.value_count(),
        expected["value_count"].as_u64().unwrap() as usize
    );
    assert_eq!(
        g.input_values.len(),
        expected["input_count"].as_u64().unwrap() as usize
    );
    assert_eq!(
        g.output_values.len(),
        expected["output_count"].as_u64().unwrap() as usize
    );
}

/// Helper: verify topological order invariant holds for a graph.
fn assert_topological_order_valid(g: &IrGraph, ctx: &str) {
    let order = g.topological_order();
    assert_eq!(order.len(), g.node_count(), "{ctx}: wrong order length");
    let pos_of = |id: IrNodeId| order.iter().position(|&n| n == id).expect("id in order");
    for node in &g.nodes {
        for &input_val in &node.inputs {
            if let Some(producer) = g
                .values
                .iter()
                .find(|v| v.id == input_val)
                .and_then(|v| v.producer)
            {
                assert!(
                    pos_of(producer) < pos_of(node.id),
                    "{ctx}: producer {:?} must precede consumer {:?}",
                    producer,
                    node.id,
                );
            }
        }
    }
}

/// graph_topological_order_valid: topological_order() invariant holds on multiple graphs.
#[test]
fn graph_topological_order_valid() {
    // add_relu graph
    {
        let mut g = IrGraph::new();
        let x = g.add_input(vec![4]);
        let (_, a) = g.add_node(IrOpKind::Add, vec![x, x], vec![vec![4]]);
        let (_, r) = g.add_node(IrOpKind::Relu, vec![a[0]], vec![vec![4]]);
        g.set_outputs(vec![r[0]]);
        assert_topological_order_valid(&g, "add_relu");
    }
    // mm_sum graph
    {
        let mut g = IrGraph::new();
        let a = g.add_input(vec![2, 3]);
        let b = g.add_input(vec![3, 2]);
        let (_, mm) = g.add_node(IrOpKind::Mm, vec![a, b], vec![vec![2, 2]]);
        let (_, s) = g.add_node(IrOpKind::Sum, vec![mm[0]], vec![vec![]]);
        g.set_outputs(vec![s[0]]);
        assert_topological_order_valid(&g, "mm_sum");
    }
}

/// graph_constant_detection: is_constant() distinguishes inputs from constants.
#[test]
fn graph_constant_detection() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "graph_constant_detection").expect("fixture missing");
    let expected = &fx["expected"];

    let mut g = IrGraph::new();
    let x = g.add_input(vec![3]);
    let c = g.add_constant(vec![1.0, 2.0, 3.0], vec![3]);

    let input_is_const = expected["input_is_constant"].as_bool().unwrap();
    let const_is_const = expected["constant_is_constant"].as_bool().unwrap();

    assert_eq!(
        g.is_constant(x),
        input_is_const,
        "input should not be constant"
    );
    assert_eq!(
        g.is_constant(c),
        const_is_const,
        "constant should be constant"
    );
}

/// graph_dtype_default_f32: default construction tags every IrValue with F32.
#[test]
fn graph_dtype_default_f32() {
    let mut g = IrGraph::new();
    let x = g.add_input(vec![3]);
    let _c = g.add_constant(vec![1.0; 3], vec![3]);
    let (_, _) = g.add_node(IrOpKind::Relu, vec![x], vec![vec![3]]);

    for v in &g.values {
        assert_eq!(
            v.dtype,
            Dtype::F32,
            "value {:?} should have dtype F32, got {:?}",
            v.id,
            v.dtype,
        );
    }
}

/// graph_dtype_explicit_f64: explicit dtype construction tags every IrValue with F64.
#[test]
fn graph_dtype_explicit_f64() {
    let mut g = IrGraph::new();
    let x = g.add_input_with_dtype(vec![2], Dtype::F64);
    let c = g.add_constant_with_dtype(vec![0.0, 1.0], vec![2], Dtype::F64);
    let (_, outs) = g.add_node_with_dtype(IrOpKind::Add, vec![x, c], vec![vec![2]], &[Dtype::F64]);
    g.set_outputs(vec![outs[0]]);

    for v in &g.values {
        assert_eq!(
            v.dtype,
            Dtype::F64,
            "value {:?} should have dtype F64, got {:?}",
            v.id,
            v.dtype,
        );
    }
}

/// graph_dtype_name_round_trip: Dtype::name() returns "f32" / "f64".
#[test]
fn graph_dtype_name_round_trip() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "graph_dtype_name_round_trip").expect("fixture missing");
    let expected = &fx["expected"];

    assert_eq!(
        Dtype::F32.name(),
        expected["f32_name"].as_str().unwrap(),
        "F32.name() mismatch"
    );
    assert_eq!(
        Dtype::F64.name(),
        expected["f64_name"].as_str().unwrap(),
        "F64.name() mismatch"
    );
}

/// graph_dtype_from_type_name: Dtype::from_type_name recognizes known types.
#[test]
fn graph_dtype_from_type_name_recognizes_primitives() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(
        &fixtures,
        "graph_dtype_from_type_name_recognizes_primitives",
    )
    .expect("fixture missing");
    let expected = &fx["expected"];

    assert_eq!(
        Dtype::from_type_name("f32"),
        Some(Dtype::F32),
        "f32 should map to F32"
    );
    assert_eq!(
        Dtype::from_type_name("f64"),
        Some(Dtype::F64),
        "f64 should map to F64"
    );
    assert_eq!(
        Dtype::from_type_name("core::primitive::f32"),
        Some(Dtype::F32),
        "core::primitive::f32 should map to F32"
    );
    assert_eq!(
        Dtype::from_type_name("bf16"),
        None,
        "bf16 should return None"
    );
    assert_eq!(Dtype::from_type_name("i32"), None, "i32 should return None");

    // Confirm fixture expectations agree.
    assert_eq!(expected["f32_maps"].as_str().unwrap(), "F32");
    assert_eq!(expected["f64_maps"].as_str().unwrap(), "F64");
    assert_eq!(expected["bf16_maps"].as_str().unwrap(), "None");
}

/// graph_remove_node_decrements_counts: remove_node() updates node/value counts.
#[test]
fn graph_remove_node_decrements_counts() {
    let fixtures = load_fixtures();
    let fx =
        fixture_by_case(&fixtures, "graph_remove_node_decrements_counts").expect("fixture missing");
    let expected = &fx["expected"];

    let mut g = IrGraph::new();
    let x = g.add_input(vec![2]);
    let (add_id, add_outs) = g.add_node(IrOpKind::Add, vec![x, x], vec![vec![2]]);
    let (relu_id, relu_outs) = g.add_node(IrOpKind::Relu, vec![add_outs[0]], vec![vec![2]]);
    g.set_outputs(vec![relu_outs[0]]);

    assert_eq!(
        g.node_count(),
        expected["node_count_before"].as_u64().unwrap() as usize,
        "node_count before remove"
    );
    assert_eq!(
        g.value_count(),
        expected["value_count_before"].as_u64().unwrap() as usize,
        "value_count before remove"
    );

    // Remove relu (the output node).
    g.remove_node(relu_id);
    assert_eq!(
        g.node_count(),
        expected["node_count_after"].as_u64().unwrap() as usize,
        "node_count after remove"
    );
    assert_eq!(
        g.value_count(),
        expected["value_count_after"].as_u64().unwrap() as usize,
        "value_count after remove"
    );
    let output_cleared = expected["output_cleared"].as_bool().unwrap();
    assert_eq!(
        g.output_values.is_empty(),
        output_cleared,
        "output_values cleared state"
    );

    // Suppress unused variable warnings.
    let _ = add_id;
}

// ===========================================================================
// TRACE — autograd-based tracer structural invariants
// ===========================================================================

/// trace_add_self_structure: trace(|x| x+x) produces 2 nodes; Add reuses input.
#[test]
fn trace_add_self_structure() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "trace_add_self_structure").expect("fixture missing");
    let expected = &fx["expected"];

    let x = grad_vec_f32(vec![1.0, 2.0, 3.0]);
    let graph = trace(
        |inputs: &[Tensor<f32>]| -> FerrotorchResult<Tensor<f32>> { add(&inputs[0], &inputs[0]) },
        &[x],
    )
    .unwrap();

    assert_eq!(
        graph.node_count(),
        expected["node_count"].as_u64().unwrap() as usize,
        "node_count"
    );
    assert_eq!(
        graph.input_values.len(),
        expected["input_count"].as_u64().unwrap() as usize,
        "input_count"
    );
    assert_eq!(
        graph.output_values.len(),
        expected["output_count"].as_u64().unwrap() as usize,
        "output_count"
    );

    // Verify the Add node exists and both its inputs are the same value.
    let add_node = graph
        .nodes
        .iter()
        .find(|n| matches!(n.op, IrOpKind::Add))
        .expect("Add node must exist");
    assert_eq!(add_node.inputs.len(), 2, "Add takes 2 inputs");
    if expected["add_inputs_both_same"].as_bool().unwrap() {
        assert_eq!(
            add_node.inputs[0], add_node.inputs[1],
            "Add's two input IrValueIds must be the same (value reuse)"
        );
    }
}

/// trace_mul_relu_structure: trace(|x,y| relu(x*y)) produces 4 nodes.
#[test]
fn trace_mul_relu_structure() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "trace_mul_relu_structure").expect("fixture missing");
    let expected = &fx["expected"];

    let x = grad_vec_f32(vec![1.0, 2.0, 3.0]);
    let y = grad_vec_f32(vec![4.0, 5.0, 6.0]);
    let graph = trace(
        |inputs: &[Tensor<f32>]| -> FerrotorchResult<Tensor<f32>> {
            let p = mul(&inputs[0], &inputs[1])?;
            relu(&p)
        },
        &[x, y],
    )
    .unwrap();

    assert_eq!(
        graph.node_count(),
        expected["node_count"].as_u64().unwrap() as usize,
        "node_count"
    );
    assert_eq!(
        graph.input_values.len(),
        expected["input_count"].as_u64().unwrap() as usize,
        "input_count"
    );
    let has_mul = expected["has_Mul"].as_bool().unwrap();
    let has_relu = expected["has_Relu"].as_bool().unwrap();
    assert_eq!(
        graph.nodes.iter().any(|n| matches!(n.op, IrOpKind::Mul)),
        has_mul,
        "Mul node present"
    );
    assert_eq!(
        graph.nodes.iter().any(|n| matches!(n.op, IrOpKind::Relu)),
        has_relu,
        "Relu node present"
    );
}

/// trace_mm_sum_structure: trace(|A,B| sum(mm(A,B))) produces 4 nodes.
#[test]
fn trace_mm_sum_structure() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "trace_mm_sum_structure").expect("fixture missing");
    let expected = &fx["expected"];

    let a = grad_mat_f32(vec![1.0, 2.0, 3.0, 4.0, 5.0, 6.0], 2, 3);
    let b = grad_mat_f32(vec![1.0, 0.0, 0.0, 1.0, 1.0, 1.0], 3, 2);
    let graph = trace(
        |inputs: &[Tensor<f32>]| -> FerrotorchResult<Tensor<f32>> {
            let product = mm_differentiable(&inputs[0], &inputs[1])?;
            sum(&product)
        },
        &[a, b],
    )
    .unwrap();

    assert_eq!(
        graph.node_count(),
        expected["node_count"].as_u64().unwrap() as usize,
        "node_count"
    );
    assert_eq!(
        graph.input_values.len(),
        expected["input_count"].as_u64().unwrap() as usize,
        "input_count"
    );
    assert_eq!(
        graph.nodes.iter().any(|n| matches!(n.op, IrOpKind::Mm)),
        expected["has_Mm"].as_bool().unwrap(),
        "Mm node"
    );
    assert_eq!(
        graph.nodes.iter().any(|n| matches!(n.op, IrOpKind::Sum)),
        expected["has_Sum"].as_bool().unwrap(),
        "Sum node"
    );
}

/// trace_no_grad_fn_error: trace() with detached inputs returns an error.
#[test]
fn trace_no_grad_fn_error() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "trace_no_grad_fn_error").expect("fixture missing");
    let expected = &fx["expected"];

    let x =
        Tensor::from_storage(TensorStorage::cpu(vec![1.0f32, 2.0, 3.0]), vec![3], false).unwrap(); // requires_grad = false

    let result = trace(
        |inputs: &[Tensor<f32>]| -> FerrotorchResult<Tensor<f32>> { add(&inputs[0], &inputs[0]) },
        &[x],
    );

    assert!(
        expected["returns_error"].as_bool().unwrap(),
        "fixture says should error"
    );
    assert!(result.is_err(), "trace must return Err for detached inputs");
    let msg = format!("{}", result.unwrap_err());
    let needle = expected["error_contains"].as_str().unwrap();
    assert!(
        msg.contains(needle),
        "error message must contain {needle:?}, got: {msg}",
    );
}

/// trace_deeper_a_plus_b_squared: trace(|a,b| (a+b)*(a+b)) produces 4 nodes.
#[test]
fn trace_deeper_a_plus_b_squared() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "trace_deeper_a_plus_b_squared").expect("fixture missing");
    let expected = &fx["expected"];

    let a = grad_vec_f32(vec![1.0, 2.0]);
    let b = grad_vec_f32(vec![3.0, 4.0]);
    let graph = trace(
        |inputs: &[Tensor<f32>]| -> FerrotorchResult<Tensor<f32>> {
            let s = add(&inputs[0], &inputs[1])?;
            mul(&s, &s)
        },
        &[a, b],
    )
    .unwrap();

    assert_eq!(
        graph.node_count(),
        expected["node_count"].as_u64().unwrap() as usize,
        "node_count"
    );
    assert_eq!(
        graph.input_values.len(),
        expected["input_count"].as_u64().unwrap() as usize,
        "input_count"
    );
    assert_eq!(
        graph.nodes.iter().any(|n| matches!(n.op, IrOpKind::Add)),
        expected["has_Add"].as_bool().unwrap(),
        "Add node"
    );
    assert_eq!(
        graph.nodes.iter().any(|n| matches!(n.op, IrOpKind::Mul)),
        expected["has_Mul"].as_bool().unwrap(),
        "Mul node"
    );
}

// ===========================================================================
// SYMBOLIC — shape guard acceptance/rejection
// ===========================================================================

/// symbolic_guard_accepts_varying_batch: guard with symbolic dim 0 accepts multiple batch sizes.
#[test]
fn symbolic_guard_accepts_varying_batch() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "symbolic_guard_accepts_varying_batch")
        .expect("fixture missing");
    let expected = &fx["expected"];

    let trace_shape = vec![4usize, 10];
    let sig = ShapeSignature::new().symbolic_dim(0, 0);
    let guard = Guard::new(vec![trace_shape], sig);

    for shape in fx["test_shapes_accept"].as_array().unwrap() {
        let s: Vec<usize> = shape
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        let result = guard.check(&[s.as_slice()]);
        assert!(
            result.is_ok(),
            "guard should accept shape {:?}, got: {:?}",
            s,
            result.err()
        );
    }

    assert!(expected["all_pass"].as_bool().unwrap());
}

/// symbolic_guard_rejects_concrete_dim: rejects when concrete dim differs.
#[test]
fn symbolic_guard_rejects_concrete_dim() {
    let fixtures = load_fixtures();
    let fx =
        fixture_by_case(&fixtures, "symbolic_guard_rejects_concrete_dim").expect("fixture missing");
    let expected = &fx["expected"];

    let trace_shape = vec![4usize, 10];
    let sig = ShapeSignature::new().symbolic_dim(0, 0);
    let guard = Guard::new(vec![trace_shape], sig);

    let bad: Vec<usize> = fx["test_shape_reject"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let result = guard.check(&[bad.as_slice()]);

    assert!(
        expected["returns_error"].as_bool().unwrap(),
        "fixture says should error"
    );
    assert!(result.is_err(), "guard must reject concrete dim mismatch");
    let msg = format!("{}", result.unwrap_err());
    let error_dim = expected["error_dim"].as_u64().unwrap();
    assert!(
        msg.contains(&format!("dim {error_dim}")),
        "error must mention dim {error_dim}: {msg}",
    );
}

/// symbolic_guard_rejects_rank_mismatch: rejects inputs with wrong rank.
#[test]
fn symbolic_guard_rejects_rank_mismatch() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "symbolic_guard_rejects_rank_mismatch")
        .expect("fixture missing");
    let expected = &fx["expected"];

    let sig = ShapeSignature::new();
    let guard = Guard::new(vec![vec![4, 10]], sig);

    let bad = vec![4usize, 10, 2];
    let result = guard.check(&[bad.as_slice()]);

    assert!(
        expected["returns_error"].as_bool().unwrap(),
        "fixture says should error"
    );
    assert!(result.is_err(), "guard must reject rank mismatch");
    let msg = format!("{}", result.unwrap_err());
    let needle = expected["error_contains"].as_str().unwrap();
    assert!(msg.contains(needle), "error must contain {needle:?}: {msg}",);
}

/// symbolic_guard_range_below_min: rejects when symbolic dim is below min.
#[test]
fn symbolic_guard_range_below_min() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "symbolic_guard_range_below_min").expect("fixture missing");
    let expected = &fx["expected"];

    let min = fx["min"].as_u64().unwrap() as usize;
    let max = fx["max"].as_u64().unwrap() as usize;
    let sig = ShapeSignature::new().symbolic_dim_with_range(0, 0, min, max);
    let guard = Guard::new(vec![vec![4, 10]], sig);

    let bad: Vec<usize> = fx["test_shape_reject"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let result = guard.check(&[bad.as_slice()]);

    assert!(expected["returns_error"].as_bool().unwrap());
    assert!(result.is_err(), "guard must reject batch below min");
    let msg = format!("{}", result.unwrap_err());
    let needle = expected["error_contains"].as_str().unwrap();
    assert!(msg.contains(needle), "error must contain {needle:?}: {msg}");
}

/// symbolic_guard_range_above_max: rejects when symbolic dim is above max.
#[test]
fn symbolic_guard_range_above_max() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "symbolic_guard_range_above_max").expect("fixture missing");
    let expected = &fx["expected"];

    let min = fx["min"].as_u64().unwrap() as usize;
    let max = fx["max"].as_u64().unwrap() as usize;
    let sig = ShapeSignature::new().symbolic_dim_with_range(0, 0, min, max);
    let guard = Guard::new(vec![vec![4, 10]], sig);

    let bad: Vec<usize> = fx["test_shape_reject"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let result = guard.check(&[bad.as_slice()]);

    assert!(expected["returns_error"].as_bool().unwrap());
    assert!(result.is_err(), "guard must reject batch above max");
    let msg = format!("{}", result.unwrap_err());
    let needle = expected["error_contains"].as_str().unwrap();
    assert!(msg.contains(needle), "error must contain {needle:?}: {msg}");
}

/// symbolic_reshape_patch_single: compile_symbolic with symbolic batch patches reshape
/// [4,10] -> [-1,10] so the module can run with different batch sizes.
///
/// patch_reshape_for_symbolic_dims is now `pub` (#888); we exercise it end-to-end through
/// compile_symbolic which calls it internally — same as the unit tests in symbolic.rs.
#[test]
fn symbolic_reshape_patch_single() {
    use ferrotorch_core::from_vec;
    use ferrotorch_core::grad_fns::shape::reshape;
    use ferrotorch_jit::symbolic::compile_symbolic;

    let fixtures = load_fixtures();
    let _fx = fixture_by_case(&fixtures, "symbolic_reshape_patch_single").expect("fixture missing");

    // Trace a graph that reshapes its input to its own concrete shape [4, 10].
    // With symbolic dim 0, compile_symbolic should patch this to [-1, 10].
    let example = from_vec(
        (0..40).map(|i| (i as f32 - 20.0) * 0.1).collect::<Vec<_>>(),
        &[4, 10],
    )
    .unwrap()
    .requires_grad_(true);

    let sig = ShapeSignature::new().symbolic_dim(0, 0);
    let compiled = compile_symbolic::<f32, _>(
        |inputs| {
            let shape_isize: Vec<isize> = inputs[0].shape().iter().map(|&d| d as isize).collect();
            let r = reshape(&inputs[0], &shape_isize)?;
            relu(&r)
        },
        &[example],
        sig,
    )
    .unwrap();

    // If the patch worked, we can run with batch=9 (impossible if shape was [4,10]).
    let big = from_vec(
        (0..90).map(|i| (i as f32 - 45.0) * 0.1).collect::<Vec<_>>(),
        &[9, 10],
    )
    .unwrap();
    let out = compiled
        .forward_symbolic(std::slice::from_ref(&big))
        .unwrap();

    assert_eq!(
        out.shape(),
        &[9, 10],
        "reshape patch should allow batch=9 after symbolic tracing"
    );
}

/// symbolic_reshape_patch_ambiguous: when trace shape is [4,4] and dim 0 is symbolic,
/// the reshape target [4,4] has the symbolic value in two positions (ambiguous) — the
/// compiled module should still work for the original batch size but the guard will
/// reject mismatching shapes for the non-patched concrete dim.
///
/// We verify the behaviour indirectly: the guard should still accept [4, 4] since both
/// dims equal the trace-time values, and reject [4, 8] because dim 1 is concrete=4.
#[test]
fn symbolic_reshape_patch_ambiguous() {
    use ferrotorch_core::from_vec;
    use ferrotorch_jit::symbolic::compile_symbolic;

    let _fixtures = load_fixtures();
    let _fx =
        fixture_by_case(&_fixtures, "symbolic_reshape_patch_ambiguous").expect("fixture missing");

    let example = from_vec(vec![0.0f32; 16], &[4, 4])
        .unwrap()
        .requires_grad_(true);

    let sig = ShapeSignature::new().symbolic_dim(0, 0);
    let compiled = compile_symbolic::<f32, _>(|inputs| relu(&inputs[0]), &[example], sig).unwrap();

    // [4, 4] must be accepted (same as trace shape).
    let same = from_vec(vec![0.0f32; 16], &[4, 4]).unwrap();
    assert!(
        compiled
            .forward_symbolic(std::slice::from_ref(&same))
            .is_ok(),
        "guard must accept trace-time shape [4,4]"
    );

    // [8, 4] must be accepted (batch varies, feature dim matches).
    let bigger_batch = from_vec(vec![0.0f32; 32], &[8, 4]).unwrap();
    assert!(
        compiled
            .forward_symbolic(std::slice::from_ref(&bigger_batch))
            .is_ok(),
        "guard must accept [8,4] since dim 0 is symbolic"
    );

    // [4, 8] must be rejected (feature dim=4 is concrete, runtime=8 mismatches).
    let wrong_feat = from_vec(vec![0.0f32; 32], &[4, 8]).unwrap();
    let result = compiled.forward_symbolic(std::slice::from_ref(&wrong_feat));
    assert!(
        result.is_err(),
        "guard must reject [4,8] since dim 1 is concrete=4"
    );
}

// ===========================================================================
// CODEGEN_IR — loop IR lowering structural assertions
// ===========================================================================

/// codegen_ir_neg_single_loop: Neg lowers to 1 flat loop.
#[test]
fn codegen_ir_neg_single_loop() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "codegen_ir_neg_single_loop").expect("fixture missing");
    let expected = &fx["expected"];

    let loops = lower_to_loops(&[IrOpKind::Neg], &["in0"], "out", 8);

    assert_eq!(
        loops.len(),
        expected["stmt_count"].as_u64().unwrap() as usize,
        "stmt_count"
    );
    match &loops[0] {
        LoopIR::Loop {
            var,
            start,
            end,
            body,
        } => {
            assert_eq!(var, "i");
            assert_eq!(*start, Expr::int(expected["loop_start"].as_i64().unwrap()));
            assert_eq!(*end, Expr::int(expected["loop_end"].as_i64().unwrap()));
            assert_eq!(
                body.len(),
                expected["body_count"].as_u64().unwrap() as usize
            );
            assert!(
                matches!(body[0], LoopIR::Store { .. }),
                "body[0] must be Store"
            );
        }
        other => panic!("expected Loop, got {other:?}"),
    }
}

/// codegen_ir_add_single_loop: Add lowers to 1 flat loop.
#[test]
fn codegen_ir_add_single_loop() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "codegen_ir_add_single_loop").expect("fixture missing");
    let expected = &fx["expected"];

    let loops = lower_to_loops(&[IrOpKind::Add], &["a", "b"], "out", 4);

    assert_eq!(
        loops.len(),
        expected["stmt_count"].as_u64().unwrap() as usize,
        "stmt_count"
    );
    match &loops[0] {
        LoopIR::Loop { start, end, .. } => {
            assert_eq!(*start, Expr::int(expected["loop_start"].as_i64().unwrap()));
            assert_eq!(*end, Expr::int(expected["loop_end"].as_i64().unwrap()));
        }
        other => panic!("expected Loop, got {other:?}"),
    }
}

/// codegen_ir_sum_reduction: Sum lowers to [Let(acc=0), Loop, Store(out[0])].
#[test]
fn codegen_ir_sum_reduction() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "codegen_ir_sum_reduction").expect("fixture missing");
    let expected = &fx["expected"];

    let loops = lower_to_loops(&[IrOpKind::Sum], &["in0"], "out", 10);

    assert_eq!(
        loops.len(),
        expected["stmt_count"].as_u64().unwrap() as usize,
        "stmt_count"
    );

    // stmt[0]: Let{var="acc", value=Const(0.0)}
    match &loops[0] {
        LoopIR::Let { var, value } => {
            assert_eq!(var.as_str(), expected["stmt_0_var"].as_str().unwrap());
            assert_eq!(
                *value,
                Expr::constant(expected["stmt_0_value"].as_f64().unwrap())
            );
        }
        other => panic!("stmt[0] should be Let, got {other:?}"),
    }

    // stmt[1]: Loop with correct end
    match &loops[1] {
        LoopIR::Loop { end, .. } => {
            assert_eq!(*end, Expr::int(expected["stmt_1_end"].as_i64().unwrap()));
        }
        other => panic!("stmt[1] should be Loop, got {other:?}"),
    }

    // stmt[2]: Store at index 0
    match &loops[2] {
        LoopIR::Store { index, .. } => {
            assert_eq!(
                *index,
                Expr::int(expected["stmt_2_index"].as_i64().unwrap())
            );
        }
        other => panic!("stmt[2] should be Store, got {other:?}"),
    }
}

/// codegen_ir_mean_divides_by_n: Mean final Store divides acc by numel.
#[test]
fn codegen_ir_mean_divides_by_n() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "codegen_ir_mean_divides_by_n").expect("fixture missing");
    let expected = &fx["expected"];

    let loops = lower_to_loops(&[IrOpKind::Mean], &["in0"], "out", 5);
    assert_eq!(
        loops.len(),
        expected["stmt_count"].as_u64().unwrap() as usize
    );

    match &loops[2] {
        LoopIR::Store { value, .. } => match value {
            Expr::BinOp { op, rhs, .. } => {
                assert_eq!(*op, BinOpKind::Div, "mean final store must divide");
                assert_eq!(
                    **rhs,
                    Expr::constant(expected["divisor"].as_f64().unwrap()),
                    "mean divisor mismatch"
                );
            }
            other => panic!("mean store value should be BinOp(Div), got {other:?}"),
        },
        other => panic!("stmt[2] should be Store, got {other:?}"),
    }
}

/// codegen_ir_prod_init_one: Prod initial Let has value=1.0.
#[test]
fn codegen_ir_prod_init_one() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "codegen_ir_prod_init_one").expect("fixture missing");
    let expected = &fx["expected"];

    let loops = lower_to_loops(&[IrOpKind::Prod], &["in0"], "out", 3);
    assert_eq!(
        loops.len(),
        expected["stmt_count"].as_u64().unwrap() as usize
    );

    match &loops[0] {
        LoopIR::Let { value, .. } => {
            assert_eq!(
                *value,
                Expr::constant(expected["stmt_0_value"].as_f64().unwrap()),
                "prod init value mismatch"
            );
        }
        other => panic!("stmt[0] should be Let, got {other:?}"),
    }
}

/// codegen_ir_fused_neg_relu_sigmoid_6_stmts: fused chain has 1 loop with 6-stmt body.
#[test]
fn codegen_ir_fused_neg_relu_sigmoid_6_stmts() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "codegen_ir_fused_neg_relu_sigmoid_6_stmts")
        .expect("fixture missing");
    let expected = &fx["expected"];

    let ops = vec![IrOpKind::Neg, IrOpKind::Relu, IrOpKind::Sigmoid];
    let loops = lower_to_loops(&ops, &["in0"], "out", 4);

    assert_eq!(
        loops.len(),
        expected["stmt_count"].as_u64().unwrap() as usize,
        "fused loop stmt_count"
    );

    match &loops[0] {
        LoopIR::Loop { body, .. } => {
            assert_eq!(
                body.len(),
                expected["body_count"].as_u64().unwrap() as usize,
                "fused body_count"
            );

            // body[0]: Let{var="in0_val"}
            match &body[0] {
                LoopIR::Let { var, .. } => {
                    assert_eq!(
                        var.as_str(),
                        expected["body_0_var"].as_str().unwrap(),
                        "body[0].var"
                    );
                }
                other => panic!("body[0] should be Let, got {other:?}"),
            }

            // body[1]: Let{var="val"}
            match &body[1] {
                LoopIR::Let { var, .. } => {
                    assert_eq!(
                        var.as_str(),
                        expected["body_1_var"].as_str().unwrap(),
                        "body[1].var"
                    );
                }
                other => panic!("body[1] should be Let, got {other:?}"),
            }

            // body[5]: Store to "out"
            match &body[5] {
                LoopIR::Store { buffer, .. } => {
                    assert_eq!(
                        buffer.as_str(),
                        expected["body_5_buffer"].as_str().unwrap(),
                        "body[5] buffer"
                    );
                }
                other => panic!("body[5] should be Store, got {other:?}"),
            }
        }
        other => panic!("stmt[0] should be Loop, got {other:?}"),
    }
}

/// codegen_ir_matmul_triple_nested: lower_matmul produces triple-nested loop.
#[test]
fn codegen_ir_matmul_triple_nested() {
    let fixtures = load_fixtures();
    let fx =
        fixture_by_case(&fixtures, "codegen_ir_matmul_triple_nested").expect("fixture missing");
    let expected = &fx["expected"];

    let m = fx["m"].as_u64().unwrap() as usize;
    let k = fx["k"].as_u64().unwrap() as usize;
    let n = fx["n"].as_u64().unwrap() as usize;
    let loops = lower_matmul("a", "b", "out", m, k, n);

    assert_eq!(
        loops.len(),
        1,
        "lower_matmul must produce exactly 1 top-level loop"
    );
    match &loops[0] {
        LoopIR::Loop { var, end, body, .. } => {
            assert_eq!(
                var.as_str(),
                expected["outer_loop_var"].as_str().unwrap(),
                "outer loop var"
            );
            assert_eq!(
                *end,
                Expr::int(expected["outer_loop_end"].as_i64().unwrap()),
                "outer loop end"
            );
            assert_eq!(body.len(), 1, "outer body has 1 inner loop");
            match &body[0] {
                LoopIR::Loop {
                    var: var_j,
                    end: end_j,
                    body: inner_body,
                    ..
                } => {
                    assert_eq!(
                        var_j.as_str(),
                        expected["inner_loop_var"].as_str().unwrap(),
                        "inner loop var"
                    );
                    assert_eq!(
                        *end_j,
                        Expr::int(expected["inner_loop_end"].as_i64().unwrap()),
                        "inner loop end"
                    );
                    assert_eq!(
                        inner_body.len(),
                        expected["inner_body_count"].as_u64().unwrap() as usize,
                        "inner body count"
                    );
                }
                other => panic!("inner body[0] should be Loop, got {other:?}"),
            }
        }
        other => panic!("loops[0] should be Loop, got {other:?}"),
    }
}

/// codegen_ir_pow_becomes_fn_call: Pow{3.0} lowers to FnCall("powf", [x, 3.0]).
#[test]
fn codegen_ir_pow_becomes_fn_call() {
    let fixtures = load_fixtures();
    let fx = fixture_by_case(&fixtures, "codegen_ir_pow_becomes_fn_call").expect("fixture missing");
    let expected = &fx["expected"];

    let exponent = fx["exponent"].as_f64().unwrap();
    let val = Expr::var("x");
    let result = apply_op_expr(val.clone(), &IrOpKind::Pow { exponent });
    assert!(result.is_some(), "Pow should produce Some(expr)");

    match result.unwrap() {
        Expr::FnCall { name, args } => {
            assert_eq!(
                name.as_str(),
                expected["fn_name"].as_str().unwrap(),
                "fn name"
            );
            assert_eq!(
                args.len(),
                expected["arg_count"].as_u64().unwrap() as usize,
                "arg count"
            );
            assert_eq!(
                args[1],
                Expr::constant(expected["arg_1_value"].as_f64().unwrap()),
                "arg[1] value"
            );
        }
        other => panic!("Pow must produce FnCall, got {other:?}"),
    }
}

/// codegen_ir_op_classification: is_unary_elementwise / is_binary / is_reduction / is_elementwise.
#[test]
fn codegen_ir_op_classification() {
    // Unary elementwise
    for op in [
        IrOpKind::Neg,
        IrOpKind::Exp,
        IrOpKind::Log,
        IrOpKind::Sqrt,
        IrOpKind::Abs,
        IrOpKind::Sigmoid,
        IrOpKind::Tanh,
        IrOpKind::Relu,
        IrOpKind::Gelu,
        IrOpKind::Silu,
    ] {
        assert!(
            is_unary_elementwise(&op),
            "{op:?} must be unary elementwise"
        );
        assert!(
            ir_op_to_unary(&op).is_some(),
            "{op:?} must map via ir_op_to_unary"
        );
        assert!(is_elementwise(&op), "{op:?} must be elementwise");
        assert!(!is_reduction(&op), "{op:?} must not be reduction");
    }

    // Pow is unary elementwise too (parameterized)
    assert!(
        is_unary_elementwise(&IrOpKind::Pow { exponent: 2.0 }),
        "Pow must be unary elementwise"
    );

    // Binary elementwise
    for op in [IrOpKind::Add, IrOpKind::Sub, IrOpKind::Mul, IrOpKind::Div] {
        assert!(
            is_binary_elementwise(&op),
            "{op:?} must be binary elementwise"
        );
        assert!(
            ir_op_to_binary(&op).is_some(),
            "{op:?} must map via ir_op_to_binary"
        );
        assert!(is_elementwise(&op), "{op:?} must be elementwise");
        assert!(!is_reduction(&op), "{op:?} must not be reduction");
    }

    // Reductions
    for op in [IrOpKind::Sum, IrOpKind::Mean, IrOpKind::Prod] {
        assert!(is_reduction(&op), "{op:?} must be reduction");
        assert!(!is_unary_elementwise(&op), "{op:?} must not be unary");
        assert!(!is_binary_elementwise(&op), "{op:?} must not be binary");
    }

    // Non-elementwise
    for op in [IrOpKind::Matmul, IrOpKind::Mm] {
        assert!(!is_elementwise(&op), "{op:?} must not be elementwise");
        assert!(!is_reduction(&op), "{op:?} must not be reduction");
    }
}

/// codegen_ir_apply_binary_op_expr: apply_binary_op_expr produces a BinOp.
#[test]
fn codegen_ir_apply_binary_op_expr() {
    let lhs = Expr::var("a");
    let rhs = Expr::var("b");

    for (op, expected_kind) in [
        (IrOpKind::Add, BinOpKind::Add),
        (IrOpKind::Sub, BinOpKind::Sub),
        (IrOpKind::Mul, BinOpKind::Mul),
        (IrOpKind::Div, BinOpKind::Div),
    ] {
        let result = apply_binary_op_expr(lhs.clone(), rhs.clone(), &op);
        assert!(result.is_some(), "{op:?} should produce Some(expr)");
        match result.unwrap() {
            Expr::BinOp { op: actual_op, .. } => {
                assert_eq!(actual_op, expected_kind, "BinOpKind mismatch for {op:?}");
            }
            other => panic!("{op:?} must produce BinOp, got {other:?}"),
        }
    }

    // Non-binary ops should return None.
    assert!(
        apply_binary_op_expr(lhs.clone(), rhs.clone(), &IrOpKind::Neg).is_none(),
        "Neg should not produce binary expr"
    );
}
