//! #1690 INDEPENDENT RE-AUDIT — batched input-projection autograd parity vs
//! LIVE torch 2.11.0+cu130 (discriminator probe; not the builder's
//! self-consistency test).
//!
//! Commit 689f85b28 folds the seq_len per-timestep `x_t @ W_ih^T` GEMMs into
//! ONE `cat(dim0) -> mm -> narrow(dim0)` GEMM in
//! `ferrotorch-nn/src/rnn.rs` (`batched_input_projection`). The builder's own
//! test `divergence_1690_rnn_batched_input_projection.rs` only checks
//! batched-vs-per-step SELF-consistency, and the sibling
//! `divergence_rnn_hoist_autograd_reaudit.rs` uses a smooth `sin` ramp input
//! that is poorly conditioned to expose a timestep SWAP in the
//! `cat`/`narrow` reassociation.
//!
//! This probe pins the load-bearing claims directly against torch:
//!   - `d_weight_ih` is NOT off by a factor of seq_len, not dropped, not
//!     mis-summed (the accumulation through ONE big matmul node must equal
//!     torch's reference).
//!   - `d_input` scatters to the RIGHT timestep after the `cat`/`narrow`
//!     (DISTINCT per-timestep inputs make a swap visible in BOTH forward
//!     output AND d_input).
//!   - multi-layer (num_layers=2): the per-layer re-derivation of X_all is
//!     correct (layer coupling).
//!   - d_h0 / d_c0 vs torch.
//!
//! R-CHAR-3: every expected value is a LIVE torch constant generated by
//! `/tmp/rnn_1690_oracle.py` (torch.nn.{LSTM,GRU,RNN}, distinct-per-timestep
//! input, non-trivial weighted loss `(out*w).sum()`), NOT copied from
//! ferrotorch. The constants live in `rnn_1690_reaudit_refs.rs.inc`.

#![allow(clippy::excessive_precision)]
#![allow(clippy::approx_constant)]

use ferrotorch_core::grad_fns::arithmetic::mul;
use ferrotorch_core::grad_fns::reduction::sum;
use ferrotorch_core::{Tensor, from_slice};
use ferrotorch_nn::{GRU, LSTM, Module, Parameter, RNN, RNNNonlinearity};
use std::collections::HashMap;

include!("rnn_1690_reaudit_refs.rs.inc");

// Tolerance: torch composes f32 RNN math in a different accumulation order
// than ferrotorch's separate ops. The reaudit sibling verified a 10%-scaled
// negative control is DETECTED at this band, so a factor-of-seq_len or
// dropped-timestep grad bug (>>10% error) is far outside tolerance.
const RTOL: f32 = 2e-4;
const ATOL: f32 = 2e-5;

fn assert_close(actual: &[f32], expected: &[f32], ctx: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{ctx}: length mismatch {} vs {}",
        actual.len(),
        expected.len()
    );
    let mut worst = 0.0f32;
    let mut worst_i = 0;
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        let tol = ATOL + RTOL * e.abs();
        let d = (a - e).abs();
        if d - tol > worst {
            worst = d - tol;
            worst_i = i;
        }
    }
    if worst > 0.0 {
        let (a, e) = (actual[worst_i], expected[worst_i]);
        panic!(
            "{ctx}: diverges from LIVE torch at idx {worst_i}: ferrotorch={a} torch={e} \
             (|d|={}, tol={})",
            (a - e).abs(),
            ATOL + RTOL * e.abs()
        );
    }
}

fn rg(data: &[f32], shape: &[usize]) -> Tensor<f32> {
    from_slice(data, shape).unwrap().requires_grad_(true)
}

/// Same deterministic ramp the torch oracle used for weights:
/// sin(i*0.137 + offset)*scale.
fn ramp(n: usize, scale: f32, offset: f32) -> Vec<f32> {
    (0..n)
        .map(|i| ((i as f32 * 0.137 + offset).sin()) * scale)
        .collect()
}

fn sd_for(layers: usize, hs: usize, insz: usize, gate: usize) -> HashMap<String, Tensor<f32>> {
    let mut sd: HashMap<String, Tensor<f32>> = HashMap::new();
    for l in 0..layers {
        let lin = if l == 0 { insz } else { hs };
        let lf = l as f32;
        sd.insert(
            format!("layers.{l}.weight_ih"),
            from_slice(&ramp(gate * hs * lin, 0.3, lf), &[gate * hs, lin]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.weight_hh"),
            from_slice(&ramp(gate * hs * hs, 0.3, 1.7 + lf), &[gate * hs, hs]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.bias_ih"),
            from_slice(&ramp(gate * hs, 0.1, 0.5 + lf), &[gate * hs]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.bias_hh"),
            from_slice(&ramp(gate * hs, 0.1, 2.3 + lf), &[gate * hs]).unwrap(),
        );
    }
    sd
}

/// Per-layer reference grads, in the parameters() order [wih,whh,bih,bhh].
type LG<'a> = (&'a [f32], &'a [f32], &'a [f32], &'a [f32]);

fn check_layer_grads(params: &[&Parameter<f32>], grads: &[LG], name: &str) {
    for (l, (wih, whh, bih, bhh)) in grads.iter().enumerate() {
        let base = l * 4;
        assert_close(
            params[base]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            wih,
            &format!("{name} layer{l} weight_ih.grad"),
        );
        assert_close(
            params[base + 1]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            whh,
            &format!("{name} layer{l} weight_hh.grad"),
        );
        assert_close(
            params[base + 2]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            bih,
            &format!("{name} layer{l} bias_ih.grad"),
        );
        assert_close(
            params[base + 3]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            bhh,
            &format!("{name} layer{l} bias_hh.grad"),
        );
    }
}

// ----- LSTM -----------------------------------------------------------------

#[allow(clippy::too_many_arguments)]
fn run_lstm(
    name: &str,
    batch: usize,
    seq: usize,
    insz: usize,
    hs: usize,
    layers: usize,
    xin: &[f32],
    out_ref: &[f32],
    hn_ref: &[f32],
    cn_ref: &[f32],
    lossw: &[f32],
    grads: &[LG],
    xgrad: &[f32],
    h0grad: &[f32],
    c0grad: &[f32],
) {
    let mut lstm = LSTM::<f32>::new(insz, hs, layers).unwrap();
    lstm.load_state_dict(&sd_for(layers, hs, insz, 4), true)
        .unwrap();

    let x = rg(xin, &[batch, seq, insz]);
    let h0 = rg(&ramp(layers * batch * hs, 0.2, 3.1), &[layers, batch, hs]);
    let c0 = rg(&ramp(layers * batch * hs, 0.2, 4.4), &[layers, batch, hs]);

    let (out, (hn, cn)) = lstm.forward_with_state(&x, Some((&h0, &c0))).unwrap();
    assert_close(out.data().unwrap(), out_ref, &format!("{name} output"));
    assert_close(hn.data().unwrap(), hn_ref, &format!("{name} h_n"));
    assert_close(cn.data().unwrap(), cn_ref, &format!("{name} c_n"));

    let w = from_slice(lossw, out.shape()).unwrap();
    sum(&mul(&out, &w).unwrap()).unwrap().backward().unwrap();

    check_layer_grads(&lstm.parameters(), grads, name);
    assert_close(
        x.grad()
            .unwrap()
            .expect("gradient should be populated")
            .data()
            .unwrap(),
        xgrad,
        &format!("{name} input.grad"),
    );
    assert_close(
        h0.grad()
            .unwrap()
            .expect("gradient should be populated")
            .data()
            .unwrap(),
        h0grad,
        &format!("{name} h0.grad"),
    );
    assert_close(
        c0.grad()
            .unwrap()
            .expect("gradient should be populated")
            .data()
            .unwrap(),
        c0grad,
        &format!("{name} c0.grad"),
    );
}

#[test]
fn lstm_state_batched_proj_vs_live_torch() {
    // cfg: batch=3 seq=5 in=4 hs=6 layers=1
    run_lstm(
        "LSTM 1L",
        3,
        5,
        4,
        6,
        1,
        LSTM_STATE_XIN,
        LSTM_STATE_OUT,
        LSTM_STATE_HN,
        LSTM_STATE_CN,
        LSTM_STATE_LOSSW,
        &[(
            LSTM_STATE_WIH_0,
            LSTM_STATE_WHH_0,
            LSTM_STATE_BIH_0,
            LSTM_STATE_BHH_0,
        )],
        LSTM_STATE_XGRAD,
        LSTM_STATE_H0GRAD,
        LSTM_STATE_C0GRAD,
    );
}

#[test]
fn lstm_2layer_batched_proj_vs_live_torch() {
    // cfg: batch=2 seq=4 in=3 hs=5 layers=2
    run_lstm(
        "LSTM 2L",
        2,
        4,
        3,
        5,
        2,
        LSTM_2LAYER_XIN,
        LSTM_2LAYER_OUT,
        LSTM_2LAYER_HN,
        LSTM_2LAYER_CN,
        LSTM_2LAYER_LOSSW,
        &[
            (
                LSTM_2LAYER_WIH_0,
                LSTM_2LAYER_WHH_0,
                LSTM_2LAYER_BIH_0,
                LSTM_2LAYER_BHH_0,
            ),
            (
                LSTM_2LAYER_WIH_1,
                LSTM_2LAYER_WHH_1,
                LSTM_2LAYER_BIH_1,
                LSTM_2LAYER_BHH_1,
            ),
        ],
        LSTM_2LAYER_XGRAD,
        LSTM_2LAYER_H0GRAD,
        LSTM_2LAYER_C0GRAD,
    );
}

// ----- GRU ------------------------------------------------------------------

#[allow(clippy::too_many_arguments)]
fn run_gru(
    name: &str,
    batch: usize,
    seq: usize,
    insz: usize,
    hs: usize,
    layers: usize,
    xin: &[f32],
    out_ref: &[f32],
    hn_ref: &[f32],
    lossw: &[f32],
    grads: &[LG],
    xgrad: &[f32],
    h0grad: &[f32],
) {
    let mut gru = GRU::<f32>::with_num_layers(insz, hs, layers).unwrap();
    gru.load_state_dict(&sd_for(layers, hs, insz, 3), true)
        .unwrap();

    let x = rg(xin, &[batch, seq, insz]);
    let h0 = rg(&ramp(layers * batch * hs, 0.2, 3.1), &[layers, batch, hs]);

    let (out, hn) = gru.forward(&x, Some(&h0)).unwrap();
    assert_close(out.data().unwrap(), out_ref, &format!("{name} output"));
    assert_close(hn.data().unwrap(), hn_ref, &format!("{name} h_n"));

    let w = from_slice(lossw, out.shape()).unwrap();
    sum(&mul(&out, &w).unwrap()).unwrap().backward().unwrap();

    check_layer_grads(&gru.parameters(), grads, name);
    assert_close(
        x.grad()
            .unwrap()
            .expect("gradient should be populated")
            .data()
            .unwrap(),
        xgrad,
        &format!("{name} input.grad"),
    );
    assert_close(
        h0.grad()
            .unwrap()
            .expect("gradient should be populated")
            .data()
            .unwrap(),
        h0grad,
        &format!("{name} h0.grad"),
    );
}

#[test]
fn gru_state_batched_proj_vs_live_torch() {
    run_gru(
        "GRU 1L",
        3,
        5,
        4,
        6,
        1,
        GRU_STATE_XIN,
        GRU_STATE_OUT,
        GRU_STATE_HN,
        GRU_STATE_LOSSW,
        &[(
            GRU_STATE_WIH_0,
            GRU_STATE_WHH_0,
            GRU_STATE_BIH_0,
            GRU_STATE_BHH_0,
        )],
        GRU_STATE_XGRAD,
        GRU_STATE_H0GRAD,
    );
}

#[test]
fn gru_2layer_batched_proj_vs_live_torch() {
    run_gru(
        "GRU 2L",
        2,
        4,
        3,
        5,
        2,
        GRU_2LAYER_XIN,
        GRU_2LAYER_OUT,
        GRU_2LAYER_HN,
        GRU_2LAYER_LOSSW,
        &[
            (
                GRU_2LAYER_WIH_0,
                GRU_2LAYER_WHH_0,
                GRU_2LAYER_BIH_0,
                GRU_2LAYER_BHH_0,
            ),
            (
                GRU_2LAYER_WIH_1,
                GRU_2LAYER_WHH_1,
                GRU_2LAYER_BIH_1,
                GRU_2LAYER_BHH_1,
            ),
        ],
        GRU_2LAYER_XGRAD,
        GRU_2LAYER_H0GRAD,
    );
}

// ----- RNN ------------------------------------------------------------------

#[allow(clippy::too_many_arguments)]
fn run_rnn(
    name: &str,
    nonlin: RNNNonlinearity,
    batch: usize,
    seq: usize,
    insz: usize,
    hs: usize,
    layers: usize,
    xin: &[f32],
    out_ref: &[f32],
    hn_ref: &[f32],
    lossw: &[f32],
    grads: &[LG],
    xgrad: &[f32],
    h0grad: &[f32],
) {
    let mut rnn = RNN::<f32>::with_options(insz, hs, layers, nonlin).unwrap();
    rnn.load_state_dict(&sd_for(layers, hs, insz, 1), true)
        .unwrap();

    let x = rg(xin, &[batch, seq, insz]);
    let h0 = rg(&ramp(layers * batch * hs, 0.2, 3.1), &[layers, batch, hs]);

    let (out, hn) = rnn.forward_with_state(&x, Some(&h0)).unwrap();
    assert_close(out.data().unwrap(), out_ref, &format!("{name} output"));
    assert_close(hn.data().unwrap(), hn_ref, &format!("{name} h_n"));

    let w = from_slice(lossw, out.shape()).unwrap();
    sum(&mul(&out, &w).unwrap()).unwrap().backward().unwrap();

    check_layer_grads(&rnn.parameters(), grads, name);
    assert_close(
        x.grad()
            .unwrap()
            .expect("gradient should be populated")
            .data()
            .unwrap(),
        xgrad,
        &format!("{name} input.grad"),
    );
    assert_close(
        h0.grad()
            .unwrap()
            .expect("gradient should be populated")
            .data()
            .unwrap(),
        h0grad,
        &format!("{name} h0.grad"),
    );
}

#[test]
fn rnn_tanh_state_batched_proj_vs_live_torch() {
    run_rnn(
        "RNN-tanh",
        RNNNonlinearity::Tanh,
        3,
        5,
        4,
        6,
        1,
        RNN_TANH_STATE_XIN,
        RNN_TANH_STATE_OUT,
        RNN_TANH_STATE_HN,
        RNN_TANH_STATE_LOSSW,
        &[(
            RNN_TANH_STATE_WIH_0,
            RNN_TANH_STATE_WHH_0,
            RNN_TANH_STATE_BIH_0,
            RNN_TANH_STATE_BHH_0,
        )],
        RNN_TANH_STATE_XGRAD,
        RNN_TANH_STATE_H0GRAD,
    );
}

#[test]
fn rnn_relu_state_batched_proj_vs_live_torch() {
    run_rnn(
        "RNN-relu",
        RNNNonlinearity::ReLU,
        3,
        5,
        4,
        6,
        1,
        RNN_RELU_STATE_XIN,
        RNN_RELU_STATE_OUT,
        RNN_RELU_STATE_HN,
        RNN_RELU_STATE_LOSSW,
        &[(
            RNN_RELU_STATE_WIH_0,
            RNN_RELU_STATE_WHH_0,
            RNN_RELU_STATE_BIH_0,
            RNN_RELU_STATE_BHH_0,
        )],
        RNN_RELU_STATE_XGRAD,
        RNN_RELU_STATE_H0GRAD,
    );
}
