//! #1680 ADVERSARIAL RE-AUDIT — RNN/GRU/LSTM sequence forward weight-transpose
//! hoist autograd correctness vs LIVE torch.
//!
//! Commit 323af7657 hoisted the constant recurrent-weight transpose out of the
//! per-timestep loop (transpose+`.contiguous()` once per layer, reused across
//! all timesteps) for LSTM/GRU/RNN forward. The load-bearing concern: ONE
//! transpose+contiguous node now feeds EVERY per-step matmul instead of
//! `seq_len` separate nodes. A bug where the shared node accumulates grad from
//! only the LAST timestep (not summed across all steps) would silently corrupt
//! every recurrent weight gradient and break all RNN training.
//!
//! The generator's own #1680 test (`divergence_1680_rnn_seq_transpose_hoist.rs`)
//! is a *self-consistency* check (hoisted-prod == inline-per-step reference) —
//! it cannot detect a shared-math error common to both shapes. THIS test pins
//! the behavior to LIVE `torch.nn.{LSTM,GRU,RNN}` backward.
//!
//! R-CHAR-3 compliance: every expected value is a named constant in
//! `rnn_torch_refs.rs.inc`, AUTO-GENERATED by
//! `tools/parity-sweep/runs/rnn_hoist/rnn_hoist_oracle.py` running torch
//! 2.11.0+cu130 (`torch.nn.LSTM/GRU/RNN`, `batch_first=True`, identical ramp
//! weights `sin(i*0.137+offset)*scale`, weighted-output loss `sum(out * lossw)`
//! with a non-uniform `lossw` ramp). The raw JSON is committed alongside at
//! `tools/parity-sweep/runs/rnn_hoist/rnn_hoist_torch_refs.json`. Expected
//! values are the torch oracle, NOT copied from the module under test.
//!
//! Covered (HUNT items 2,3,5): GRU, LSTM, RNN(tanh), RNN(relu); with/without
//! initial state (h0/c0); num_layers=2 (per-layer hoist, cross-layer bleed);
//! seq_len=1 (degenerate) and seq_len=8 (long); weight_ih/weight_hh/bias_ih/
//! bias_hh AND input.grad element-wise. Forward output + h_n (+ c_n) parity too.

#![allow(clippy::excessive_precision)]
#![allow(clippy::approx_constant)]

use ferrotorch_core::grad_fns::arithmetic::mul;
use ferrotorch_core::grad_fns::reduction::sum;
use ferrotorch_core::{Tensor, from_slice};
use ferrotorch_nn::{GRU, LSTM, Module, RNN, RNNNonlinearity};
use std::collections::HashMap;

include!("rnn_torch_refs.rs.inc");

/// Per-layer reference gradients: (weight_ih, weight_hh, bias_ih, bias_hh).
type LayerGrads<'a> = (&'a [f32], &'a [f32], &'a [f32], &'a [f32]);

/// Tolerance: torch runs cuDNN/native fused RNN in f32; ferrotorch composes the
/// same math from separate f32 ops. Accumulation order differs, so use a
/// relative+absolute band sized for f32 over these small shapes. A negative
/// control (10%-scaled reference) was verified to be DETECTED at this band, so
/// the ~5x error a "last-timestep-only grad accumulation" bug would cause is
/// far outside tolerance.
const RTOL: f32 = 2e-4;
const ATOL: f32 = 2e-5;

fn assert_close(actual: &[f32], expected: &[f32], ctx: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{ctx}: length mismatch {} vs {}",
        actual.len(),
        expected.len()
    );
    let mut worst = 0.0f32;
    let mut worst_i = 0;
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        let tol = ATOL + RTOL * e.abs();
        let d = (a - e).abs();
        if d - tol > worst {
            worst = d - tol;
            worst_i = i;
        }
    }
    if worst > 0.0 {
        let (a, e) = (actual[worst_i], expected[worst_i]);
        panic!(
            "{ctx}: diverges from torch at idx {worst_i}: ferrotorch={a} torch={e} \
             (|d|={}, tol={})",
            (a - e).abs(),
            ATOL + RTOL * e.abs()
        );
    }
}

fn rg(data: &[f32], shape: &[usize]) -> Tensor<f32> {
    from_slice(data, shape).unwrap().requires_grad_(true)
}

/// Same deterministic ramp the torch oracle used: sin(i*0.137 + offset)*scale.
fn ramp(n: usize, scale: f32, offset: f32) -> Vec<f32> {
    (0..n)
        .map(|i| ((i as f32 * 0.137 + offset).sin()) * scale)
        .collect()
}

// ---- LSTM ----------------------------------------------------------------

fn load_lstm(lstm: &mut LSTM<f32>, layers: usize, hs: usize, insz: usize) {
    let mut sd: HashMap<String, Tensor<f32>> = HashMap::new();
    for l in 0..layers {
        let lin = if l == 0 { insz } else { hs };
        let lf = l as f32;
        sd.insert(
            format!("layers.{l}.weight_ih"),
            from_slice(&ramp(4 * hs * lin, 0.3, lf), &[4 * hs, lin]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.weight_hh"),
            from_slice(&ramp(4 * hs * hs, 0.3, 1.7 + lf), &[4 * hs, hs]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.bias_ih"),
            from_slice(&ramp(4 * hs, 0.1, 0.5 + lf), &[4 * hs]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.bias_hh"),
            from_slice(&ramp(4 * hs, 0.1, 2.3 + lf), &[4 * hs]).unwrap(),
        );
    }
    lstm.load_state_dict(&sd, true).unwrap();
}

#[allow(clippy::too_many_arguments)]
fn run_lstm_check(
    name: &str,
    batch: usize,
    seq: usize,
    insz: usize,
    hs: usize,
    layers: usize,
    with_state: bool,
    loss_on_hn: bool,
    out_ref: &[f32],
    hn_ref: &[f32],
    cn_ref: &[f32],
    lossw: &[f32],
    grads: &[LayerGrads],
    xgrad_ref: &[f32],
    h0grad_ref: Option<&[f32]>,
    c0grad_ref: Option<&[f32]>,
) {
    let mut lstm = LSTM::<f32>::new(insz, hs, layers).unwrap();
    load_lstm(&mut lstm, layers, hs, insz);

    let x = rg(&ramp(batch * seq * insz, 0.5, 0.9), &[batch, seq, insz]);
    let (h0, c0) = if with_state {
        (
            Some(rg(
                &ramp(layers * batch * hs, 0.2, 3.1),
                &[layers, batch, hs],
            )),
            Some(rg(
                &ramp(layers * batch * hs, 0.2, 4.4),
                &[layers, batch, hs],
            )),
        )
    } else {
        (None, None)
    };
    let state = match (&h0, &c0) {
        (Some(h), Some(c)) => Some((h, c)),
        _ => None,
    };

    let (out, (hn, cn)) = lstm.forward_with_state(&x, state).unwrap();

    assert_close(out.data().unwrap(), out_ref, &format!("{name} LSTM output"));
    assert_close(hn.data().unwrap(), hn_ref, &format!("{name} LSTM h_n"));
    assert_close(cn.data().unwrap(), cn_ref, &format!("{name} LSTM c_n"));

    // Non-uniform weighted loss (matches torch oracle).
    let target = if loss_on_hn { &hn } else { &out };
    let w = from_slice(lossw, target.shape()).unwrap();
    let loss = sum(&mul(target, &w).unwrap()).unwrap();
    loss.backward().unwrap();

    let params = lstm.parameters(); // [l0.wih,l0.whh,l0.bih,l0.bhh, l1...]
    for (l, (wih, whh, bih, bhh)) in grads.iter().enumerate() {
        let base = l * 4;
        assert_close(
            params[base]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            wih,
            &format!("{name} layer{l} weight_ih.grad"),
        );
        assert_close(
            params[base + 1]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            whh,
            &format!("{name} layer{l} weight_hh.grad"),
        );
        assert_close(
            params[base + 2]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            bih,
            &format!("{name} layer{l} bias_ih.grad"),
        );
        assert_close(
            params[base + 3]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            bhh,
            &format!("{name} layer{l} bias_hh.grad"),
        );
    }
    assert_close(
        x.grad().unwrap().unwrap().data().unwrap(),
        xgrad_ref,
        &format!("{name} input.grad"),
    );
    if let Some(hg) = h0grad_ref {
        assert_close(
            h0.unwrap().grad().unwrap().unwrap().data().unwrap(),
            hg,
            &format!("{name} h0.grad"),
        );
    }
    if let Some(cg) = c0grad_ref {
        assert_close(
            c0.unwrap().grad().unwrap().unwrap().data().unwrap(),
            cg,
            &format!("{name} c0.grad"),
        );
    }
}

#[test]
fn lstm_grads_match_torch_with_state() {
    run_lstm_check(
        "lstm_state",
        3,
        5,
        4,
        6,
        1,
        true,
        false,
        LSTM_STATE_OUT,
        LSTM_STATE_HN,
        LSTM_STATE_CN,
        LSTM_STATE_LOSSW,
        &[(
            LSTM_STATE_WIH0,
            LSTM_STATE_WHH0,
            LSTM_STATE_BIH0,
            LSTM_STATE_BHH0,
        )],
        LSTM_STATE_XGRAD,
        Some(LSTM_STATE_H0GRAD),
        Some(LSTM_STATE_C0GRAD),
    );
}

#[test]
fn lstm_grads_match_torch_nostate_long_seq() {
    run_lstm_check(
        "lstm_nostate_long",
        2,
        8,
        3,
        5,
        1,
        false,
        true,
        LSTM_NOSTATE_LONG_OUT,
        LSTM_NOSTATE_LONG_HN,
        LSTM_NOSTATE_LONG_CN,
        LSTM_NOSTATE_LONG_LOSSW,
        &[(
            LSTM_NOSTATE_LONG_WIH0,
            LSTM_NOSTATE_LONG_WHH0,
            LSTM_NOSTATE_LONG_BIH0,
            LSTM_NOSTATE_LONG_BHH0,
        )],
        LSTM_NOSTATE_LONG_XGRAD,
        None,
        None,
    );
}

#[test]
fn lstm_grads_match_torch_2layer() {
    run_lstm_check(
        "lstm_2layer",
        2,
        4,
        3,
        4,
        2,
        true,
        false,
        LSTM_2LAYER_OUT,
        LSTM_2LAYER_HN,
        LSTM_2LAYER_CN,
        LSTM_2LAYER_LOSSW,
        &[
            (
                LSTM_2LAYER_WIH0,
                LSTM_2LAYER_WHH0,
                LSTM_2LAYER_BIH0,
                LSTM_2LAYER_BHH0,
            ),
            (
                LSTM_2LAYER_WIH1,
                LSTM_2LAYER_WHH1,
                LSTM_2LAYER_BIH1,
                LSTM_2LAYER_BHH1,
            ),
        ],
        LSTM_2LAYER_XGRAD,
        Some(LSTM_2LAYER_H0GRAD),
        Some(LSTM_2LAYER_C0GRAD),
    );
}

#[test]
fn lstm_grads_match_torch_seq1() {
    run_lstm_check(
        "lstm_seq1",
        3,
        1,
        4,
        5,
        1,
        true,
        false,
        LSTM_SEQ1_OUT,
        LSTM_SEQ1_HN,
        LSTM_SEQ1_CN,
        LSTM_SEQ1_LOSSW,
        &[(
            LSTM_SEQ1_WIH0,
            LSTM_SEQ1_WHH0,
            LSTM_SEQ1_BIH0,
            LSTM_SEQ1_BHH0,
        )],
        LSTM_SEQ1_XGRAD,
        Some(LSTM_SEQ1_H0GRAD),
        Some(LSTM_SEQ1_C0GRAD),
    );
}

// ---- GRU -----------------------------------------------------------------

fn load_gru(gru: &mut GRU<f32>, layers: usize, hs: usize, insz: usize) {
    let mut sd: HashMap<String, Tensor<f32>> = HashMap::new();
    for l in 0..layers {
        let lin = if l == 0 { insz } else { hs };
        let lf = l as f32;
        sd.insert(
            format!("layers.{l}.weight_ih"),
            from_slice(&ramp(3 * hs * lin, 0.3, lf), &[3 * hs, lin]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.weight_hh"),
            from_slice(&ramp(3 * hs * hs, 0.3, 1.7 + lf), &[3 * hs, hs]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.bias_ih"),
            from_slice(&ramp(3 * hs, 0.1, 0.5 + lf), &[3 * hs]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.bias_hh"),
            from_slice(&ramp(3 * hs, 0.1, 2.3 + lf), &[3 * hs]).unwrap(),
        );
    }
    gru.load_state_dict(&sd, true).unwrap();
}

#[allow(clippy::too_many_arguments)]
fn run_gru_check(
    name: &str,
    batch: usize,
    seq: usize,
    insz: usize,
    hs: usize,
    layers: usize,
    with_state: bool,
    out_ref: &[f32],
    hn_ref: &[f32],
    lossw: &[f32],
    grads: &[LayerGrads],
    xgrad_ref: &[f32],
    h0grad_ref: Option<&[f32]>,
) {
    let mut gru = GRU::<f32>::with_num_layers(insz, hs, layers).unwrap();
    load_gru(&mut gru, layers, hs, insz);
    let x = rg(&ramp(batch * seq * insz, 0.5, 0.9), &[batch, seq, insz]);
    let h0 = if with_state {
        Some(rg(
            &ramp(layers * batch * hs, 0.2, 3.1),
            &[layers, batch, hs],
        ))
    } else {
        None
    };
    let (out, hn) = gru.forward(&x, h0.as_ref()).unwrap();
    assert_close(out.data().unwrap(), out_ref, &format!("{name} GRU output"));
    assert_close(hn.data().unwrap(), hn_ref, &format!("{name} GRU h_n"));

    let w = from_slice(lossw, out.shape()).unwrap();
    sum(&mul(&out, &w).unwrap()).unwrap().backward().unwrap();

    let params = gru.parameters();
    for (l, (wih, whh, bih, bhh)) in grads.iter().enumerate() {
        let base = l * 4;
        assert_close(
            params[base]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            wih,
            &format!("{name} layer{l} weight_ih.grad"),
        );
        assert_close(
            params[base + 1]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            whh,
            &format!("{name} layer{l} weight_hh.grad"),
        );
        assert_close(
            params[base + 2]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            bih,
            &format!("{name} layer{l} bias_ih.grad"),
        );
        assert_close(
            params[base + 3]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            bhh,
            &format!("{name} layer{l} bias_hh.grad"),
        );
    }
    assert_close(
        x.grad().unwrap().unwrap().data().unwrap(),
        xgrad_ref,
        &format!("{name} input.grad"),
    );
    if let Some(hg) = h0grad_ref {
        assert_close(
            h0.unwrap().grad().unwrap().unwrap().data().unwrap(),
            hg,
            &format!("{name} h0.grad"),
        );
    }
}

#[test]
fn gru_grads_match_torch_with_state() {
    run_gru_check(
        "gru_state",
        3,
        5,
        4,
        6,
        1,
        true,
        GRU_STATE_OUT,
        GRU_STATE_HN,
        GRU_STATE_LOSSW,
        &[(
            GRU_STATE_WIH0,
            GRU_STATE_WHH0,
            GRU_STATE_BIH0,
            GRU_STATE_BHH0,
        )],
        GRU_STATE_XGRAD,
        Some(GRU_STATE_H0GRAD),
    );
}

#[test]
fn gru_grads_match_torch_2layer() {
    run_gru_check(
        "gru_2layer",
        2,
        4,
        3,
        4,
        2,
        true,
        GRU_2LAYER_OUT,
        GRU_2LAYER_HN,
        GRU_2LAYER_LOSSW,
        &[
            (
                GRU_2LAYER_WIH0,
                GRU_2LAYER_WHH0,
                GRU_2LAYER_BIH0,
                GRU_2LAYER_BHH0,
            ),
            (
                GRU_2LAYER_WIH1,
                GRU_2LAYER_WHH1,
                GRU_2LAYER_BIH1,
                GRU_2LAYER_BHH1,
            ),
        ],
        GRU_2LAYER_XGRAD,
        Some(GRU_2LAYER_H0GRAD),
    );
}

#[test]
fn gru_grads_match_torch_seq1_nostate() {
    run_gru_check(
        "gru_seq1",
        3,
        1,
        4,
        5,
        1,
        false,
        GRU_SEQ1_OUT,
        GRU_SEQ1_HN,
        GRU_SEQ1_LOSSW,
        &[(GRU_SEQ1_WIH0, GRU_SEQ1_WHH0, GRU_SEQ1_BIH0, GRU_SEQ1_BHH0)],
        GRU_SEQ1_XGRAD,
        None,
    );
}

// ---- RNN (tanh / relu) ---------------------------------------------------

fn load_rnn(rnn: &mut RNN<f32>, layers: usize, hs: usize, insz: usize) {
    let mut sd: HashMap<String, Tensor<f32>> = HashMap::new();
    for l in 0..layers {
        let lin = if l == 0 { insz } else { hs };
        let lf = l as f32;
        sd.insert(
            format!("layers.{l}.weight_ih"),
            from_slice(&ramp(hs * lin, 0.3, lf), &[hs, lin]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.weight_hh"),
            from_slice(&ramp(hs * hs, 0.3, 1.7 + lf), &[hs, hs]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.bias_ih"),
            from_slice(&ramp(hs, 0.1, 0.5 + lf), &[hs]).unwrap(),
        );
        sd.insert(
            format!("layers.{l}.bias_hh"),
            from_slice(&ramp(hs, 0.1, 2.3 + lf), &[hs]).unwrap(),
        );
    }
    rnn.load_state_dict(&sd, true).unwrap();
}

#[allow(clippy::too_many_arguments)]
fn run_rnn_check(
    name: &str,
    nonlin: RNNNonlinearity,
    batch: usize,
    seq: usize,
    insz: usize,
    hs: usize,
    layers: usize,
    with_state: bool,
    out_ref: &[f32],
    hn_ref: &[f32],
    lossw: &[f32],
    grads: &[LayerGrads],
    xgrad_ref: &[f32],
    h0grad_ref: Option<&[f32]>,
) {
    let mut rnn = RNN::<f32>::with_options(insz, hs, layers, nonlin).unwrap();
    load_rnn(&mut rnn, layers, hs, insz);
    let x = rg(&ramp(batch * seq * insz, 0.5, 0.9), &[batch, seq, insz]);
    let h0 = if with_state {
        Some(rg(
            &ramp(layers * batch * hs, 0.2, 3.1),
            &[layers, batch, hs],
        ))
    } else {
        None
    };
    let (out, hn) = rnn.forward_with_state(&x, h0.as_ref()).unwrap();
    assert_close(out.data().unwrap(), out_ref, &format!("{name} RNN output"));
    assert_close(hn.data().unwrap(), hn_ref, &format!("{name} RNN h_n"));

    let w = from_slice(lossw, out.shape()).unwrap();
    sum(&mul(&out, &w).unwrap()).unwrap().backward().unwrap();

    let params = rnn.parameters();
    for (l, (wih, whh, bih, bhh)) in grads.iter().enumerate() {
        let base = l * 4;
        assert_close(
            params[base]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            wih,
            &format!("{name} layer{l} weight_ih.grad"),
        );
        assert_close(
            params[base + 1]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            whh,
            &format!("{name} layer{l} weight_hh.grad"),
        );
        assert_close(
            params[base + 2]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            bih,
            &format!("{name} layer{l} bias_ih.grad"),
        );
        assert_close(
            params[base + 3]
                .tensor()
                .grad()
                .unwrap()
                .unwrap()
                .data()
                .unwrap(),
            bhh,
            &format!("{name} layer{l} bias_hh.grad"),
        );
    }
    assert_close(
        x.grad().unwrap().unwrap().data().unwrap(),
        xgrad_ref,
        &format!("{name} input.grad"),
    );
    if let Some(hg) = h0grad_ref {
        assert_close(
            h0.unwrap().grad().unwrap().unwrap().data().unwrap(),
            hg,
            &format!("{name} h0.grad"),
        );
    }
}

#[test]
fn rnn_tanh_grads_match_torch_with_state() {
    run_rnn_check(
        "rnn_tanh_state",
        RNNNonlinearity::Tanh,
        3,
        5,
        4,
        6,
        1,
        true,
        RNN_TANH_STATE_OUT,
        RNN_TANH_STATE_HN,
        RNN_TANH_STATE_LOSSW,
        &[(
            RNN_TANH_STATE_WIH0,
            RNN_TANH_STATE_WHH0,
            RNN_TANH_STATE_BIH0,
            RNN_TANH_STATE_BHH0,
        )],
        RNN_TANH_STATE_XGRAD,
        Some(RNN_TANH_STATE_H0GRAD),
    );
}

#[test]
fn rnn_relu_grads_match_torch_with_state() {
    run_rnn_check(
        "rnn_relu_state",
        RNNNonlinearity::ReLU,
        3,
        5,
        4,
        6,
        1,
        true,
        RNN_RELU_STATE_OUT,
        RNN_RELU_STATE_HN,
        RNN_RELU_STATE_LOSSW,
        &[(
            RNN_RELU_STATE_WIH0,
            RNN_RELU_STATE_WHH0,
            RNN_RELU_STATE_BIH0,
            RNN_RELU_STATE_BHH0,
        )],
        RNN_RELU_STATE_XGRAD,
        Some(RNN_RELU_STATE_H0GRAD),
    );
}

#[test]
fn rnn_tanh_grads_match_torch_2layer() {
    run_rnn_check(
        "rnn_tanh_2layer",
        RNNNonlinearity::Tanh,
        2,
        4,
        3,
        4,
        2,
        true,
        RNN_TANH_2LAYER_OUT,
        RNN_TANH_2LAYER_HN,
        RNN_TANH_2LAYER_LOSSW,
        &[
            (
                RNN_TANH_2LAYER_WIH0,
                RNN_TANH_2LAYER_WHH0,
                RNN_TANH_2LAYER_BIH0,
                RNN_TANH_2LAYER_BHH0,
            ),
            (
                RNN_TANH_2LAYER_WIH1,
                RNN_TANH_2LAYER_WHH1,
                RNN_TANH_2LAYER_BIH1,
                RNN_TANH_2LAYER_BHH1,
            ),
        ],
        RNN_TANH_2LAYER_XGRAD,
        Some(RNN_TANH_2LAYER_H0GRAD),
    );
}
