//! Phase 11 (#998 / #1013) probe: ferrotorch swin_tiny named_parameters
//! must match the torchvision swin_t state-dict key set 1:1.
//!
//! This is a "probe-before-fix" diagnostic — it surfaces every key
//! diff between ferrotorch and torchvision so the strict value-parity
//! loader's downstream "extra key" / "missing param" failures are
//! pre-empted with a humanly-readable diff.

use ferrotorch_nn::module::Module;
use ferrotorch_vision::models::swin::swin_tiny;
use std::collections::BTreeSet;

#[test]
fn probe_swin_tiny_named_parameters_match_torchvision() {
    let model = swin_tiny::<f32>(1000).expect("swin_tiny construction");
    let actual: BTreeSet<String> = model
        .named_parameters()
        .into_iter()
        .map(|(n, _)| n)
        .collect();

    // Sourced 1:1 from
    // ferrotorch-vision/tests/conformance/fixtures_value_parity.json
    // → swin_t_value_parity.param_keys, generated by torchvision's
    // `tvm.swin_t(weights=None).named_parameters()` directly.
    let expected_raw: &[&str] = &[
        "features.0.0.bias",
        "features.0.0.weight",
        "features.0.2.bias",
        "features.0.2.weight",
        "features.1.0.attn.proj.bias",
        "features.1.0.attn.proj.weight",
        "features.1.0.attn.qkv.bias",
        "features.1.0.attn.qkv.weight",
        "features.1.0.attn.relative_position_bias_table",
        "features.1.0.mlp.0.bias",
        "features.1.0.mlp.0.weight",
        "features.1.0.mlp.3.bias",
        "features.1.0.mlp.3.weight",
        "features.1.0.norm1.bias",
        "features.1.0.norm1.weight",
        "features.1.0.norm2.bias",
        "features.1.0.norm2.weight",
        "features.1.1.attn.proj.bias",
        "features.1.1.attn.proj.weight",
        "features.1.1.attn.qkv.bias",
        "features.1.1.attn.qkv.weight",
        "features.1.1.attn.relative_position_bias_table",
        "features.1.1.mlp.0.bias",
        "features.1.1.mlp.0.weight",
        "features.1.1.mlp.3.bias",
        "features.1.1.mlp.3.weight",
        "features.1.1.norm1.bias",
        "features.1.1.norm1.weight",
        "features.1.1.norm2.bias",
        "features.1.1.norm2.weight",
        "features.2.norm.bias",
        "features.2.norm.weight",
        "features.2.reduction.weight",
        "features.3.0.attn.proj.bias",
        "features.3.0.attn.proj.weight",
        "features.3.0.attn.qkv.bias",
        "features.3.0.attn.qkv.weight",
        "features.3.0.attn.relative_position_bias_table",
        "features.3.0.mlp.0.bias",
        "features.3.0.mlp.0.weight",
        "features.3.0.mlp.3.bias",
        "features.3.0.mlp.3.weight",
        "features.3.0.norm1.bias",
        "features.3.0.norm1.weight",
        "features.3.0.norm2.bias",
        "features.3.0.norm2.weight",
        "features.3.1.attn.proj.bias",
        "features.3.1.attn.proj.weight",
        "features.3.1.attn.qkv.bias",
        "features.3.1.attn.qkv.weight",
        "features.3.1.attn.relative_position_bias_table",
        "features.3.1.mlp.0.bias",
        "features.3.1.mlp.0.weight",
        "features.3.1.mlp.3.bias",
        "features.3.1.mlp.3.weight",
        "features.3.1.norm1.bias",
        "features.3.1.norm1.weight",
        "features.3.1.norm2.bias",
        "features.3.1.norm2.weight",
        "features.4.norm.bias",
        "features.4.norm.weight",
        "features.4.reduction.weight",
        "features.5.0.attn.proj.bias",
        "features.5.0.attn.proj.weight",
        "features.5.0.attn.qkv.bias",
        "features.5.0.attn.qkv.weight",
        "features.5.0.attn.relative_position_bias_table",
        "features.5.0.mlp.0.bias",
        "features.5.0.mlp.0.weight",
        "features.5.0.mlp.3.bias",
        "features.5.0.mlp.3.weight",
        "features.5.0.norm1.bias",
        "features.5.0.norm1.weight",
        "features.5.0.norm2.bias",
        "features.5.0.norm2.weight",
        "features.5.1.attn.proj.bias",
        "features.5.1.attn.proj.weight",
        "features.5.1.attn.qkv.bias",
        "features.5.1.attn.qkv.weight",
        "features.5.1.attn.relative_position_bias_table",
        "features.5.1.mlp.0.bias",
        "features.5.1.mlp.0.weight",
        "features.5.1.mlp.3.bias",
        "features.5.1.mlp.3.weight",
        "features.5.1.norm1.bias",
        "features.5.1.norm1.weight",
        "features.5.1.norm2.bias",
        "features.5.1.norm2.weight",
        "features.5.2.attn.proj.bias",
        "features.5.2.attn.proj.weight",
        "features.5.2.attn.qkv.bias",
        "features.5.2.attn.qkv.weight",
        "features.5.2.attn.relative_position_bias_table",
        "features.5.2.mlp.0.bias",
        "features.5.2.mlp.0.weight",
        "features.5.2.mlp.3.bias",
        "features.5.2.mlp.3.weight",
        "features.5.2.norm1.bias",
        "features.5.2.norm1.weight",
        "features.5.2.norm2.bias",
        "features.5.2.norm2.weight",
        "features.5.3.attn.proj.bias",
        "features.5.3.attn.proj.weight",
        "features.5.3.attn.qkv.bias",
        "features.5.3.attn.qkv.weight",
        "features.5.3.attn.relative_position_bias_table",
        "features.5.3.mlp.0.bias",
        "features.5.3.mlp.0.weight",
        "features.5.3.mlp.3.bias",
        "features.5.3.mlp.3.weight",
        "features.5.3.norm1.bias",
        "features.5.3.norm1.weight",
        "features.5.3.norm2.bias",
        "features.5.3.norm2.weight",
        "features.5.4.attn.proj.bias",
        "features.5.4.attn.proj.weight",
        "features.5.4.attn.qkv.bias",
        "features.5.4.attn.qkv.weight",
        "features.5.4.attn.relative_position_bias_table",
        "features.5.4.mlp.0.bias",
        "features.5.4.mlp.0.weight",
        "features.5.4.mlp.3.bias",
        "features.5.4.mlp.3.weight",
        "features.5.4.norm1.bias",
        "features.5.4.norm1.weight",
        "features.5.4.norm2.bias",
        "features.5.4.norm2.weight",
        "features.5.5.attn.proj.bias",
        "features.5.5.attn.proj.weight",
        "features.5.5.attn.qkv.bias",
        "features.5.5.attn.qkv.weight",
        "features.5.5.attn.relative_position_bias_table",
        "features.5.5.mlp.0.bias",
        "features.5.5.mlp.0.weight",
        "features.5.5.mlp.3.bias",
        "features.5.5.mlp.3.weight",
        "features.5.5.norm1.bias",
        "features.5.5.norm1.weight",
        "features.5.5.norm2.bias",
        "features.5.5.norm2.weight",
        "features.6.norm.bias",
        "features.6.norm.weight",
        "features.6.reduction.weight",
        "features.7.0.attn.proj.bias",
        "features.7.0.attn.proj.weight",
        "features.7.0.attn.qkv.bias",
        "features.7.0.attn.qkv.weight",
        "features.7.0.attn.relative_position_bias_table",
        "features.7.0.mlp.0.bias",
        "features.7.0.mlp.0.weight",
        "features.7.0.mlp.3.bias",
        "features.7.0.mlp.3.weight",
        "features.7.0.norm1.bias",
        "features.7.0.norm1.weight",
        "features.7.0.norm2.bias",
        "features.7.0.norm2.weight",
        "features.7.1.attn.proj.bias",
        "features.7.1.attn.proj.weight",
        "features.7.1.attn.qkv.bias",
        "features.7.1.attn.qkv.weight",
        "features.7.1.attn.relative_position_bias_table",
        "features.7.1.mlp.0.bias",
        "features.7.1.mlp.0.weight",
        "features.7.1.mlp.3.bias",
        "features.7.1.mlp.3.weight",
        "features.7.1.norm1.bias",
        "features.7.1.norm1.weight",
        "features.7.1.norm2.bias",
        "features.7.1.norm2.weight",
        "head.bias",
        "head.weight",
        "norm.bias",
        "norm.weight",
    ];
    let expected: BTreeSet<String> = expected_raw.iter().map(|s| (*s).to_string()).collect();

    let only_in_actual: Vec<&String> = actual.difference(&expected).collect();
    let only_in_expected: Vec<&String> = expected.difference(&actual).collect();

    if !only_in_actual.is_empty() || !only_in_expected.is_empty() {
        eprintln!(
            "ferrotorch named_parameters has {} keys; torchvision swin_t has {} keys",
            actual.len(),
            expected.len()
        );
        eprintln!("Only in ferrotorch (extras): {only_in_actual:?}");
        eprintln!("Only in torchvision (missing on ferrotorch side): {only_in_expected:?}");
    }

    assert!(
        only_in_actual.is_empty(),
        "ferrotorch swin_tiny exposes parameters not present in torchvision swin_t"
    );
    assert!(
        only_in_expected.is_empty(),
        "ferrotorch swin_tiny is missing parameters present in torchvision swin_t"
    );
}
