//! Red-then-green regression tests for audit finding CORE-067 (crosslink
//! #1761, CLASS-S): valid CUDA nested attention OUTSIDE the flash-kernel
//! regime (head dim > 128, unsupported dtype, backend declined) errored
//! with a GPU-data-access failure because the "composite fallback" called
//! the CPU-only `data()` on the CUDA q/k/v. The design claims the
//! composite path is a fallback when the backend declines; pre-fix it
//! never was, on CUDA.
//!
//! Post-fix contract: when the flash kernel declines a CUDA component,
//! attention composes from the device-aware dispatched primitives
//! (`mm_bt` → broadcast `mul` → `softmax` → `matmul`) and the result
//! stays on CUDA (R-ORACLE-3 device asserts).
//!
//! All expectations come from a LIVE torch session (torch 2.11.0+cu130,
//! R-ORACLE-1(b)). Inputs are generated by a deterministic modular
//! formula, exactly representable in f32/f64:
//!
//! ```python
//! >>> def mk(seq_q, seq_k, dk, dv):
//! ...     q = ((torch.arange(seq_q*dk, dtype=torch.float64).reshape(seq_q,dk) % 7) * 0.25 - 0.5)
//! ...     k = ((torch.arange(seq_k*dk, dtype=torch.float64).reshape(seq_k,dk) % 5) * 0.5 - 1.0)
//! ...     v = ((torch.arange(seq_k*dv, dtype=torch.float64).reshape(seq_k,dv) % 3) * 1.0 - 1.0)
//! ...     return q,k,v
//! >>> q,k,v = mk(2,3,128,4)
//! >>> torch.nn.functional.scaled_dot_product_attention(q,k,v).flatten().tolist()
//! [0.01094586247207674, 0.003729990314408904, -0.014675852786485644, 0.01094586247207674,
//!  0.007631625913374573, -0.039961863275488174, 0.0323302373621136, 0.007631625913374573]
//! >>> q,k,v = mk(2,3,129,4)
//! >>> torch.nn.functional.scaled_dot_product_attention(q,k,v).flatten().tolist()
//! [0.01440147512904616, 0.011224882530688707, -0.025626357659734866, 0.01440147512904616,
//!  -0.014401475129046215, 0.025626357659734866, -0.011224882530688651, -0.014401475129046215]
//! ```

#![cfg(feature = "gpu")]

use std::sync::Once;

use ferrotorch_core::Device;
use ferrotorch_core::nested::{NestedTensor, nested_scaled_dot_product_attention};
use ferrotorch_core::storage::TensorStorage;
use ferrotorch_core::tensor::Tensor;

static GPU_INIT: Once = Once::new();

fn ensure_cuda_backend() {
    GPU_INIT.call_once(|| {
        ferrotorch_gpu::init_cuda_backend()
            .expect("CUDA backend must initialize for the CORE-067 regression suite");
    });
}

/// Deterministic modular inputs matching the torch oracle snippet above.
fn mk_qkv_f32(seq_q: usize, seq_k: usize, dk: usize, dv: usize) -> (Vec<f32>, Vec<f32>, Vec<f32>) {
    let q = (0..seq_q * dk)
        .map(|i| (i % 7) as f32 * 0.25 - 0.5)
        .collect();
    let k = (0..seq_k * dk)
        .map(|i| (i % 5) as f32 * 0.5 - 1.0)
        .collect();
    let v = (0..seq_k * dv)
        .map(|i| (i % 3) as f32 * 1.0 - 1.0)
        .collect();
    (q, k, v)
}

fn cuda_f32(data: Vec<f32>, shape: Vec<usize>) -> Tensor<f32> {
    Tensor::from_storage(TensorStorage::cpu(data), shape, false)
        .unwrap()
        .to(Device::Cuda(0))
        .expect("upload to cuda:0")
}

fn cuda_f64(data: Vec<f64>, shape: Vec<usize>) -> Tensor<f64> {
    Tensor::from_storage(TensorStorage::cpu(data), shape, false)
        .unwrap()
        .to(Device::Cuda(0))
        .expect("upload to cuda:0")
}

fn run_nested_attention_f32(
    q: Tensor<f32>,
    k: Tensor<f32>,
    v: Tensor<f32>,
) -> ferrotorch_core::FerrotorchResult<NestedTensor<f32>> {
    let qn = NestedTensor::new(vec![q], 0)?;
    let kn = NestedTensor::new(vec![k], 0)?;
    let vn = NestedTensor::new(vec![v], 0)?;
    nested_scaled_dot_product_attention(&qn, &kn, &vn)
}

const WANT_D128: [f64; 8] = [
    0.01094586247207674,
    0.003729990314408904,
    -0.014675852786485644,
    0.01094586247207674,
    0.007631625913374573,
    -0.039961863275488174,
    0.0323302373621136,
    0.007631625913374573,
];

const WANT_D129: [f64; 8] = [
    0.01440147512904616,
    0.011224882530688707,
    -0.025626357659734866,
    0.01440147512904616,
    -0.014401475129046215,
    0.025626357659734866,
    -0.011224882530688651,
    -0.014401475129046215,
];

/// Head size 129 (one past the flash-kernel cap): the flash helper
/// declines, and the device-aware composite must take over — NOT a
/// GPU-data-access error.
#[test]
fn core067_cuda_attention_d129_composite_fallback_f32() {
    ensure_cuda_backend();
    let (q, k, v) = mk_qkv_f32(2, 3, 129, 4);
    let out = run_nested_attention_f32(
        cuda_f32(q, vec![2, 129]),
        cuda_f32(k, vec![3, 129]),
        cuda_f32(v, vec![3, 4]),
    )
    .expect("valid CUDA attention at d_k=129 must fall back to the composite, not error");

    let out0 = &out.tensors()[0];
    assert_eq!(
        out0.device(),
        Device::Cuda(0),
        "R-ORACLE-3: composite fallback must stay on CUDA, got {:?}",
        out0.device()
    );
    assert_eq!(out0.shape(), &[2, 4]);
    let got = out0.data_vec().unwrap();
    for (i, (g, w)) in got.iter().zip(WANT_D129.iter()).enumerate() {
        // Tolerance: f32 eps (1.2e-7) over 129-term dot products of
        // magnitude O(30), a 3-way softmax, and 3-term weighted sums —
        // absolute error budget ~3e-5; assert at 1e-4.
        assert!(
            (*g as f64 - w).abs() < 1e-4,
            "d129 out[{i}]: got {g}, torch oracle {w}"
        );
    }
}

/// Head size 128 (the flash boundary): same data family, flash regime —
/// must agree with the same torch oracle, on-device.
#[test]
fn core067_cuda_attention_d128_flash_boundary_f32() {
    ensure_cuda_backend();
    let (q, k, v) = mk_qkv_f32(2, 3, 128, 4);
    let out = run_nested_attention_f32(
        cuda_f32(q, vec![2, 128]),
        cuda_f32(k, vec![3, 128]),
        cuda_f32(v, vec![3, 4]),
    )
    .expect("d_k=128 is inside the flash regime");

    let out0 = &out.tensors()[0];
    assert_eq!(out0.device(), Device::Cuda(0), "R-ORACLE-3");
    let got = out0.data_vec().unwrap();
    for (i, (g, w)) in got.iter().zip(WANT_D128.iter()).enumerate() {
        // Same budget as d129 (128-term f32 dots).
        assert!(
            (*g as f64 - w).abs() < 1e-4,
            "d128 out[{i}]: got {g}, torch oracle {w}"
        );
    }
}

/// f64 at d_k=129: also outside the kernel cap; the composite fallback
/// must reproduce the oracle at f64 precision.
#[test]
fn core067_cuda_attention_d129_composite_fallback_f64() {
    ensure_cuda_backend();
    let q: Vec<f64> = (0..2 * 129).map(|i| (i % 7) as f64 * 0.25 - 0.5).collect();
    let k: Vec<f64> = (0..3 * 129).map(|i| (i % 5) as f64 * 0.5 - 1.0).collect();
    let v: Vec<f64> = (0..3 * 4).map(|i| (i % 3) as f64 - 1.0).collect();
    let qn = NestedTensor::new(vec![cuda_f64(q, vec![2, 129])], 0).unwrap();
    let kn = NestedTensor::new(vec![cuda_f64(k, vec![3, 129])], 0).unwrap();
    let vn = NestedTensor::new(vec![cuda_f64(v, vec![3, 4])], 0).unwrap();

    let out = nested_scaled_dot_product_attention(&qn, &kn, &vn)
        .expect("valid CUDA f64 attention at d_k=129 must fall back to the composite");
    let out0 = &out.tensors()[0];
    assert_eq!(out0.device(), Device::Cuda(0), "R-ORACLE-3");
    let got = out0.data_vec().unwrap();
    for (i, (g, w)) in got.iter().zip(WANT_D129.iter()).enumerate() {
        // f64 eps (2.2e-16) over 129-term dots of magnitude O(30) plus
        // softmax — budget ~1e-12; assert at 1e-9.
        assert!(
            (g - w).abs() < 1e-9,
            "d129 f64 out[{i}]: got {g}, torch oracle {w}"
        );
    }
}

/// d_v > 128 with d_k <= 128 also leaves the flash regime — the composite
/// must handle it (the value head dim drives the kernel cap too).
///
/// Oracle (live torch session; v uses the mod-5 pattern because the mod-3
/// pattern aliases at dv=129 — 129 ≡ 0 (mod 3) makes every v column
/// constant, which any normalized weighting would reproduce):
///
/// ```python
/// >>> q = ((torch.arange(2*4, dtype=torch.float64).reshape(2,4) % 7) * 0.25 - 0.5)
/// >>> k = ((torch.arange(3*4, dtype=torch.float64).reshape(3,4) % 5) * 0.5 - 1.0)
/// >>> v = ((torch.arange(3*129, dtype=torch.float64).reshape(3,129) % 5) * 0.5 - 1.0)
/// >>> out = torch.nn.functional.scaled_dot_product_attention(q,k,v)
/// >>> out[0,0].item(), out[0,1].item(), out[1,64].item(), out[1,128].item()
/// (-0.06734431325455716, -0.2861998147860336, 0.3821519573198031, -0.11784804268019693)
/// ```
#[test]
fn core067_cuda_attention_dv_129_composite_fallback_f32() {
    ensure_cuda_backend();
    let (q, k, _) = mk_qkv_f32(2, 3, 4, 4);
    let v: Vec<f32> = (0..3 * 129).map(|i| (i % 5) as f32 * 0.5 - 1.0).collect();
    let out = run_nested_attention_f32(
        cuda_f32(q, vec![2, 4]),
        cuda_f32(k, vec![3, 4]),
        cuda_f32(v, vec![3, 129]),
    )
    .expect("valid CUDA attention at d_v=129 must fall back to the composite");
    let out0 = &out.tensors()[0];
    assert_eq!(out0.device(), Device::Cuda(0), "R-ORACLE-3");
    assert_eq!(out0.shape(), &[2, 129]);
    let got = out0.data_vec().unwrap();
    // Tolerance: f32 eps over 4-term dots + 3-way softmax — 1e-5 budget.
    let spots: [(usize, f64); 4] = [
        (0, -0.06734431325455716),
        (1, -0.2861998147860336),
        (129 + 64, 0.3821519573198031),
        (129 + 128, -0.11784804268019693),
    ];
    for (idx, w) in spots {
        assert!(
            (got[idx] as f64 - w).abs() < 1e-5,
            "dv129 out[flat {idx}]: got {}, torch oracle {w}",
            got[idx]
        );
    }
}
