//! Divergences pinned in commit `895232ac4` — the S1 batch that
//! shipped 9 new reduction ops (logsumexp, argmax/argmin, std/var,
//! any/all/count_nonzero, amin_dim/amax_dim, prod_dim) and 13 runner
//! arms. Generated by acto-critic audit.
//!
//! Upstream pin: PyTorch 2.11.0+cu130 / `/home/doll/pytorch` tree.
//! Source files this audit opened:
//!
//!   - aten/src/ATen/native/ReduceOps.cpp:1512-1559 (logsumexp_out_impl)
//!   - aten/src/ATen/native/ReduceOps.cpp:1775-1823 (argmax/argmin impl)
//!   - aten/src/ATen/native/ReduceOps.cpp:2085-2108 (var/std)
//!   - aten/src/ATen/native/ReduceOps.cpp:1758-1772 (amin/amax_out)
//!   - aten/src/ATen/native/ReduceOps.cpp:1681 / :1667 (any/all)
//!   - tools/autograd/derivatives.yaml:1205-1211 (scale_grad_by_count)
//!
//! Each test is the smallest failing case that pins a specific
//! divergence. The expected values were captured by live-calling
//! `python3 -c "import torch; ..."` against /home/doll/pytorch's
//! pinned 2.11.0+cu130 build — typed bits traceable to torch op
//! responses, per R-CHAR-3.

use ferrotorch_core::Tensor;
use ferrotorch_core::grad_fns::reduction::{
    amax_dim, amin_dim, argmax, argmax_dim, argmin, argmin_dim, std as red_std,
    std_with_correction, var as red_var, var_with_correction,
};
use ferrotorch_core::storage::TensorStorage;

fn leaf(data: &[f64], shape: &[usize], requires_grad: bool) -> Tensor<f64> {
    Tensor::from_storage(
        TensorStorage::cpu(data.to_vec()),
        shape.to_vec(),
        requires_grad,
    )
    .expect("leaf construction")
}

// ============================================================================
// DIVERGENCE 1: argmax with NaN — upstream returns NaN's index, ferrotorch
// skips NaN and returns the first non-NaN winner.
//
// Upstream: aten/src/ATen/native/SharedReduceOps.h::ArgMaxOps / `>=` semantics
// where NaN comparison returns false but the NaN element is initialized as
// the running max. Live torch:
//   torch.argmax(torch.tensor([1.0, nan, 3.0])).item() == 1
// ferrotorch (reduction.rs:1428-1453 `argmax_argmin_full`):
//   `best_val = 1.0`; `take = NaN > 1.0 -> false`; `take = 3.0 > 1.0 -> true`
//   so returns 2.
// ============================================================================

#[test]
fn divergence_argmax_full_nan_propagation() {
    // From live oracle:
    //   torch.argmax(torch.tensor([1.0, float('nan'), 3.0])).item() == 1
    let x = leaf(&[1.0, f64::NAN, 3.0], &[3], false);
    let result = argmax(&x).expect("argmax forward");
    let r = result.data().expect("argmax data");
    assert_eq!(
        r,
        &[1i64],
        "torch.argmax([1, nan, 3]) is 1 (NaN propagates as the running max), \
         ferrotorch returned {r:?}"
    );
}

#[test]
fn divergence_argmin_full_nan_propagation() {
    // From live oracle:
    //   torch.argmin(torch.tensor([1.0, float('nan'), 3.0])).item() == 1
    let x = leaf(&[1.0, f64::NAN, 3.0], &[3], false);
    let result = argmin(&x).expect("argmin forward");
    let r = result.data().expect("argmin data");
    assert_eq!(
        r,
        &[1i64],
        "torch.argmin([1, nan, 3]) is 1 (NaN propagates), got {r:?}"
    );
}

#[test]
fn divergence_argmax_dim_nan_propagation_per_slice() {
    // From live oracle:
    //   torch.argmax(torch.tensor([[1.0, nan, 3.0], [4.0, 5.0, 6.0]]), dim=1) == [1, 2]
    let x = leaf(&[1.0, f64::NAN, 3.0, 4.0, 5.0, 6.0], &[2, 3], false);
    let result = argmax_dim(&x, 1, false).expect("argmax_dim");
    let r = result.data().expect("data");
    assert_eq!(
        r,
        &[1i64, 2],
        "torch.argmax([[1,nan,3],[4,5,6]], dim=1) == [1, 2], got {r:?}"
    );
}

#[test]
fn divergence_argmin_dim_nan_propagation_per_slice() {
    // From live oracle:
    //   torch.argmin(torch.tensor([[1.0, nan, 3.0], [4.0, 5.0, 6.0]]), dim=1) == [1, 0]
    let x = leaf(&[1.0, f64::NAN, 3.0, 4.0, 5.0, 6.0], &[2, 3], false);
    let result = argmin_dim(&x, 1, false).expect("argmin_dim");
    let r = result.data().expect("data");
    assert_eq!(
        r,
        &[1i64, 0],
        "torch.argmin([[1,nan,3],[4,5,6]], dim=1) == [1, 0], got {r:?}"
    );
}

// ============================================================================
// DIVERGENCE 2: amin_dim / amax_dim — NaN propagation per-slice.
//
// Upstream: `b < a` / `b > a` style accumulators see NaN in input data and
// the comparison returns false BUT the running min/max is initialized to
// data[0]. When data[0] is NaN, NaN sticks. When NaN is in the middle, the
// running comparator was NaN before and NaN remains. This is the documented
// "NaN poisons" behavior in SharedReduceOps.h. Live torch:
//   torch.amin(torch.tensor([[1.0, nan, 3.0], [4.0, 5.0, 6.0]]), dim=1)
//      == [nan, 4.0]
//   torch.amax(...) == [nan, 6.0]
// ferrotorch (reduction.rs `amin_amax_dim_forward`): `best = in_data[base]`,
// then `take = v < best` for each v. If best is NaN (data[0]), NaN > NaN is
// false, never replaced; matches upstream IFF NaN is in position 0. But
// when NaN is in position 1 with data[0]=1.0, ferrotorch keeps 1.0 (NaN<1.0
// is false), losing the NaN.
//
// The design doc admits this divergence for the FULL-reduction amin/amax
// (REQ-4) but the new amin_dim / amax_dim ships the SAME bug per-slice.
// ============================================================================

#[test]
fn divergence_amin_dim_nan_propagation_per_slice() {
    // From live oracle:
    //   torch.amin(torch.tensor([[1.0, nan, 3.0], [4.0, 5.0, 6.0]]), dim=1)
    //      == [nan, 4.0]
    let x = leaf(&[1.0, f64::NAN, 3.0, 4.0, 5.0, 6.0], &[2, 3], false);
    let result = amin_dim(&x, 1, false).expect("amin_dim forward");
    let r = result.data().expect("amin_dim data");
    assert_eq!(r.len(), 2);
    assert!(
        r[0].is_nan(),
        "torch.amin([[1,nan,3],[..]], dim=1)[0] is NaN (NaN propagates), \
         ferrotorch got {}",
        r[0]
    );
    assert!((r[1] - 4.0).abs() < 1e-12);
}

#[test]
fn divergence_amax_dim_nan_propagation_per_slice() {
    // From live oracle:
    //   torch.amax(torch.tensor([[1.0, nan, 3.0], [4.0, 5.0, 6.0]]), dim=1)
    //      == [nan, 6.0]
    let x = leaf(&[1.0, f64::NAN, 3.0, 4.0, 5.0, 6.0], &[2, 3], false);
    let result = amax_dim(&x, 1, false).expect("amax_dim forward");
    let r = result.data().expect("amax_dim data");
    assert_eq!(r.len(), 2);
    assert!(
        r[0].is_nan(),
        "torch.amax([[1,nan,3],[..]], dim=1)[0] is NaN (NaN propagates), \
         ferrotorch got {}",
        r[0]
    );
    assert!((r[1] - 6.0).abs() < 1e-12);
}

// ============================================================================
// DIVERGENCE 3: var/std with non-{0,1} correction on full reduction.
//
// The runner cleanly SKIPS samples with correction ∈ {-1, 0.5, 1.3, 2} on
// the full-reduction path. But the public API surface ITSELF is missing —
// `pub fn var(input, unbiased: bool)` only accepts the boolean dichotomy.
// Per S5 / R-DEFER-1, REQ-8 SHIPPED status requires the public API
// surface to be in place. The design doc REQ-8 row claims SHIPPED but
// admits the "non-{0,1} correction full reduction" gap, which the design
// doc grades as a follow-up to #1301. Per R-DEFER-2: SHIPPED requires
// end-to-end coverage; the follow-up should re-classify REQ-8 as
// NOT-STARTED for the full-reduction-with-arbitrary-correction subset.
//
// This test asserts the divergence: torch supports arbitrary correction
// on full reduction, ferrotorch's full-reduction API does not.
//
// From live oracle:
//   torch.var(torch.tensor([1,2,3,4,5]), correction=2) == 3.3333333...
//   torch.std(..., correction=2) == 1.8257418583505538
//   torch.std(..., correction=0.5) == 1.4907119849998598
// ferrotorch: no API to set correction in the full-reduction call.
// ============================================================================

#[test]
fn divergence_var_full_correction_2_no_api() {
    // From live oracle:
    //   torch.var(torch.tensor([1.,2.,3.,4.,5.]), correction=2).item()
    //      == 3.3333333333333335
    //
    // Closed by audit #1346: `var_with_correction(input, correction)` is
    // now in the public API. Asserts upstream value byte-for-byte.
    let x = leaf(&[1.0, 2.0, 3.0, 4.0, 5.0], &[5], false);
    let r = var_with_correction(&x, 2.0).expect("var corr=2");
    let v = r.item().expect("item");
    let upstream_corr2 = 10.0_f64 / 3.0;
    assert!(
        (v - upstream_corr2).abs() < 1e-10,
        "torch.var([1..5], correction=2) == 10/3 = {upstream_corr2}; got {v}"
    );
    // Sanity: the legacy `unbiased=true` (correction=1) path still
    // returns 10/4 = 2.5 — regression guard for the dichotomy API.
    let r1 = red_var(&x, true).expect("var unbiased");
    let v1 = r1.item().expect("item");
    assert!(
        (v1 - 2.5).abs() < 1e-10,
        "ferrotorch's var(x, unbiased=true) should be 10/(n-1)=2.5; got {v1}"
    );
}

#[test]
fn divergence_var_full_correction_2_pinned() {
    // Closed by audit #1346: `var_with_correction` API landed.
    //
    // From live oracle 2026-05-25:
    //   torch.var(torch.tensor([1.,2.,3.,4.,5.]), correction=2) == 3.3333333333333335
    let x = leaf(&[1.0, 2.0, 3.0, 4.0, 5.0], &[5], false);
    let r = var_with_correction(&x, 2.0).expect("var corr=2");
    assert!((r.item().expect("item") - 10.0_f64 / 3.0).abs() < 1e-10);
    // And `std_with_correction`:
    //   torch.std(..., correction=2).item() == sqrt(10/3) == 1.8257418583505538
    //   torch.std(..., correction=0.5).item() == 1.4907119849998598
    let s2 = std_with_correction(&x, 2.0).expect("std corr=2");
    let s2v = s2.item().expect("item");
    let expected_s2 = (10.0_f64 / 3.0).sqrt();
    assert!(
        (s2v - expected_s2).abs() < 1e-10,
        "torch.std([1..5], correction=2) == sqrt(10/3) = {expected_s2}; got {s2v}"
    );
    let s05 = std_with_correction(&x, 0.5).expect("std corr=0.5");
    let s05v = s05.item().expect("item");
    // sum_sq = 10.0, denom = max(0, 5 - 0.5) = 4.5, var = 10/4.5,
    // std = sqrt(10/4.5) = 1.4907119849998598
    let expected_s05 = (10.0_f64 / 4.5).sqrt();
    assert!(
        (s05v - expected_s05).abs() < 1e-10,
        "torch.std([1..5], correction=0.5) == sqrt(10/4.5) = {expected_s05}; got {s05v}"
    );
}

// ============================================================================
// DIVERGENCE 4: var on empty tensor.
//
// Upstream: `torch.var(torch.tensor([]))` returns NaN (a scalar warning is
// printed about correction<=0, but the value comes back as `nan` from the
// `0/0` path). Source: aten/src/ATen/native/ReduceOps.cpp:1858 (the
// `std::max(0.0, self.numel() - correction)` clamp + IEEE-754 0/0=nan).
// ferrotorch (reduction.rs:1680-1683): explicitly returns
// `FerrotorchError::InvalidArgument { message: "var: cannot reduce empty tensor" }`.
//
// This is an API-level divergence: torch returns a NaN scalar Tensor; ferrotorch
// raises an error. A caller `torch_to_ferrotorch_translation_X(x)` that
// uses var(empty) gets an Err in Rust where torch gives a NaN tensor.
// ============================================================================

#[test]
fn divergence_var_empty_returns_nan_not_error() {
    // From live oracle:
    //   torch.var(torch.tensor([], dtype=torch.float64)).item() is nan
    //
    // ferrotorch raises InvalidArgument instead of returning a NaN scalar.
    let x = leaf(&[], &[0], false);
    let result = red_var(&x, true);
    match result {
        Ok(t) => {
            let v = t.item().expect("item");
            assert!(
                v.is_nan(),
                "torch.var(empty) returns NaN scalar; ferrotorch returned {v}"
            );
        }
        Err(e) => panic!(
            "torch.var(empty) returns NaN scalar (no error); ferrotorch \
             raised {e:?}. Should return a tensor holding NaN to match upstream."
        ),
    }
}

#[test]
fn divergence_std_empty_returns_nan_not_error() {
    // From live oracle:
    //   torch.std(torch.tensor([], dtype=torch.float64)).item() is nan
    let x = leaf(&[], &[0], false);
    let result = red_std(&x, true);
    match result {
        Ok(t) => {
            let v = t.item().expect("item");
            assert!(
                v.is_nan(),
                "torch.std(empty) returns NaN scalar; ferrotorch returned {v}"
            );
        }
        Err(e) => panic!(
            "torch.std(empty) returns NaN scalar (no error); ferrotorch \
             raised {e:?}."
        ),
    }
}

// ============================================================================
// DIVERGENCE 5: argmax with NaN as data[0] — the "trivial first element is
// NaN" case happens to MATCH upstream by coincidence (best_idx=0 stays at
// 0 since every comparison is false). Document as observation to prevent
// regression.
// ============================================================================

#[test]
fn observation_argmax_nan_at_zero_happens_to_match_torch() {
    // From live oracle:
    //   torch.argmax(torch.tensor([nan, 1.0, 3.0])).item() == 0
    //
    // ferrotorch: best_val starts as NaN; every later v > NaN is false,
    // so best_idx stays 0. Coincidental match. Document — if this code
    // changes (e.g. someone "fixes" the NaN-skipping to skip the FIRST
    // NaN too), this test should fail.
    let x = leaf(&[f64::NAN, 1.0, 3.0], &[3], false);
    let result = argmax(&x).expect("argmax forward");
    let r = result.data().expect("data");
    assert_eq!(r, &[0i64]);
}
