//! Conformance Phase C6.3 — `ferrotorch-optim` advanced optimizers + utilities.
//!
//! Modules covered (10):
//!   muon, lbfgs, natural_gradient (kfac), ema, swa, grad_accumulator,
//!   grad_scaler, optimizer (ParamGroup/Optimizer trait), foreach_utils,
//!   differentiable.
//!
//! Reference library: `torch == 2.11.0`. Fixtures live in
//! `tests/conformance/fixtures.json`, generated by
//! `scripts/regenerate_optim_advanced_fixtures.py`.
//!
//! ## Layer 2 — fixture-driven tests
//!
//! EMA, SWA, SWALR, GradScaler, GradientAccumulator, differentiable SGD, and
//! foreach_utils are exercised against exact Python-computed reference values.
//!
//! ## Layer 3 — mathematical-property tests
//!
//! Muon (Newton-Schulz orthogonality + quadratic convergence), LBFGS
//! (quadratic + Rosenbrock convergence), and K-FAC (Kronecker factor update
//! arithmetic + convergence) have no PyTorch reference implementation — these
//! are tested via algebraic invariants and convergence bounds documented in
//! the originating papers.
//!
//! ## cascade_skip convention
//!
//! `cascade_skip!(label)` prints a diagnostic and returns early.  It is NOT
//! `#[ignore]` — the test still runs and emits the notice.  Skip targets are
//! features that require a live GPU or a full training loop.

#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_sign_loss,
    clippy::uninlined_format_args,
    clippy::explicit_iter_loop,
    clippy::redundant_else,
    clippy::approx_constant
)]

use std::path::PathBuf;

use ferrotorch_core::grad_fns::arithmetic::{add, pow};
use ferrotorch_core::{FerrotorchResult, Float, Tensor, TensorStorage, no_grad};
use ferrotorch_nn::Parameter;
use ferrotorch_optim::differentiable::{diff_sgd_momentum_step, diff_sgd_step};
use ferrotorch_optim::ema::ExponentialMovingAverage;
use ferrotorch_optim::foreach_utils::{elemwise_max, f64_scalar_on};
use ferrotorch_optim::grad_accumulator::GradientAccumulator;
use ferrotorch_optim::grad_scaler::{GradScaler, GradScalerConfig};
use ferrotorch_optim::lbfgs::{Lbfgs, LbfgsConfig, LineSearchFn};
use ferrotorch_optim::muon::{Muon, MuonConfig};
use ferrotorch_optim::natural_gradient::{Kfac, KfacConfig};
use ferrotorch_optim::optimizer::{Optimizer, OptimizerState, ParamGroup};
use ferrotorch_optim::scheduler::LrScheduler;
use ferrotorch_optim::swa::{AveragedModel, AveragingStrategy, Swalr};
use serde::Deserialize;

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct FixtureFile {
    ema: Vec<EmaFixture>,
    swa: Vec<SwaFixture>,
    swalr: Vec<SwalrFixture>,
    lbfgs: Vec<LbfgsFixture>,
    grad_scaler: Vec<GradScalerFixture>,
    grad_accumulator: Vec<GradAccumFixture>,
    differentiable: Vec<DifferentiableFixture>,
    foreach_utils: Vec<ForeachFixture>,
    optimizer: Vec<OptimizerFixture>,
    muon: Vec<MuonFixture>,
    kfac: Vec<KfacFixture>,
}

fn load_fixtures() -> FixtureFile {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("conformance")
        .join("fixtures_advanced.json");
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "read {} failed: {e}. Run scripts/regenerate_optim_advanced_fixtures.py first.",
            path.display()
        )
    });
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parse {} failed: {e}", path.display()))
}

// ---------------------------------------------------------------------------
// Fixture structs (serde-deserialized)
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct EmaFixture {
    kind: String,
    #[serde(default)]
    decay: f64,
    #[serde(default)]
    initial_shadow: Vec<f64>,
    #[serde(default)]
    update_param: Vec<f64>,
    #[serde(default)]
    expected_after_1: Vec<f64>,
    #[serde(default)]
    update_value: f64,
    #[serde(default)]
    n_steps: usize,
    #[serde(default)]
    expected_after_each: Vec<f64>,
    label: String,
}

#[allow(dead_code, reason = "fixture metadata for diagnostics")]
#[derive(Debug, Deserialize)]
struct SwaFixture {
    kind: String,
    #[serde(default)]
    checkpoints: Vec<f64>,
    #[serde(default)]
    expected_running: Vec<f64>,
    #[serde(default)]
    checkpoint_value: f64,
    #[serde(default)]
    n_updates: usize,
    #[serde(default)]
    expected_mean: f64,
    #[serde(default)]
    first_checkpoint: f64,
    #[serde(default)]
    second_checkpoint: f64,
    #[serde(default)]
    ema_decay: f64,
    #[serde(default)]
    expected_after_second: f64,
    label: String,
}

#[derive(Debug, Deserialize)]
struct SwalrFixture {
    kind: String,
    #[serde(default)]
    initial_lr: f64,
    #[serde(default)]
    swa_lr: f64,
    #[serde(default)]
    anneal_epochs: usize,
    #[serde(default)]
    lr_sequence: Vec<f64>,
    #[serde(default)]
    expected_final_lr: f64,
    #[serde(default)]
    step: usize,
    #[serde(default)]
    expected_lr: f64,
    label: String,
}

#[derive(Debug, Deserialize)]
struct LbfgsFixture {
    kind: String,
    #[serde(default)]
    initial_x: f64,
    #[serde(default)]
    lr: f64,
    #[serde(default)]
    n_steps: usize,
    #[serde(default)]
    convergence_tolerance: f64,
    #[serde(default)]
    initial_params: Vec<f64>,
    label: String,
}

#[derive(Debug, Deserialize)]
struct GradScalerFixture {
    kind: String,
    #[serde(default)]
    expected_init_scale: f64,
    #[serde(default)]
    init_scale: f64,
    #[serde(default)]
    backoff_factor: f64,
    #[serde(default)]
    expected_scale_after_update: f64,
    #[serde(default)]
    growth_factor: f64,
    #[serde(default)]
    growth_interval: usize,
    #[serde(default)]
    n_healthy_steps: usize,
    #[serde(default)]
    expected_scale_after_growth: f64,
    #[serde(default)]
    growth_tracker_after_2_steps: usize,
    label: String,
}

#[allow(dead_code, reason = "fixture metadata for diagnostics")]
#[derive(Debug, Deserialize)]
struct GradAccumFixture {
    kind: String,
    #[serde(default)]
    accumulation_steps: usize,
    #[serde(default)]
    n_calls: usize,
    #[serde(default)]
    expected_results: Vec<bool>,
    #[serde(default)]
    loss: f64,
    #[serde(default)]
    expected_scaled: f64,
    #[serde(default)]
    batch_losses: Vec<f64>,
    #[serde(default)]
    n_accumulate: usize,
    #[serde(default)]
    expected_mean_loss: f64,
    label: String,
}

#[allow(dead_code, reason = "fixture metadata for diagnostics")]
#[derive(Debug, Deserialize)]
struct DifferentiableFixture {
    kind: String,
    #[serde(default)]
    param: Vec<f64>,
    #[serde(default)]
    grad: Vec<f64>,
    #[serde(default)]
    lr: f64,
    #[serde(default)]
    expected: Vec<f64>,
    #[serde(default)]
    expected_params: Vec<Vec<f64>>,
    #[serde(default)]
    params: Vec<Vec<f64>>,
    #[serde(default)]
    grads: Vec<Vec<f64>>,
    #[serde(default)]
    v_prev: Vec<f64>,
    #[serde(default)]
    momentum: f64,
    #[serde(default)]
    expected_v_new: Vec<f64>,
    #[serde(default)]
    expected_p_new: Vec<f64>,
    label: String,
}

#[derive(Debug, Deserialize)]
struct ForeachFixture {
    kind: String,
    #[serde(default)]
    a: Vec<f64>,
    #[serde(default)]
    b: Vec<f64>,
    #[serde(default)]
    expected: Vec<f64>,
    #[serde(default)]
    expected_scalar: f64,
    #[serde(default)]
    value: f64,
    label: String,
}

#[derive(Debug, Deserialize)]
struct OptimizerFixture {
    kind: String,
    #[serde(default)]
    lr: f64,
    #[serde(default)]
    weight_decay: f64,
    #[serde(default)]
    expected_weight_decay: f64,
    label: String,
}

#[allow(dead_code, reason = "fixture metadata for diagnostics")]
#[derive(Debug, Deserialize)]
struct MuonFixture {
    kind: String,
    #[serde(default)]
    tolerance: f64,
    #[serde(default)]
    input: Vec<Vec<f64>>,
    #[serde(default)]
    ns_steps: usize,
    #[serde(default)]
    initial_param: Vec<f64>,
    #[serde(default)]
    lr: f64,
    #[serde(default)]
    momentum: f64,
    #[serde(default)]
    n_steps: usize,
    #[serde(default)]
    convergence_tolerance_norm_sq: f64,
    label: String,
}

#[derive(Debug, Deserialize)]
struct KfacFixture {
    kind: String,
    #[serde(default)]
    activation: Vec<Vec<f64>>,
    #[serde(default)]
    expected_a_factor_diag: Vec<f64>,
    #[serde(default)]
    expected_a_factor_offdiag: Vec<f64>,
    label: String,
}

// ---------------------------------------------------------------------------
// Tolerance constants
// ---------------------------------------------------------------------------

mod tolerance {
    /// Absolute tolerance for optimizer arithmetic (f64, CPU, few-step).
    pub const F64_OPTIMIZER_CPU: f64 = 1e-10;
    /// Relaxed tolerance for cumulative EMA / SWA arithmetic (f32 accumulation
    /// over many steps can drift slightly).
    pub const F32_EMA_CPU: f32 = 1e-5;
    /// Convergence tolerance margin for property-based tests.
    pub const CONVERGENCE_MARGIN: f64 = 1.1; // allow 10% over the fixture tolerance
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Build a scalar (0-D) `Parameter<f64>` with the given value.
fn scalar_param(val: f64) -> Parameter<f64> {
    let t = Tensor::from_storage(TensorStorage::cpu(vec![val]), vec![], true).unwrap();
    Parameter::new(t)
}

/// Build a 1-D `Parameter<f64>` from a slice.
fn param_from(data: &[f64], shape: &[usize]) -> Parameter<f64> {
    Parameter::from_slice(data, shape).unwrap()
}

/// Build a leaf `Tensor<f64>` (no grad) from a slice.
fn t64(data: &[f64], shape: &[usize]) -> Tensor<f64> {
    Tensor::from_storage(TensorStorage::cpu(data.to_vec()), shape.to_vec(), false).unwrap()
}

/// Build a leaf `Tensor<f32>` (no grad) from a slice.
fn t32(data: &[f32], shape: &[usize]) -> Tensor<f32> {
    Tensor::from_storage(TensorStorage::cpu(data.to_vec()), shape.to_vec(), false).unwrap()
}

/// Minimal mock optimizer for GradScaler and SWALR tests (no real params).
struct MockOptimizer<T: Float> {
    lr: f64,
    param_groups: Vec<ParamGroup<T>>,
    step_called: bool,
}

impl<T: Float> MockOptimizer<T> {
    fn new(lr: f64) -> Self {
        Self {
            lr,
            param_groups: Vec::new(),
            step_called: false,
        }
    }
    fn with_params(lr: f64, params: Vec<Parameter<T>>) -> Self {
        let group = ParamGroup::new(params, lr);
        Self {
            lr,
            param_groups: vec![group],
            step_called: false,
        }
    }
}

impl<T: Float> Optimizer<T> for MockOptimizer<T> {
    fn step(&mut self) -> FerrotorchResult<()> {
        self.step_called = true;
        Ok(())
    }
    fn zero_grad(&mut self) -> FerrotorchResult<()> {
        for g in &self.param_groups {
            for p in g.params() {
                p.set_grad(None)?;
            }
        }
        Ok(())
    }
    fn lr(&self) -> f64 {
        self.lr
    }
    fn set_lr(&mut self, lr: f64) {
        self.lr = lr;
    }
    fn param_groups(&self) -> &[ParamGroup<T>] {
        &self.param_groups
    }
    fn param_groups_mut(&mut self) -> &mut [ParamGroup<T>] {
        &mut self.param_groups
    }
    fn add_param_group(&mut self, g: ParamGroup<T>) {
        self.param_groups.push(g);
    }
    fn state_dict(&self) -> FerrotorchResult<OptimizerState> {
        Ok(OptimizerState::new())
    }
    fn load_state_dict(&mut self, _: &OptimizerState) -> FerrotorchResult<()> {
        Ok(())
    }
}

// ===========================================================================
// Layer 2 — EMA fixture-driven tests
// ===========================================================================

#[test]
fn ema_single_step_matches_reference() {
    let fx = load_fixtures();
    let f = fx.ema.iter().find(|f| f.kind == "ema_single_step").unwrap();

    let shadow: Vec<f32> = f.initial_shadow.iter().map(|&v| v as f32).collect();
    let param_data: Vec<f32> = f.update_param.iter().map(|&v| v as f32).collect();

    let p = Parameter::from_slice(&shadow, &[shadow.len()]).unwrap();
    let mut ema = ExponentialMovingAverage::new(std::slice::from_ref(&p), f.decay);

    // Simulate optimizer step — update param in-place.
    no_grad(|| unsafe { p.tensor().update_data(&param_data) }).unwrap();
    ema.update(std::slice::from_ref(&p)).unwrap();

    let got = ema.shadow_params()[0].clone();
    for (i, (&g, &exp)) in got.iter().zip(f.expected_after_1.iter()).enumerate() {
        let exp_f32 = exp as f32;
        assert!(
            (g - exp_f32).abs() < tolerance::F32_EMA_CPU,
            "[{}] element {i}: expected {exp_f32}, got {g} (label: {})",
            f.kind,
            f.label
        );
    }
}

#[test]
fn ema_multi_step_matches_reference() {
    let fx = load_fixtures();
    let f = fx.ema.iter().find(|f| f.kind == "ema_multi_step").unwrap();

    let p = Parameter::from_slice(&[f.initial_shadow[0] as f32], &[1]).unwrap();
    let mut ema = ExponentialMovingAverage::new(std::slice::from_ref(&p), f.decay);

    for (step_idx, &exp) in f.expected_after_each.iter().enumerate() {
        no_grad(|| unsafe { p.tensor().update_data(&[f.update_value as f32]) }).unwrap();
        ema.update(std::slice::from_ref(&p)).unwrap();

        let got = ema.shadow_params()[0][0];
        let exp_f32 = exp as f32;
        assert!(
            (got - exp_f32).abs() < tolerance::F32_EMA_CPU,
            "[{}] step {step_idx}: expected {exp_f32}, got {got} (label: {})",
            f.kind,
            f.label
        );
    }
}

#[test]
fn ema_decay_zero_full_replace() {
    let fx = load_fixtures();
    let f = fx.ema.iter().find(|f| f.kind == "ema_decay_zero").unwrap();

    let p = Parameter::from_slice(&[f.initial_shadow[0] as f32], &[1]).unwrap();
    let mut ema = ExponentialMovingAverage::new(std::slice::from_ref(&p), f.decay);

    no_grad(|| unsafe { p.tensor().update_data(&[f.update_param[0] as f32]) }).unwrap();
    ema.update(std::slice::from_ref(&p)).unwrap();

    let got = ema.shadow_params()[0][0];
    let exp = f.expected_after_1[0] as f32;
    assert!(
        (got - exp).abs() < tolerance::F32_EMA_CPU,
        "[{}] expected {exp}, got {got} (label: {})",
        f.kind,
        f.label
    );
}

#[test]
fn ema_decay_one_freezes_shadow() {
    let fx = load_fixtures();
    let f = fx.ema.iter().find(|f| f.kind == "ema_decay_one").unwrap();

    let p = Parameter::from_slice(&[f.initial_shadow[0] as f32], &[1]).unwrap();
    let mut ema = ExponentialMovingAverage::new(std::slice::from_ref(&p), f.decay);

    no_grad(|| unsafe { p.tensor().update_data(&[f.update_param[0] as f32]) }).unwrap();
    ema.update(std::slice::from_ref(&p)).unwrap();

    let got = ema.shadow_params()[0][0];
    let exp = f.expected_after_1[0] as f32;
    assert!(
        (got - exp).abs() < tolerance::F32_EMA_CPU,
        "[{}] expected {exp}, got {got} (label: {})",
        f.kind,
        f.label
    );
}

#[test]
fn ema_apply_and_restore_roundtrip() {
    // Property test: apply_shadow swaps in EMA weights; restore swaps them back.
    let p = Parameter::from_slice(&[10.0f32, 20.0], &[2]).unwrap();
    let mut ema = ExponentialMovingAverage::new(std::slice::from_ref(&p), 0.5);

    no_grad(|| unsafe { p.tensor().update_data(&[0.0f32, 0.0]) }).unwrap();
    ema.update(std::slice::from_ref(&p)).unwrap();
    // shadow = 0.5*[10,20] + 0.5*[0,0] = [5, 10]

    ema.apply_shadow(std::slice::from_ref(&p)).unwrap();
    let after_apply = p.data().unwrap().to_vec();
    assert!((after_apply[0] - 5.0f32).abs() < tolerance::F32_EMA_CPU);
    assert!((after_apply[1] - 10.0f32).abs() < tolerance::F32_EMA_CPU);

    ema.restore(std::slice::from_ref(&p)).unwrap();
    let after_restore = p.data().unwrap().to_vec();
    assert!((after_restore[0] - 0.0f32).abs() < tolerance::F32_EMA_CPU);
    assert!((after_restore[1] - 0.0f32).abs() < tolerance::F32_EMA_CPU);
}

// ===========================================================================
// Layer 2 — SWA fixture-driven tests
// ===========================================================================

#[test]
fn swa_running_mean_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .swa
        .iter()
        .find(|f| f.kind == "swa_running_mean")
        .unwrap();

    let p = Parameter::from_slice(&[0.0f32], &[1]).unwrap();
    let mut avg = AveragedModel::new(std::slice::from_ref(&p), AveragingStrategy::Swa);

    for (step_idx, (&checkpoint, &exp)) in f
        .checkpoints
        .iter()
        .zip(f.expected_running.iter())
        .enumerate()
    {
        no_grad(|| unsafe { p.tensor().update_data(&[checkpoint as f32]) }).unwrap();
        avg.update_parameters(std::slice::from_ref(&p)).unwrap();

        let got = avg.averaged_params()[0][0];
        let exp_f32 = exp as f32;
        assert!(
            (got - exp_f32).abs() < 1e-5f32,
            "[swa_running_mean] step {step_idx}: expected {exp_f32}, got {got} (label: {})",
            f.label
        );
    }
}

#[test]
fn swa_identical_checkpoints_converge_to_value() {
    let fx = load_fixtures();
    let f = fx
        .swa
        .iter()
        .find(|f| f.kind == "swa_identical_checkpoints")
        .unwrap();

    let val = f.checkpoint_value as f32;
    let p = Parameter::from_slice(&[val], &[1]).unwrap();
    let mut avg = AveragedModel::new(std::slice::from_ref(&p), AveragingStrategy::Swa);

    for _ in 0..f.n_updates {
        avg.update_parameters(std::slice::from_ref(&p)).unwrap();
    }

    let got = avg.averaged_params()[0][0];
    assert!(
        (got - val).abs() < 1e-5f32,
        "[swa_identical_checkpoints] expected {val}, got {got} (label: {})",
        f.label
    );
}

#[test]
fn swa_ema_strategy_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .swa
        .iter()
        .find(|f| f.kind == "swa_ema_two_steps")
        .unwrap();

    let p = Parameter::from_slice(&[f.first_checkpoint as f32], &[1]).unwrap();
    let mut avg = AveragedModel::new(
        std::slice::from_ref(&p),
        AveragingStrategy::Ema(f.ema_decay),
    );

    // First update: copies the first checkpoint.
    avg.update_parameters(std::slice::from_ref(&p)).unwrap();

    // Second update: blends with second_checkpoint.
    no_grad(|| unsafe { p.tensor().update_data(&[f.second_checkpoint as f32]) }).unwrap();
    avg.update_parameters(std::slice::from_ref(&p)).unwrap();

    let got = avg.averaged_params()[0][0];
    let exp = f.expected_after_second as f32;
    assert!(
        (got - exp).abs() < 1e-5f32,
        "[swa_ema_two_steps] expected {exp}, got {got} (label: {})",
        f.label
    );
}

#[test]
fn swa_apply_to_sets_param_to_average() {
    // Property test: apply_to copies averaged weights into the parameter.
    let p = Parameter::from_slice(&[1.0f32, 2.0], &[2]).unwrap();
    let mut avg = AveragedModel::new(std::slice::from_ref(&p), AveragingStrategy::Swa);

    // First update: avg = [1, 2].
    avg.update_parameters(std::slice::from_ref(&p)).unwrap();

    // Second update with [3, 4]: avg = [1,2] + ([3,4]-[1,2])/2 = [2, 3].
    no_grad(|| unsafe { p.tensor().update_data(&[3.0f32, 4.0]) }).unwrap();
    avg.update_parameters(std::slice::from_ref(&p)).unwrap();

    avg.apply_to(std::slice::from_ref(&p)).unwrap();
    let data = p.data().unwrap();
    assert!(
        (data[0] - 2.0f32).abs() < 1e-5f32,
        "expected 2.0, got {}",
        data[0]
    );
    assert!(
        (data[1] - 3.0f32).abs() < 1e-5f32,
        "expected 3.0, got {}",
        data[1]
    );
}

// ===========================================================================
// Layer 2 — SWALR fixture-driven tests
// ===========================================================================

#[test]
fn swalr_cosine_sequence_matches_reference() {
    let fx = load_fixtures();
    let f = fx.swalr.iter().find(|f| f.kind == "swalr_cosine").unwrap();

    let mut sched = Swalr::new(
        f.swa_lr,
        f.anneal_epochs,
        ferrotorch_optim::swa::AnnealStrategy::Cosine,
    );
    let mut opt: MockOptimizer<f32> = MockOptimizer::new(f.initial_lr);

    for (step_idx, &exp_lr) in f.lr_sequence.iter().enumerate() {
        sched.step(&mut opt);
        assert!(
            (opt.lr - exp_lr).abs() < 1e-10,
            "[swalr_cosine] step {step_idx}: expected {exp_lr}, got {} (label: {})",
            opt.lr,
            f.label
        );
    }

    // After all anneal_epochs steps, should be at swa_lr.
    assert!(
        (opt.lr - f.expected_final_lr).abs() < 1e-10,
        "[swalr_cosine] final lr: expected {}, got {} (label: {})",
        f.expected_final_lr,
        opt.lr,
        f.label
    );
}

#[test]
fn swalr_cosine_midpoint_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .swalr
        .iter()
        .find(|f| f.kind == "swalr_cosine_midpoint")
        .unwrap();

    let mut sched = Swalr::new(
        f.swa_lr,
        f.anneal_epochs,
        ferrotorch_optim::swa::AnnealStrategy::Cosine,
    );
    let mut opt: MockOptimizer<f32> = MockOptimizer::new(f.initial_lr);

    for _ in 0..f.step {
        sched.step(&mut opt);
    }

    assert!(
        (opt.lr - f.expected_lr).abs() < 1e-10,
        "[swalr_cosine_midpoint] expected {}, got {} (label: {})",
        f.expected_lr,
        opt.lr,
        f.label
    );
}

#[test]
fn swalr_linear_midpoint_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .swalr
        .iter()
        .find(|f| f.kind == "swalr_linear_midpoint")
        .unwrap();

    let mut sched = Swalr::new(
        f.swa_lr,
        f.anneal_epochs,
        ferrotorch_optim::swa::AnnealStrategy::Linear,
    );
    let mut opt: MockOptimizer<f32> = MockOptimizer::new(f.initial_lr);

    for _ in 0..f.step {
        sched.step(&mut opt);
    }

    assert!(
        (opt.lr - f.expected_lr).abs() < 1e-10,
        "[swalr_linear_midpoint] expected {}, got {} (label: {})",
        f.expected_lr,
        opt.lr,
        f.label
    );
}

#[test]
fn swalr_linear_endpoint_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .swalr
        .iter()
        .find(|f| f.kind == "swalr_linear_endpoint")
        .unwrap();

    let mut sched = Swalr::new(
        f.swa_lr,
        f.anneal_epochs,
        ferrotorch_optim::swa::AnnealStrategy::Linear,
    );
    let mut opt: MockOptimizer<f32> = MockOptimizer::new(f.initial_lr);

    for _ in 0..f.step {
        sched.step(&mut opt);
    }

    assert!(
        (opt.lr - f.expected_lr).abs() < 1e-10,
        "[swalr_linear_endpoint] expected {}, got {} (label: {})",
        f.expected_lr,
        opt.lr,
        f.label
    );
}

#[test]
fn swalr_post_anneal_stays_at_swa_lr() {
    let fx = load_fixtures();
    let f = fx
        .swalr
        .iter()
        .find(|f| f.kind == "swalr_cosine_post_anneal")
        .unwrap();

    let mut sched = Swalr::new(
        f.swa_lr,
        f.anneal_epochs,
        ferrotorch_optim::swa::AnnealStrategy::Cosine,
    );
    let mut opt: MockOptimizer<f32> = MockOptimizer::new(f.initial_lr);

    for _ in 0..f.step {
        sched.step(&mut opt);
    }

    assert!(
        (opt.lr - f.expected_lr).abs() < 1e-10,
        "[swalr_post_anneal] expected {}, got {} (label: {})",
        f.expected_lr,
        opt.lr,
        f.label
    );
}

// ===========================================================================
// Layer 3 — LBFGS mathematical-property tests
// ===========================================================================

#[test]
fn lbfgs_converges_on_quadratic() {
    let fx = load_fixtures();
    let f = fx
        .lbfgs
        .iter()
        .find(|f| f.kind == "lbfgs_quadratic_convergence")
        .unwrap();

    let p = scalar_param(f.initial_x);
    let mut opt = Lbfgs::new(vec![p], LbfgsConfig::default().with_lr(f.lr));

    for _ in 0..f.n_steps {
        opt.zero_grad().unwrap();
        let x = opt.param_groups()[0].params()[0].tensor().clone();
        let loss = pow(&x, 2.0).unwrap();
        loss.backward().unwrap();
        opt.step().unwrap();
    }

    let val = opt.param_groups()[0].params()[0].tensor().data().unwrap()[0];
    assert!(
        val.abs() < f.convergence_tolerance * tolerance::CONVERGENCE_MARGIN,
        "[lbfgs_quadratic_convergence] expected |x| < {}, got |x| = {} (label: {})",
        f.convergence_tolerance,
        val.abs(),
        f.label
    );
}

#[test]
fn lbfgs_converges_on_multidim_quadratic() {
    let fx = load_fixtures();
    let f = fx
        .lbfgs
        .iter()
        .find(|f| f.kind == "lbfgs_multidim_quadratic_convergence")
        .unwrap();

    let params: Vec<Parameter<f64>> = f.initial_params.iter().map(|&v| scalar_param(v)).collect();
    let mut opt = Lbfgs::new(params, LbfgsConfig::default().with_lr(f.lr));

    for _ in 0..f.n_steps {
        opt.zero_grad().unwrap();
        let a = opt.param_groups()[0].params()[0].tensor().clone();
        let b = opt.param_groups()[0].params()[1].tensor().clone();
        let a_sq = pow(&a, 2.0).unwrap();
        let b_sq = pow(&b, 2.0).unwrap();
        let loss = add(&a_sq, &b_sq).unwrap();
        loss.backward().unwrap();
        opt.step().unwrap();
    }

    for (i, param) in opt.param_groups()[0].params().iter().enumerate() {
        let val = param.tensor().data().unwrap()[0];
        assert!(
            val.abs() < f.convergence_tolerance * tolerance::CONVERGENCE_MARGIN,
            "[lbfgs_multidim] param[{i}]: expected |v| < {}, got |v| = {} (label: {})",
            f.convergence_tolerance,
            val.abs(),
            f.label
        );
    }
}

#[test]
fn lbfgs_strong_wolfe_converges_on_quadratic() {
    // Property test: strong Wolfe line search also converges on x^2.
    let p = scalar_param(5.0);
    let mut opt = Lbfgs::new(
        vec![p],
        LbfgsConfig::default()
            .with_lr(1.0)
            .with_line_search_fn(Some(LineSearchFn::StrongWolfe)),
    );

    for _ in 0..50 {
        let param = opt.param_groups()[0].params()[0].clone();
        opt.step_with_closure(move || {
            let x = param.tensor().clone();
            let loss = pow(&x, 2.0).unwrap();
            loss.backward().unwrap();
            loss.item()
        })
        .unwrap();
    }

    let val = opt.param_groups()[0].params()[0].tensor().data().unwrap()[0];
    assert!(
        val.abs() < 1e-3,
        "[lbfgs_strong_wolfe] expected |x| < 1e-3, got {val}"
    );
}

#[test]
fn lbfgs_history_bounded_by_history_size() {
    // Property test: history never exceeds history_size entries.
    let p = scalar_param(10.0);
    let history_size = 3usize;
    let mut opt = Lbfgs::new(
        vec![p],
        LbfgsConfig::default()
            .with_lr(0.1)
            .with_history_size(history_size),
    );

    for _ in 0..15 {
        opt.zero_grad().unwrap();
        let x = opt.param_groups()[0].params()[0].tensor().clone();
        let loss = pow(&x, 2.0).unwrap();
        loss.backward().unwrap();
        opt.step().unwrap();
    }

    let state = opt.state_dict().unwrap();
    let history_len = state["meta"]["history_len"][0] as usize;
    assert!(
        history_len <= history_size,
        "[lbfgs_history] history_len {history_len} > history_size {history_size}"
    );
}

#[test]
fn lbfgs_step_requires_closure_for_line_search() {
    // Contract test: step() without closure errors when line_search_fn is set.
    let p = scalar_param(1.0);
    let mut opt = Lbfgs::new(
        vec![p],
        LbfgsConfig::default().with_line_search_fn(Some(LineSearchFn::StrongWolfe)),
    );
    let grad = t64(&[1.0], &[]);
    opt.param_groups_mut()[0].params()[0]
        .tensor()
        .set_grad(Some(grad))
        .unwrap();
    let result = opt.step();
    assert!(
        result.is_err(),
        "[lbfgs_contract] step without closure should error"
    );
}

// ===========================================================================
// Layer 2 — GradScaler fixture-driven tests
// ===========================================================================

#[test]
fn grad_scaler_default_init_scale_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .grad_scaler
        .iter()
        .find(|f| f.kind == "grad_scaler_default_init_scale")
        .unwrap();

    let scaler = GradScaler::<f32>::new(GradScalerConfig::default());
    assert!(
        (scaler.get_scale() - f.expected_init_scale).abs() < tolerance::F64_OPTIMIZER_CPU,
        "[grad_scaler_default] expected {}, got {} (label: {})",
        f.expected_init_scale,
        scaler.get_scale(),
        f.label
    );
}

#[test]
fn grad_scaler_inf_halves_scale_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .grad_scaler
        .iter()
        .find(|f| f.kind == "grad_scaler_inf_halves_scale")
        .unwrap();

    let config = GradScalerConfig::default()
        .with_init_scale(f.init_scale)
        .with_backoff_factor(f.backoff_factor);
    let mut scaler = GradScaler::<f32>::new(config);

    let p = Parameter::from_slice(&[1.0f32], &[1]).unwrap();
    let grad = t32(&[f32::INFINITY], &[1]);
    p.set_grad(Some(grad)).unwrap();

    let mut opt = MockOptimizer::with_params(0.01, vec![p]);
    let stepped = scaler.step(&mut opt).unwrap();
    assert!(!stepped, "[grad_scaler_inf] step should be skipped");
    assert!(
        !opt.step_called,
        "[grad_scaler_inf] optimizer must not be called"
    );

    scaler.update();
    assert!(
        (scaler.get_scale() - f.expected_scale_after_update).abs() < tolerance::F64_OPTIMIZER_CPU,
        "[grad_scaler_inf] expected scale {}, got {} (label: {})",
        f.expected_scale_after_update,
        scaler.get_scale(),
        f.label
    );
}

#[test]
fn grad_scaler_nan_skips_step() {
    let config = GradScalerConfig::default().with_init_scale(1024.0);
    let mut scaler = GradScaler::<f32>::new(config);

    let p = Parameter::from_slice(&[1.0f32], &[1]).unwrap();
    let grad = t32(&[f32::NAN], &[1]);
    p.set_grad(Some(grad)).unwrap();

    let mut opt = MockOptimizer::with_params(0.01, vec![p]);
    let stepped = scaler.step(&mut opt).unwrap();
    assert!(!stepped, "[grad_scaler_nan] step should be skipped");
}

#[test]
fn grad_scaler_growth_after_interval_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .grad_scaler
        .iter()
        .find(|f| f.kind == "grad_scaler_growth_after_interval")
        .unwrap();

    let config = GradScalerConfig::default()
        .with_init_scale(f.init_scale)
        .with_growth_factor(f.growth_factor)
        .with_growth_interval(f.growth_interval);
    let mut scaler = GradScaler::<f32>::new(config);

    for _ in 0..f.n_healthy_steps {
        let p = Parameter::from_slice(&[1.0f32], &[1]).unwrap();
        let grad = t32(&[1.0f32], &[1]);
        p.set_grad(Some(grad)).unwrap();
        let mut opt = MockOptimizer::with_params(0.01, vec![p]);
        let stepped = scaler.step(&mut opt).unwrap();
        assert!(stepped, "[grad_scaler_growth] healthy step should proceed");
        scaler.update();
    }

    assert!(
        (scaler.get_scale() - f.expected_scale_after_growth).abs() < tolerance::F64_OPTIMIZER_CPU,
        "[grad_scaler_growth] expected scale {}, got {} (label: {})",
        f.expected_scale_after_growth,
        scaler.get_scale(),
        f.label
    );
}

#[test]
fn grad_scaler_state_dict_roundtrip_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .grad_scaler
        .iter()
        .find(|f| f.kind == "grad_scaler_state_dict_roundtrip")
        .unwrap();

    let config = GradScalerConfig::default()
        .with_init_scale(f.init_scale)
        .with_growth_interval(10);
    let mut scaler = GradScaler::<f32>::new(config);

    // Advance tracker by 2 healthy steps.
    for _ in 0..2 {
        let p = Parameter::from_slice(&[1.0f32], &[1]).unwrap();
        let grad = t32(&[1.0f32], &[1]);
        p.set_grad(Some(grad)).unwrap();
        let mut opt = MockOptimizer::with_params(0.01, vec![p]);
        scaler.step(&mut opt).unwrap();
        scaler.update();
    }

    let state = scaler.state_dict();
    assert_eq!(
        state.growth_tracker, f.growth_tracker_after_2_steps,
        "[grad_scaler_state_dict] tracker: expected {}, got {} (label: {})",
        f.growth_tracker_after_2_steps, state.growth_tracker, f.label
    );
    assert!(
        (state.scale_factor - f.init_scale).abs() < tolerance::F64_OPTIMIZER_CPU,
        "[grad_scaler_state_dict] scale: expected {}, got {} (label: {})",
        f.init_scale,
        state.scale_factor,
        f.label
    );

    // Round-trip into a fresh scaler.
    let mut scaler2 = GradScaler::<f32>::new(GradScalerConfig::default());
    scaler2.load_state_dict(&state);
    let state2 = scaler2.state_dict();
    assert_eq!(state2.growth_tracker, state.growth_tracker);
    assert!((state2.scale_factor - state.scale_factor).abs() < tolerance::F64_OPTIMIZER_CPU);
}

#[test]
fn grad_scaler_disabled_passthrough() {
    let config = GradScalerConfig::default().with_enabled(false);
    let mut scaler = GradScaler::<f32>::new(config);

    // scale() returns the tensor unchanged.
    let loss = t32(&[5.0f32], &[1]);
    let scaled = scaler.scale(&loss).unwrap();
    assert!(
        (scaled.data().unwrap()[0] - 5.0f32).abs() < 1e-6f32,
        "[grad_scaler_disabled] scale should not modify loss"
    );

    // step() calls the optimizer even with an inf gradient.
    let p = Parameter::from_slice(&[1.0f32], &[1]).unwrap();
    let grad = t32(&[f32::INFINITY], &[1]);
    p.set_grad(Some(grad)).unwrap();
    let mut opt = MockOptimizer::with_params(0.01, vec![p]);
    let stepped = scaler.step(&mut opt).unwrap();
    assert!(stepped, "[grad_scaler_disabled] should always step");
    assert!(
        opt.step_called,
        "[grad_scaler_disabled] optimizer must be called"
    );
}

#[test]
fn grad_scaler_unscale_divides_gradients() {
    // Property test: unscale_ divides each gradient element by scale_factor.
    let scale = 256.0f64;
    let config = GradScalerConfig::default().with_init_scale(scale);
    let mut scaler = GradScaler::<f32>::new(config);

    let p = Parameter::from_slice(&[1.0f32, 2.0, 3.0], &[3]).unwrap();
    let grad = t32(&[256.0f32, 512.0, 768.0], &[3]);
    p.set_grad(Some(grad)).unwrap();

    let mut opt = MockOptimizer::with_params(0.01, vec![p]);
    scaler.unscale_(&mut opt).unwrap();

    let unscaled = opt.param_groups()[0].params()[0].grad().unwrap().unwrap();
    let data = unscaled.data().unwrap();
    assert!(
        (data[0] - 1.0f32).abs() < 1e-5f32,
        "expected 1.0, got {}",
        data[0]
    );
    assert!(
        (data[1] - 2.0f32).abs() < 1e-5f32,
        "expected 2.0, got {}",
        data[1]
    );
    assert!(
        (data[2] - 3.0f32).abs() < 1e-5f32,
        "expected 3.0, got {}",
        data[2]
    );
}

// ===========================================================================
// Layer 2 — GradientAccumulator fixture-driven tests
// ===========================================================================

#[test]
fn grad_accumulator_should_step_cycle_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .grad_accumulator
        .iter()
        .find(|f| f.kind == "grad_accum_should_step_cycle")
        .unwrap();

    let mut acc = GradientAccumulator::new(f.accumulation_steps);
    for (call_idx, &expected) in f.expected_results.iter().enumerate() {
        let got = acc.should_step();
        assert_eq!(
            got, expected,
            "[grad_accum_cycle] call {call_idx}: expected {expected}, got {got} (label: {})",
            f.label
        );
    }
}

#[test]
fn grad_accumulator_scale_loss_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .grad_accumulator
        .iter()
        .find(|f| f.kind == "grad_accum_scale_loss")
        .unwrap();

    let acc = GradientAccumulator::new(f.accumulation_steps);
    let loss = t64(&[f.loss], &[1]);
    let scaled = acc.scale_loss(&loss).unwrap();
    let got = scaled.data().unwrap()[0];
    assert!(
        (got - f.expected_scaled).abs() < tolerance::F64_OPTIMIZER_CPU,
        "[grad_accum_scale] expected {}, got {got} (label: {})",
        f.expected_scaled,
        f.label
    );
}

#[test]
fn grad_accumulator_scale_loss_identity_with_steps_one() {
    let fx = load_fixtures();
    let f = fx
        .grad_accumulator
        .iter()
        .find(|f| f.kind == "grad_accum_scale_loss_identity")
        .unwrap();

    let acc = GradientAccumulator::new(f.accumulation_steps);
    let loss = t64(&[f.loss], &[1]);
    let scaled = acc.scale_loss(&loss).unwrap();
    let got = scaled.data().unwrap()[0];
    assert!(
        (got - f.expected_scaled).abs() < tolerance::F64_OPTIMIZER_CPU,
        "[grad_accum_identity] expected {}, got {got} (label: {})",
        f.expected_scaled,
        f.label
    );
}

#[test]
fn grad_accumulator_mean_over_batches_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .grad_accumulator
        .iter()
        .find(|f| f.kind == "grad_accum_mean_over_batches")
        .unwrap();

    let acc = GradientAccumulator::new(f.n_accumulate);
    let mut total_scaled = 0.0f64;
    for &batch_loss in &f.batch_losses {
        let loss = t64(&[batch_loss], &[1]);
        let scaled = acc.scale_loss(&loss).unwrap();
        total_scaled += scaled.data().unwrap()[0];
    }
    assert!(
        (total_scaled - f.expected_mean_loss).abs() < tolerance::F64_OPTIMIZER_CPU,
        "[grad_accum_mean] expected {}, got {total_scaled} (label: {})",
        f.expected_mean_loss,
        f.label
    );
}

#[test]
fn grad_accumulator_zero_steps_panics() {
    // Contract: GradientAccumulator::new(0) must panic.
    let result = std::panic::catch_unwind(|| GradientAccumulator::new(0));
    assert!(result.is_err(), "[grad_accum_contract] new(0) should panic");
}

// ===========================================================================
// Layer 2 — Differentiable SGD fixture-driven tests
// ===========================================================================

#[test]
fn diff_sgd_step_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .differentiable
        .iter()
        .find(|f| f.kind == "diff_sgd_step")
        .unwrap();

    let param = Tensor::from_storage(
        TensorStorage::cpu(f.param.clone()),
        vec![f.param.len()],
        true,
    )
    .unwrap();
    let grad = t64(&f.grad, &[f.grad.len()]);
    let out = diff_sgd_step(&[param], &[grad], f.lr).unwrap();

    let got = out[0].data().unwrap().to_vec();
    for (i, (&g, &exp)) in got.iter().zip(f.expected.iter()).enumerate() {
        assert!(
            (g - exp).abs() < tolerance::F64_OPTIMIZER_CPU,
            "[diff_sgd_step] element {i}: expected {exp}, got {g} (label: {})",
            f.label
        );
    }
}

#[test]
fn diff_sgd_step_multi_param_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .differentiable
        .iter()
        .find(|f| f.kind == "diff_sgd_step_multi_param")
        .unwrap();

    let params: Vec<Tensor<f64>> = f
        .params
        .iter()
        .map(|p| Tensor::from_storage(TensorStorage::cpu(p.clone()), vec![p.len()], true).unwrap())
        .collect();
    let grads: Vec<Tensor<f64>> = f.grads.iter().map(|g| t64(g, &[g.len()])).collect();
    let out = diff_sgd_step(&params, &grads, f.lr).unwrap();

    for (param_idx, (got_t, exp_slice)) in out.iter().zip(f.expected_params.iter()).enumerate() {
        let got = got_t.data().unwrap().to_vec();
        for (i, (&g, &exp)) in got.iter().zip(exp_slice.iter()).enumerate() {
            assert!(
                (g - exp).abs() < tolerance::F64_OPTIMIZER_CPU,
                "[diff_sgd_multi] param {param_idx} elem {i}: expected {exp}, got {g} (label: {})",
                f.label
            );
        }
    }
}

#[test]
fn diff_sgd_momentum_step_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .differentiable
        .iter()
        .find(|f| f.kind == "diff_sgd_momentum_step")
        .unwrap();

    let param = Tensor::from_storage(
        TensorStorage::cpu(f.param.clone()),
        vec![f.param.len()],
        true,
    )
    .unwrap();
    let grad = t64(&f.grad, &[f.grad.len()]);
    let v_prev = t64(&f.v_prev, &[f.v_prev.len()]);

    let (new_params, new_velocities) =
        diff_sgd_momentum_step(&[param], &[grad], &[v_prev], f.lr, f.momentum).unwrap();

    let got_v = new_velocities[0].data().unwrap().to_vec();
    let got_p = new_params[0].data().unwrap().to_vec();

    for (i, (&g, &exp)) in got_v.iter().zip(f.expected_v_new.iter()).enumerate() {
        assert!(
            (g - exp).abs() < tolerance::F64_OPTIMIZER_CPU,
            "[diff_sgd_mom] v_new[{i}]: expected {exp}, got {g} (label: {})",
            f.label
        );
    }
    for (i, (&g, &exp)) in got_p.iter().zip(f.expected_p_new.iter()).enumerate() {
        assert!(
            (g - exp).abs() < tolerance::F64_OPTIMIZER_CPU,
            "[diff_sgd_mom] p_new[{i}]: expected {exp}, got {g} (label: {})",
            f.label
        );
    }
}

#[test]
fn diff_sgd_momentum_first_step_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .differentiable
        .iter()
        .find(|f| f.kind == "diff_sgd_momentum_step_first")
        .unwrap();

    let params: Vec<Tensor<f64>> = f
        .param
        .iter()
        .map(|&v| Tensor::from_storage(TensorStorage::cpu(vec![v]), vec![], true).unwrap())
        .collect();
    let grads: Vec<Tensor<f64>> = f.grad.iter().map(|&v| t64(&[v], &[])).collect();

    let (new_params, new_velocities) =
        diff_sgd_momentum_step(&params, &grads, &[], f.lr, f.momentum).unwrap();

    for (i, (got_v, &exp_v)) in new_velocities
        .iter()
        .zip(f.expected_v_new.iter())
        .enumerate()
    {
        let v = got_v.data().unwrap()[0];
        assert!(
            (v - exp_v).abs() < tolerance::F64_OPTIMIZER_CPU,
            "[diff_sgd_mom_first] v_new[{i}]: expected {exp_v}, got {v} (label: {})",
            f.label
        );
    }
    for (i, (got_p, &exp_p)) in new_params.iter().zip(f.expected_p_new.iter()).enumerate() {
        let p = got_p.data().unwrap()[0];
        assert!(
            (p - exp_p).abs() < tolerance::F64_OPTIMIZER_CPU,
            "[diff_sgd_mom_first] p_new[{i}]: expected {exp_p}, got {p} (label: {})",
            f.label
        );
    }
}

#[test]
fn diff_sgd_step_autograd_edge_to_param() {
    // Property test: adapted = param - lr*grad has an autograd edge to param.
    use ferrotorch_core::grad_fns::reduction::sum;
    let theta =
        Tensor::from_storage(TensorStorage::cpu(vec![1.0f64, 2.0, 3.0]), vec![3], true).unwrap();
    let grad = t64(&[0.1, 0.2, 0.3], &[3]);
    let adapted = diff_sgd_step(std::slice::from_ref(&theta), &[grad], 0.1).unwrap();
    let loss = sum(&adapted[0]).unwrap();
    loss.backward().unwrap();
    let theta_grad = theta.grad().unwrap().unwrap();
    for &v in theta_grad.data().unwrap() {
        assert!(
            (v - 1.0f64).abs() < tolerance::F64_OPTIMIZER_CPU,
            "[diff_sgd_autograd] d(loss)/d(theta) should be 1.0, got {v}"
        );
    }
}

// ===========================================================================
// Layer 2 — foreach_utils fixture-driven tests
// ===========================================================================

#[test]
fn foreach_elemwise_max_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .foreach_utils
        .iter()
        .find(|f| f.kind == "elemwise_max")
        .unwrap();

    let a: Vec<f64> = f.a.clone();
    let b: Vec<f64> = f.b.clone();
    let ta = t64(&a, &[a.len()]);
    let tb = t64(&b, &[b.len()]);

    let result = elemwise_max(&ta, &tb, ferrotorch_core::Device::Cpu).unwrap();
    let got = result.data().unwrap().to_vec();

    for (i, (&g, &exp)) in got.iter().zip(f.expected.iter()).enumerate() {
        assert!(
            (g - exp).abs() < tolerance::F64_OPTIMIZER_CPU,
            "[foreach_max] element {i}: expected {exp}, got {g} (label: {})",
            f.label
        );
    }
}

#[test]
fn foreach_f64_scalar_on_produces_correct_value() {
    let fx = load_fixtures();
    let f = fx
        .foreach_utils
        .iter()
        .find(|f| f.kind == "f64_scalar_on")
        .unwrap();

    let scalar = f64_scalar_on::<f64>(f.value, ferrotorch_core::Device::Cpu).unwrap();
    let got = scalar.data().unwrap()[0];
    assert!(
        (got - f.expected_scalar).abs() < tolerance::F64_OPTIMIZER_CPU,
        "[foreach_scalar] expected {}, got {got} (label: {})",
        f.expected_scalar,
        f.label
    );
}

// ===========================================================================
// Layer 2 — Optimizer / ParamGroup fixture-driven tests
// ===========================================================================

#[test]
fn param_group_default_weight_decay_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .optimizer
        .iter()
        .find(|f| f.kind == "param_group_default_weight_decay")
        .unwrap();

    let p = Parameter::<f64>::zeros(&[2]).unwrap();
    let group = ParamGroup::new(vec![p], f.lr);
    assert!(
        (group.weight_decay - f.expected_weight_decay).abs() < tolerance::F64_OPTIMIZER_CPU,
        "[param_group_wd] expected {}, got {} (label: {})",
        f.expected_weight_decay,
        group.weight_decay,
        f.label
    );
    assert!(
        (group.lr - f.lr).abs() < tolerance::F64_OPTIMIZER_CPU,
        "[param_group_lr] expected {}, got {} (label: {})",
        f.lr,
        group.lr,
        f.label
    );
}

#[test]
fn param_group_with_weight_decay_builder_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .optimizer
        .iter()
        .find(|f| f.kind == "param_group_with_weight_decay")
        .unwrap();

    let p = Parameter::<f64>::zeros(&[2]).unwrap();
    let group = ParamGroup::new(vec![p], f.lr).with_weight_decay(f.weight_decay);
    assert!(
        (group.weight_decay - f.weight_decay).abs() < tolerance::F64_OPTIMIZER_CPU,
        "[param_group_wd_builder] expected {}, got {} (label: {})",
        f.weight_decay,
        group.weight_decay,
        f.label
    );
}

// ===========================================================================
// Layer 3 — Muon mathematical-property tests
// ===========================================================================

#[test]
fn muon_newton_schulz_produces_orthogonal_matrix() {
    let fx = load_fixtures();
    let f = fx
        .muon
        .iter()
        .find(|f| f.kind == "muon_ns_orthogonality")
        .unwrap();

    // Run a Muon step on a 2x2 parameter with the given input as the gradient
    // (no-momentum, no-nesterov), then verify the parameter moved in an
    // orthogonal direction. We check the property via a direct Newton-Schulz
    // test: construct gradient matrix G, run orthogonalization, verify
    // G_orth^T @ G_orth ≈ I.
    //
    // The Muon internals call `newton_schulz_orthogonalize` but it is private.
    // We drive the property through a Muon step and inspect parameter movement.
    let g_flat: Vec<f64> = f.input.iter().flat_map(|row| row.iter().copied()).collect();
    let p = param_from(&[1.0, 0.0, 0.0, 1.0], &[2, 2]); // identity matrix
    let grad_t =
        Tensor::from_storage(TensorStorage::cpu(g_flat.clone()), vec![2, 2], false).unwrap();
    p.set_grad(Some(grad_t)).unwrap();

    let config = MuonConfig::new(0.1)
        .momentum(0.0)
        .nesterov(false)
        .ns_steps(10);
    let mut muon = Muon::new(vec![p], config);
    muon.step().unwrap();

    // The parameter was updated: param_new = I - lr * G_orth.
    // G_orth should be orthogonal; verify by checking that the update direction
    // satisfies ||G_orth @ G_orth^T - I||_max < tolerance.
    // We extract G_orth = (I - param_new) / lr.
    let param_new = muon.param_groups()[0].params()[0].data().unwrap().to_vec();
    let lr = 0.1f64;
    // g_orth[i] = (identity[i] - param_new[i]) / lr
    let identity = [1.0, 0.0, 0.0, 1.0];
    let g_orth: Vec<f64> = identity
        .iter()
        .zip(param_new.iter())
        .map(|(&id, &pn)| (id - pn) / lr)
        .collect();

    // Compute G_orth^T @ G_orth (should be ~ I for orthogonal G_orth).
    let mut product = [0.0f64; 4];
    for i in 0..2 {
        for j in 0..2 {
            for k in 0..2 {
                product[i * 2 + j] += g_orth[k * 2 + i] * g_orth[k * 2 + j];
            }
        }
    }
    let tol = f.tolerance;
    assert!(
        (product[0] - 1.0).abs() < tol,
        "[muon_ns] (0,0)={} not ~1.0",
        product[0]
    );
    assert!(
        (product[3] - 1.0).abs() < tol,
        "[muon_ns] (1,1)={} not ~1.0",
        product[3]
    );
    assert!(
        product[1].abs() < tol,
        "[muon_ns] (0,1)={} not ~0.0",
        product[1]
    );
    assert!(
        product[2].abs() < tol,
        "[muon_ns] (1,0)={} not ~0.0",
        product[2]
    );
}

#[test]
fn muon_converges_on_quadratic() {
    let fx = load_fixtures();
    let f = fx
        .muon
        .iter()
        .find(|f| f.kind == "muon_convergence_1d")
        .unwrap();

    let init: Vec<f64> = f.initial_param.clone();
    let p = param_from(&init, &[init.len()]);

    let config = MuonConfig::new(f.lr).momentum(0.9).nesterov(true);
    let mut muon = Muon::new(vec![p], config);

    for _ in 0..f.n_steps {
        let current = muon.param_groups()[0].params()[0].data().unwrap().to_vec();
        let grad = Tensor::from_storage(
            TensorStorage::cpu(current.clone()),
            vec![current.len()],
            false,
        )
        .unwrap();
        muon.param_groups_mut()[0].params()[0]
            .set_grad(Some(grad))
            .unwrap();
        muon.step().unwrap();
    }

    let final_data = muon.param_groups()[0].params()[0].data().unwrap().to_vec();
    let norm_sq: f64 = final_data.iter().map(|&x| x * x).sum();
    assert!(
        norm_sq < f.convergence_tolerance_norm_sq * tolerance::CONVERGENCE_MARGIN,
        "[muon_convergence] ||x||^2 = {norm_sq} not < {} (label: {})",
        f.convergence_tolerance_norm_sq,
        f.label
    );
}

#[test]
fn muon_state_dict_roundtrip_preserves_momentum_buffers() {
    // Property test: state_dict/load_state_dict round-trips momentum buffers.
    let p = param_from(&[5.0, 5.0], &[2]);
    let config = MuonConfig::new(0.02).momentum(0.95);
    let mut muon = Muon::new(vec![p], config);

    let grad = Tensor::from_storage(TensorStorage::cpu(vec![1.0f64, 2.0]), vec![2], false).unwrap();
    muon.param_groups_mut()[0].params()[0]
        .set_grad(Some(grad))
        .unwrap();
    muon.step().unwrap();

    let state = muon.state_dict().unwrap();
    assert!(
        !state.is_empty(),
        "[muon_state_dict] should be non-empty after a step"
    );

    let p2 = param_from(&[5.0, 5.0], &[2]);
    let mut muon2 = Muon::new(vec![p2], MuonConfig::new(0.02).momentum(0.95));
    muon2.load_state_dict(&state).unwrap();

    let state2 = muon2.state_dict().unwrap();

    // Element-wise comparison of the momentum buffer — a stub that loads
    // zeros (or any other length-preserving value) is rejected here.
    let buf1: &Vec<f64> = state
        .get("0_0")
        .and_then(|m| m.get("momentum_buffer"))
        .expect("[muon_state_dict] state must contain 0_0/momentum_buffer");
    let buf2: &Vec<f64> = state2
        .get("0_0")
        .and_then(|m| m.get("momentum_buffer"))
        .expect("[muon_state_dict] state2 must contain 0_0/momentum_buffer after load");
    assert_eq!(
        buf1.len(),
        buf2.len(),
        "[muon_state_dict] momentum buffer length must round-trip"
    );
    for (i, (&a, &b)) in buf1.iter().zip(buf2.iter()).enumerate() {
        assert!(
            (a - b).abs() < tolerance::F64_OPTIMIZER_CPU,
            "[muon_state_dict] momentum_buffer[{i}]: original {a} vs round-tripped {b}"
        );
    }
}

// ===========================================================================
// Layer 3 — K-FAC (natural gradient) mathematical-property tests
// ===========================================================================

#[test]
fn kfac_factor_update_arithmetic_matches_reference() {
    let fx = load_fixtures();
    let f = fx
        .kfac
        .iter()
        .find(|f| f.kind == "kfac_factor_update")
        .unwrap();

    let n_features = f.activation[0].len();
    let n_batch = f.activation.len();
    let flat_act: Vec<f64> = f
        .activation
        .iter()
        .flat_map(|r| r.iter().copied())
        .collect();
    let act_t = Tensor::from_storage(
        TensorStorage::cpu(flat_act),
        vec![n_batch, n_features],
        false,
    )
    .unwrap();

    // out_features = 1 for simplicity; gradient is all ones.
    let grad_t = Tensor::from_storage(
        TensorStorage::cpu(vec![1.0f64; n_batch]),
        vec![n_batch, 1],
        false,
    )
    .unwrap();

    let p = param_from(&vec![0.0f64; n_features], &[1, n_features]);
    let config = KfacConfig::default().with_momentum(0.0); // no EMA blending
    let mut kfac = Kfac::new(vec![p], config);
    kfac.update_factors("g0_p0", &act_t, &grad_t).unwrap();

    let factors = kfac.state_dict().unwrap();
    let a_factor = factors
        .get("g0_p0")
        .and_then(|e| e.get("a_factor"))
        .expect("a_factor must be present");

    // Diagonal entries should match reference.
    for (i, &exp) in f.expected_a_factor_diag.iter().enumerate() {
        let got = a_factor[i * n_features + i];
        assert!(
            (got - exp).abs() < tolerance::F64_OPTIMIZER_CPU,
            "[kfac_factors] diag[{i}]: expected {exp}, got {got} (label: {})",
            f.label
        );
    }
    // Off-diagonal entries should be ~0 (centered/orthogonal activations).
    // Walk the actual computed matrix and assert each off-diagonal element
    // produced by the implementation is near zero — this catches a stub that
    // populates only the diagonal or returns the identity matrix unchanged.
    for i in 0..n_features {
        for j in 0..n_features {
            if i == j {
                continue;
            }
            let got = a_factor[i * n_features + j];
            assert!(
                got.abs() < tolerance::F64_OPTIMIZER_CPU,
                "[kfac_factors] off-diag[{i},{j}]: expected ~0, got {got} (label: {})",
                f.label
            );
        }
    }
    // Secondary guard: the fixture's recorded off-diagonal expectations are
    // themselves ~0 (so the empirical bound above matches the reference).
    for &exp in &f.expected_a_factor_offdiag {
        assert!(
            exp.abs() < tolerance::F64_OPTIMIZER_CPU,
            "[kfac_factors] off-diag fixture {exp} is not zero (label: {})",
            f.label
        );
    }
}

#[test]
fn kfac_falls_back_to_sgd_without_factors() {
    // Property test: without registered Kronecker factors, K-FAC update
    // equals SGD: param -= lr * grad.
    let lr = 0.1f64;
    let data = vec![1.0, 2.0, 3.0];
    let grad_data = vec![0.1, 0.2, 0.3];

    let p = param_from(&data, &[3]);
    let grad_t =
        Tensor::from_storage(TensorStorage::cpu(grad_data.clone()), vec![3], false).unwrap();
    p.tensor().set_grad(Some(grad_t)).unwrap();

    let config = KfacConfig::default()
        .with_lr(lr)
        .with_momentum(0.0)
        .with_update_freq(1)
        .with_damping(0.0)
        .with_weight_decay(0.0)
        .with_maximize(false);
    let mut kfac = Kfac::new(vec![p], config);
    kfac.step().unwrap();

    let updated = kfac.param_groups()[0].params()[0].data().unwrap().to_vec();
    for (i, (&got, (&orig, &g))) in updated
        .iter()
        .zip(data.iter().zip(grad_data.iter()))
        .enumerate()
    {
        let exp = orig - lr * g;
        assert!(
            (got - exp).abs() < tolerance::F64_OPTIMIZER_CPU,
            "[kfac_sgd_fallback] param[{i}]: expected {exp}, got {got}"
        );
    }
}

#[test]
fn kfac_converges_on_quadratic() {
    // Property test: K-FAC (with SGD fallback) converges on f(x) = x^2.
    let p = scalar_param(5.0);
    let config = KfacConfig::default()
        .with_lr(0.01)
        .with_damping(1e-3)
        .with_momentum(0.0)
        .with_update_freq(1)
        .with_weight_decay(0.0)
        .with_maximize(false);
    let mut kfac = Kfac::new(vec![p], config);

    for _ in 0..1000 {
        kfac.zero_grad().unwrap();
        let tensor = kfac.param_groups()[0].params()[0].tensor().clone();
        let loss = pow(&tensor, 2.0).unwrap();
        loss.backward().unwrap();
        kfac.step().unwrap();
    }

    let val = kfac.param_groups()[0].params()[0].tensor().data().unwrap()[0];
    assert!(
        val.abs() < 0.1,
        "[kfac_convergence] expected |x| < 0.1, got {val}"
    );
}

#[test]
fn kfac_state_dict_roundtrip() {
    // Property test: state_dict/load_state_dict preserves step_count and factors.
    let p = param_from(&[1.0, 2.0, 3.0, 4.0], &[2, 2]);
    let config = KfacConfig::default().with_momentum(0.0).with_update_freq(1);
    let mut kfac = Kfac::new(vec![p], config);

    let act = Tensor::from_storage(
        TensorStorage::cpu(vec![1.0, 0.0, 0.0, 1.0]),
        vec![2, 2],
        false,
    )
    .unwrap();
    let grad_out = Tensor::from_storage(
        TensorStorage::cpu(vec![1.0, 0.0, 0.0, 1.0]),
        vec![2, 2],
        false,
    )
    .unwrap();
    kfac.update_factors("g0_p0", &act, &grad_out).unwrap();

    let grad_t = Tensor::from_storage(
        TensorStorage::cpu(vec![0.1, 0.2, 0.3, 0.4]),
        vec![2, 2],
        false,
    )
    .unwrap();
    kfac.param_groups_mut()[0].params()[0]
        .tensor()
        .set_grad(Some(grad_t))
        .unwrap();
    kfac.step().unwrap();

    let saved = kfac.state_dict().unwrap();
    assert!(
        saved.contains_key("__kfac_meta__"),
        "[kfac_state] meta key must exist"
    );
    assert!(
        saved.contains_key("g0_p0"),
        "[kfac_state] factor key must exist"
    );
    assert_eq!(saved["__kfac_meta__"]["step_count"][0] as usize, 1);

    let p2 = param_from(&[1.0, 2.0, 3.0, 4.0], &[2, 2]);
    let mut kfac2 = Kfac::new(vec![p2], config);
    kfac2.load_state_dict(&saved).unwrap();

    assert_eq!(
        kfac2.state_dict().unwrap()["__kfac_meta__"]["step_count"][0] as usize,
        1
    );
}
