//! Conformance Phase C6.4 — `ferrotorch-optim` LR schedulers parity against
//! `torch.optim.lr_scheduler`.
//!
//! Tracking issue: crosslink #882.
//! Parent dispatch: C6 optim conformance (#806 family).
//!
//! ## Schedulers covered (12 total)
//!
//! | Scheduler | Source file |
//! |-----------|-------------|
//! | [`StepLR`] | `scheduler/step.rs` |
//! | [`MultiStepLR`] | `scheduler/multi_step_lr.rs` |
//! | [`ExponentialLR`] | `scheduler/exponential_lr.rs` |
//! | [`CosineAnnealingLR`] | `scheduler/cosine.rs` |
//! | [`CosineAnnealingWarmRestarts`] | `scheduler/cosine_warm_restarts.rs` |
//! | [`CyclicLR`] | `scheduler/cyclic_lr.rs` |
//! | [`OneCycleLR`] | `scheduler/one_cycle_lr.rs` |
//! | [`PolynomialLR`] | `scheduler/polynomial_lr.rs` |
//! | [`ConstantLR`] | `scheduler/constant_lr.rs` |
//! | [`LinearLR`] | `scheduler/linear_lr.rs` |
//! | [`LinearWarmup`] | `scheduler/warmup.rs` |
//! | [`ReduceLROnPlateau`] | `scheduler/plateau.rs` |
//!
//! ## Fixture source
//!
//! `ferrotorch-optim/tests/conformance/scheduler_fixtures.json`
//! Generated by `scripts/regenerate_optim_scheduler_fixtures.py`
//! (pin: torch == 2.11.0, analytical formulas).
//!
//! ## Tolerance
//!
//! LR schedulers perform exact closed-form arithmetic with no GPU or
//! stochastic components. Tolerance: 1e-9 absolute.

use serde::Deserialize;
use std::path::PathBuf;

use ferrotorch_optim::scheduler::{
    AnnealStrategy, ConstantLR, CosineAnnealingLR, CosineAnnealingWarmRestarts, CyclicLR,
    CyclicMode, ExponentialLR, LinearLR, LinearWarmup, LrScheduler, MetricScheduler, MultiStepLR,
    OneCycleLR, PlateauMode, PolynomialLR, ReduceLROnPlateau, StepLR,
};

// ---------------------------------------------------------------------------
// Tolerance: closed-form, no GPU — 1e-9 is generous for double-precision math
// ---------------------------------------------------------------------------
const LR_TOL: f64 = 1e-9;

// ---------------------------------------------------------------------------
// Mock optimizer (mirrors the pattern used by unit tests in scheduler modules)
// ---------------------------------------------------------------------------

use ferrotorch_core::FerrotorchResult;
use ferrotorch_optim::optimizer::{Optimizer, OptimizerState, ParamGroup};

struct MockOptimizer {
    lr: f64,
}

impl MockOptimizer {
    fn new(lr: f64) -> Self {
        Self { lr }
    }
}

impl Optimizer<f32> for MockOptimizer {
    fn step(&mut self) -> FerrotorchResult<()> {
        Ok(())
    }
    fn zero_grad(&mut self) -> FerrotorchResult<()> {
        Ok(())
    }
    fn lr(&self) -> f64 {
        self.lr
    }
    fn set_lr(&mut self, lr: f64) {
        self.lr = lr;
    }
    fn param_groups(&self) -> &[ParamGroup<f32>] {
        &[]
    }
    fn param_groups_mut(&mut self) -> &mut [ParamGroup<f32>] {
        &mut []
    }
    fn add_param_group(&mut self, _group: ParamGroup<f32>) {
        // Mock: no param-group storage needed for scheduler tests.
    }
    fn state_dict(&self) -> FerrotorchResult<OptimizerState> {
        Ok(Default::default())
    }
    fn load_state_dict(&mut self, _state: &OptimizerState) -> FerrotorchResult<()> {
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Fixture types
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct SchedulerFixtures {
    fixtures: Vec<SchedulerFixture>,
}

#[derive(Debug, Deserialize)]
struct SchedulerFixture {
    scheduler: String,
    params: serde_json::Value,
    n_steps: usize,
    #[serde(default)]
    metrics: Vec<f64>,
    lr_sequence: Vec<f64>,
}

// ---------------------------------------------------------------------------
// Fixture loader
// ---------------------------------------------------------------------------

fn load_fixtures() -> SchedulerFixtures {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "tests",
        "conformance",
        "scheduler_fixtures.json",
    ]
    .iter()
    .collect();
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {e}", path.display()));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("Failed to parse {}: {e}", path.display()))
}

// ---------------------------------------------------------------------------
// Helper: assert LR sequence
// ---------------------------------------------------------------------------

fn assert_lr_sequence(label: &str, actual: &[f64], expected: &[f64]) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: sequence length mismatch"
    );
    for (step, (&got, &want)) in actual.iter().zip(expected.iter()).enumerate() {
        let diff = (got - want).abs();
        assert!(
            diff <= LR_TOL,
            "{label} step {}: got={got:.15e}, want={want:.15e}, diff={diff:.3e} > tol={LR_TOL:.3e}",
            step + 1,
        );
    }
}

// ---------------------------------------------------------------------------
// Helper: cascade_skip — marks a test as blocked by a known bug
// ---------------------------------------------------------------------------

#[track_caller]
#[allow(dead_code)]
fn cascade_skip(issue: u32, reason: &str) {
    eprintln!("cascade_skip(#{issue}): {reason}");
}

// ---------------------------------------------------------------------------
// Layer-3 conformance tests
// ---------------------------------------------------------------------------

// --- StepLR -----------------------------------------------------------------

#[test]
fn step_lr_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "StepLR")
        .collect();
    assert!(!cases.is_empty(), "no StepLR fixtures found");

    for case in cases {
        let p = &case.params;
        let base_lr = p["base_lr"].as_f64().unwrap();
        let step_size = p["step_size"].as_u64().unwrap() as usize;
        let gamma = p["gamma"].as_f64().unwrap();

        let mut sched = StepLR::new(base_lr, step_size, gamma);
        let mut opt = MockOptimizer::new(base_lr);
        let mut actual = Vec::with_capacity(case.n_steps);

        for _ in 0..case.n_steps {
            sched.step(&mut opt);
            actual.push(opt.lr);
        }

        let label = format!("StepLR(base_lr={base_lr}, step_size={step_size}, gamma={gamma})");
        assert_lr_sequence(&label, &actual, &case.lr_sequence);

        // Also verify get_lr() agrees with the optimizer's lr after the final step.
        // This exercises LrScheduler::get_lr and StepLR::get_lr.
        assert!(
            (sched.get_lr() - opt.lr).abs() < LR_TOL,
            "{label}: sched.get_lr()={} != opt.lr={}",
            sched.get_lr(),
            opt.lr
        );
    }
}

// --- MultiStepLR ------------------------------------------------------------

#[test]
fn multi_step_lr_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "MultiStepLR")
        .collect();
    assert!(!cases.is_empty(), "no MultiStepLR fixtures found");

    for case in cases {
        let p = &case.params;
        let base_lr = p["base_lr"].as_f64().unwrap();
        let milestones: Vec<usize> = p["milestones"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        let gamma = p["gamma"].as_f64().unwrap();

        let mut sched = MultiStepLR::new(base_lr, milestones.clone(), gamma);
        let mut opt = MockOptimizer::new(base_lr);
        let mut actual = Vec::with_capacity(case.n_steps);

        for _ in 0..case.n_steps {
            sched.step(&mut opt);
            actual.push(opt.lr);
        }

        let label =
            format!("MultiStepLR(base_lr={base_lr}, milestones={milestones:?}, gamma={gamma})");
        assert_lr_sequence(&label, &actual, &case.lr_sequence);
    }
}

// --- ExponentialLR ----------------------------------------------------------

#[test]
fn exponential_lr_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "ExponentialLR")
        .collect();
    assert!(!cases.is_empty(), "no ExponentialLR fixtures found");

    for case in cases {
        let p = &case.params;
        let base_lr = p["base_lr"].as_f64().unwrap();
        let gamma = p["gamma"].as_f64().unwrap();

        let mut sched = ExponentialLR::new(base_lr, gamma);
        let mut opt = MockOptimizer::new(base_lr);
        let mut actual = Vec::with_capacity(case.n_steps);

        for _ in 0..case.n_steps {
            sched.step(&mut opt);
            actual.push(opt.lr);
        }

        let label = format!("ExponentialLR(base_lr={base_lr}, gamma={gamma})");
        assert_lr_sequence(&label, &actual, &case.lr_sequence);
    }
}

// --- CosineAnnealingLR ------------------------------------------------------

#[test]
fn cosine_annealing_lr_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "CosineAnnealingLR")
        .collect();
    assert!(!cases.is_empty(), "no CosineAnnealingLR fixtures found");

    for case in cases {
        let p = &case.params;
        let base_lr = p["base_lr"].as_f64().unwrap();
        let t_max = p["t_max"].as_u64().unwrap() as usize;
        let eta_min = p["eta_min"].as_f64().unwrap();

        let mut sched = CosineAnnealingLR::new(base_lr, t_max, eta_min);
        let mut opt = MockOptimizer::new(base_lr);
        let mut actual = Vec::with_capacity(case.n_steps);

        for _ in 0..case.n_steps {
            sched.step(&mut opt);
            actual.push(opt.lr);
        }

        let label =
            format!("CosineAnnealingLR(base_lr={base_lr}, t_max={t_max}, eta_min={eta_min})");
        assert_lr_sequence(&label, &actual, &case.lr_sequence);
    }
}

// --- CosineAnnealingWarmRestarts --------------------------------------------

#[test]
fn cosine_annealing_warm_restarts_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "CosineAnnealingWarmRestarts")
        .collect();
    assert!(
        !cases.is_empty(),
        "no CosineAnnealingWarmRestarts fixtures found"
    );

    for case in cases {
        let p = &case.params;
        let base_lr = p["base_lr"].as_f64().unwrap();
        let t_0 = p["t_0"].as_u64().unwrap() as usize;
        let t_mult = p["t_mult"].as_u64().unwrap() as usize;
        let eta_min = p["eta_min"].as_f64().unwrap();

        let mut sched = CosineAnnealingWarmRestarts::new(base_lr, t_0, t_mult, eta_min);
        let mut opt = MockOptimizer::new(base_lr);
        let mut actual = Vec::with_capacity(case.n_steps);

        for _ in 0..case.n_steps {
            sched.step(&mut opt);
            actual.push(opt.lr);
        }

        let label = format!(
            "CosineAnnealingWarmRestarts(base_lr={base_lr}, t_0={t_0}, t_mult={t_mult}, eta_min={eta_min})"
        );
        assert_lr_sequence(&label, &actual, &case.lr_sequence);
    }
}

// --- PolynomialLR -----------------------------------------------------------

#[test]
fn polynomial_lr_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "PolynomialLR")
        .collect();
    assert!(!cases.is_empty(), "no PolynomialLR fixtures found");

    for case in cases {
        let p = &case.params;
        let base_lr = p["base_lr"].as_f64().unwrap();
        let total_iters = p["total_iters"].as_u64().unwrap() as usize;
        let power = p["power"].as_f64().unwrap();

        let mut sched = PolynomialLR::new(base_lr, total_iters, power);
        let mut opt = MockOptimizer::new(base_lr);
        let mut actual = Vec::with_capacity(case.n_steps);

        for _ in 0..case.n_steps {
            sched.step(&mut opt);
            actual.push(opt.lr);
        }

        let label =
            format!("PolynomialLR(base_lr={base_lr}, total_iters={total_iters}, power={power})");
        assert_lr_sequence(&label, &actual, &case.lr_sequence);
    }
}

// --- ConstantLR -------------------------------------------------------------

#[test]
fn constant_lr_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "ConstantLR")
        .collect();
    assert!(!cases.is_empty(), "no ConstantLR fixtures found");

    for case in cases {
        let p = &case.params;
        let base_lr = p["base_lr"].as_f64().unwrap();
        let factor = p["factor"].as_f64().unwrap();
        let total_iters = p["total_iters"].as_u64().unwrap() as usize;

        let mut sched = ConstantLR::new(base_lr, factor, total_iters);
        let mut opt = MockOptimizer::new(base_lr);
        let mut actual = Vec::with_capacity(case.n_steps);

        for _ in 0..case.n_steps {
            sched.step(&mut opt);
            actual.push(opt.lr);
        }

        let label =
            format!("ConstantLR(base_lr={base_lr}, factor={factor}, total_iters={total_iters})");
        assert_lr_sequence(&label, &actual, &case.lr_sequence);
    }
}

// --- LinearLR ---------------------------------------------------------------

#[test]
fn linear_lr_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "LinearLR")
        .collect();
    assert!(!cases.is_empty(), "no LinearLR fixtures found");

    for case in cases {
        let p = &case.params;
        let base_lr = p["base_lr"].as_f64().unwrap();
        let start_factor = p["start_factor"].as_f64().unwrap();
        let end_factor = p["end_factor"].as_f64().unwrap();
        let total_iters = p["total_iters"].as_u64().unwrap() as usize;

        let mut sched = LinearLR::new(base_lr, start_factor, end_factor, total_iters);
        let mut opt = MockOptimizer::new(base_lr * start_factor);
        let mut actual = Vec::with_capacity(case.n_steps);

        for _ in 0..case.n_steps {
            sched.step(&mut opt);
            actual.push(opt.lr);
        }

        let label = format!(
            "LinearLR(base_lr={base_lr}, start_factor={start_factor}, end_factor={end_factor}, total_iters={total_iters})"
        );
        assert_lr_sequence(&label, &actual, &case.lr_sequence);
    }
}

// --- LinearWarmup -----------------------------------------------------------

#[test]
fn linear_warmup_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "LinearWarmup")
        .collect();
    assert!(!cases.is_empty(), "no LinearWarmup fixtures found");

    for case in cases {
        let p = &case.params;
        let base_lr = p["base_lr"].as_f64().unwrap();
        let warmup_steps = p["warmup_steps"].as_u64().unwrap() as usize;

        let mut sched = LinearWarmup::new(base_lr, warmup_steps);
        let mut opt = MockOptimizer::new(0.0);
        let mut actual = Vec::with_capacity(case.n_steps);

        for _ in 0..case.n_steps {
            sched.step(&mut opt);
            actual.push(opt.lr);
        }

        let label = format!("LinearWarmup(base_lr={base_lr}, warmup_steps={warmup_steps})");
        assert_lr_sequence(&label, &actual, &case.lr_sequence);
    }
}

// --- ReduceLROnPlateau ------------------------------------------------------

#[test]
fn reduce_lr_on_plateau_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "ReduceLROnPlateau")
        .collect();
    assert!(!cases.is_empty(), "no ReduceLROnPlateau fixtures found");

    for case in cases {
        let p = &case.params;
        let init_lr = p["init_lr"].as_f64().unwrap();
        let factor = p["factor"].as_f64().unwrap();
        let patience = p["patience"].as_u64().unwrap() as usize;
        let threshold = p["threshold"].as_f64().unwrap();

        let mut sched = ReduceLROnPlateau::new(PlateauMode::Min)
            .factor(factor)
            .patience(patience)
            .threshold(threshold);
        let mut opt = MockOptimizer::new(init_lr);
        let mut actual = Vec::with_capacity(case.n_steps);

        for &metric in &case.metrics {
            <ReduceLROnPlateau as MetricScheduler<f32>>::step(&mut sched, &mut opt, metric);
            actual.push(opt.lr);
        }

        let label = format!(
            "ReduceLROnPlateau(init_lr={init_lr}, factor={factor}, patience={patience}, threshold={threshold})"
        );
        assert_lr_sequence(&label, &actual, &case.lr_sequence);
    }
}

// --- OneCycleLR -------------------------------------------------------------

#[test]
fn one_cycle_lr_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "OneCycleLR")
        .collect();
    assert!(!cases.is_empty(), "no OneCycleLR fixtures found");

    for case in cases {
        let p = &case.params;
        let max_lr = p["max_lr"].as_f64().unwrap();
        let total_steps = p["total_steps"].as_u64().unwrap() as usize;
        let pct_start = p["pct_start"].as_f64().unwrap();
        let div_factor = p["div_factor"].as_f64().unwrap();
        let final_div_factor = p["final_div_factor"].as_f64().unwrap();
        let anneal_str = p["anneal"].as_str().unwrap();
        let anneal = if anneal_str == "cos" {
            AnnealStrategy::Cos
        } else {
            AnnealStrategy::Linear
        };

        let mut sched = OneCycleLR::new(
            max_lr,
            total_steps,
            pct_start,
            anneal,
            div_factor,
            final_div_factor,
            false,
        );
        let mut opt = MockOptimizer::new(max_lr / div_factor);
        let mut actual = Vec::with_capacity(case.n_steps);

        for _ in 0..case.n_steps {
            sched.step(&mut opt);
            actual.push(opt.lr);
        }

        let label = format!(
            "OneCycleLR(max_lr={max_lr}, total_steps={total_steps}, pct_start={pct_start}, anneal={anneal_str})"
        );
        assert_lr_sequence(&label, &actual, &case.lr_sequence);
    }
}

// --- CyclicLR ---------------------------------------------------------------

#[test]
fn cyclic_lr_matches_reference() {
    let fixtures = load_fixtures();
    let cases: Vec<_> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.scheduler == "CyclicLR")
        .collect();
    assert!(!cases.is_empty(), "no CyclicLR fixtures found");

    for case in cases {
        let p = &case.params;
        let base_lr = p["base_lr"].as_f64().unwrap();
        let max_lr = p["max_lr"].as_f64().unwrap();
        let step_size_up = p["step_size_up"].as_u64().unwrap() as usize;
        let step_size_down = p["step_size_down"].as_u64().unwrap() as usize;
        let mode_str = p["mode"].as_str().unwrap();
        let gamma = p["gamma"].as_f64().unwrap();

        let mode = match mode_str {
            "triangular" => CyclicMode::Triangular,
            "triangular2" => CyclicMode::Triangular2,
            "exp_range" => CyclicMode::ExpRange,
            other => panic!("unknown CyclicMode: {other}"),
        };

        let mut sched = CyclicLR::new(
            base_lr,
            max_lr,
            step_size_up,
            Some(step_size_down),
            mode,
            gamma,
        );
        let mut opt = MockOptimizer::new(base_lr);
        let mut actual = Vec::with_capacity(case.n_steps);

        for _ in 0..case.n_steps {
            sched.step(&mut opt);
            actual.push(opt.lr);
        }

        let label = format!(
            "CyclicLR(base_lr={base_lr}, max_lr={max_lr}, step_size_up={step_size_up}, mode={mode_str})"
        );
        assert_lr_sequence(&label, &actual, &case.lr_sequence);
    }
}

// ---------------------------------------------------------------------------
// Scheduler count smoke test — ensures all 12 scheduler kinds are covered
// ---------------------------------------------------------------------------

#[test]
fn all_scheduler_kinds_present_in_fixtures() {
    let fixtures = load_fixtures();
    let expected_schedulers = [
        "StepLR",
        "MultiStepLR",
        "ExponentialLR",
        "CosineAnnealingLR",
        "CosineAnnealingWarmRestarts",
        "CyclicLR",
        "OneCycleLR",
        "PolynomialLR",
        "ConstantLR",
        "LinearLR",
        "LinearWarmup",
        "ReduceLROnPlateau",
    ];

    let present: std::collections::HashSet<&str> = fixtures
        .fixtures
        .iter()
        .map(|f| f.scheduler.as_str())
        .collect();

    let missing: Vec<&&str> = expected_schedulers
        .iter()
        .filter(|s| !present.contains(**s))
        .collect();

    assert!(
        missing.is_empty(),
        "Missing scheduler fixtures: {missing:?}"
    );

    // Each scheduler must have at least 2 fixture variants.
    for sched_name in &expected_schedulers {
        let count = fixtures
            .fixtures
            .iter()
            .filter(|f| f.scheduler == *sched_name)
            .count();
        assert!(
            count >= 2,
            "Scheduler {sched_name} has only {count} fixture variant(s), need >= 2"
        );
    }
}
