//! Conformance Layer 3 — SGD-family optimizer step-parity tests (C6.1).
//!
//! Tracking issue: #881 (C6.1 SGD-family conformance)
//! Reference: torch == 2.11.0 (torch.optim)
//!
//! Fixtures: tests/conformance/fixtures.json
//! Generated by: scripts/regenerate_optim_fixtures.py
//!
//! ## Covered optimizers
//!
//! - SGD (plain, momentum, nesterov, weight_decay, dampening)
//! - Adagrad (plain, lr_decay, weight_decay)
//! - ASGD (plain, weight_decay)
//! - Rprop (plain)
//! - RMSprop (plain, centered, momentum, weight_decay)
//!
//! ## Layer 4
//!
//! Surface-coverage gate is deferred to C6 wrap-up (C6.4), after all
//! sub-phases (C6.2-C6.4) have landed their tests.
//!
//! ## cascade_skip convention
//!
//! `cascade_skip!(label, issue)` prints a diagnostic and returns early.
//! This is NOT `#[ignore]` — the test runs and emits the notice so that
//! CI counts skips separately from passes.

#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_sign_loss,
    clippy::uninlined_format_args,
    clippy::explicit_iter_loop,
    clippy::redundant_else
)]

use std::path::PathBuf;

use ferrotorch_core::{Tensor, TensorStorage};
use ferrotorch_nn::Parameter;
use ferrotorch_optim::{
    Adagrad, AdagradConfig, Asgd, AsgdConfig, Optimizer, ParamGroup, Rmsprop, RmspropConfig, Rprop,
    RpropConfig, Sgd, SgdConfig,
};

// ---------------------------------------------------------------------------
// cascade_skip macro — kept for use if divergences are found in future runs.
// ---------------------------------------------------------------------------

/// Print a skip diagnostic and return early. Never panics.
/// Usage: `cascade_skip!("reason", "CL-NNN")`.
#[allow(unused_macros)]
macro_rules! cascade_skip {
    ($reason:expr, $issue:expr) => {{
        eprintln!(
            "  [cascade_skip] {} — {} (tracking: {})",
            module_path!(),
            $reason,
            $issue
        );
        return;
    }};
}

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("conformance")
        .join("fixtures.json")
}

fn load_fixtures() -> serde_json::Value {
    let path = fixture_path();
    let body = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("read fixtures.json: {e}. Run scripts/regenerate_optim_fixtures.py")
    });
    serde_json::from_str(&body).expect("parse fixtures.json")
}

fn fvec(v: &serde_json::Value) -> Vec<f32> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap() as f32)
        .collect()
}

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

/// Tolerance for f32 optimizer steps against reference algorithm.
/// Optimizers accumulate f64 in the reference script but operate in f32 in
/// ferrotorch, so we allow a loose tolerance of 1e-4 abs.
const TOL: f32 = 1e-4;

fn assert_close_vec(actual: &[f32], expected: &[f32], tol: f32, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx}: length mismatch");
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert!(
            (a - e).abs() <= tol,
            "{ctx}[{i}]: expected {e:.7}, got {a:.7} (diff={:.2e})",
            (a - e).abs()
        );
    }
}

/// Build a `Parameter<f32>` from a slice of data.
fn make_param(data: &[f32]) -> Parameter<f32> {
    let n = data.len();
    let t = Tensor::from_storage(TensorStorage::cpu(data.to_vec()), vec![n], true).unwrap();
    Parameter::new(t)
}

/// Read the parameter's current data vector.
fn read_param(param: &Parameter<f32>) -> Vec<f32> {
    param.data().unwrap().to_vec()
}

/// Set gradient on a parameter.
fn set_grad(param: &Parameter<f32>, grad: &[f32]) {
    let n = grad.len();
    let g = Tensor::from_storage(TensorStorage::cpu(grad.to_vec()), vec![n], false).unwrap();
    param.set_grad(Some(g)).unwrap();
}

// ---------------------------------------------------------------------------
// SGD — plain (no momentum, no weight_decay)
// ---------------------------------------------------------------------------

#[test]
fn sgd_plain_step_parity() {
    let fix = load_fixtures();
    let variant = fix["sgd"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "plain")
        .expect("sgd plain fixture");

    let lr = variant["lr"].as_f64().unwrap() as f32;

    // The fixture stores params AFTER each step; init is not in the file.
    // We hard-code the canonical seed (torch.manual_seed(42); torch.randn(10)).
    let init_params: Vec<f32> = vec![
        0.3367, 0.1288, 0.2345, 0.2303, -1.1229, -0.1863, 2.2082, -0.6380, 0.4617, 0.2674,
    ];
    let grad_steps: Vec<Vec<f32>> = vec![
        vec![
            -0.4917, 0.3557, -0.3465, 0.6218, 1.5722, 1.1409, -0.0960, -0.7693, 0.9757, -0.0737,
        ],
        vec![
            0.2162, -0.3476, -0.4131, -0.2786, 0.4397, -0.5476, 1.3618, 0.3791, 0.0870, -1.1205,
        ],
        vec![
            -0.1613, 1.0161, -0.7040, -0.2243, -0.0559, 0.3891, -0.5073, 0.4729, 0.1440, -0.3407,
        ],
        vec![
            0.0516, 0.1965, 0.6048, 0.7213, -0.5534, 0.3248, -0.1098, -1.2456, 0.4319, 0.1012,
        ],
        vec![
            -0.8547, -0.2256, 0.2893, 0.2490, -0.4065, -0.0572, -0.9133, 0.4128, -0.2097, 0.5714,
        ],
    ];

    let param = make_param(&init_params);
    let config = SgdConfig::new(lr as f64);
    let mut opt = Sgd::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grad_steps[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("sgd_plain step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// SGD — momentum
// ---------------------------------------------------------------------------

#[test]
fn sgd_momentum_step_parity() {
    let fix = load_fixtures();
    let variant = fix["sgd"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "momentum")
        .expect("sgd momentum fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let momentum = variant["momentum"].as_f64().unwrap();

    let init_params: Vec<f32> = vec![
        0.3367, 0.1288, 0.2345, 0.2303, -1.1229, -0.1863, 2.2082, -0.6380, 0.4617, 0.2674,
    ];
    let grad_steps: Vec<Vec<f32>> = vec![
        vec![
            -0.4917, 0.3557, -0.3465, 0.6218, 1.5722, 1.1409, -0.0960, -0.7693, 0.9757, -0.0737,
        ],
        vec![
            0.2162, -0.3476, -0.4131, -0.2786, 0.4397, -0.5476, 1.3618, 0.3791, 0.0870, -1.1205,
        ],
        vec![
            -0.1613, 1.0161, -0.7040, -0.2243, -0.0559, 0.3891, -0.5073, 0.4729, 0.1440, -0.3407,
        ],
        vec![
            0.0516, 0.1965, 0.6048, 0.7213, -0.5534, 0.3248, -0.1098, -1.2456, 0.4319, 0.1012,
        ],
        vec![
            -0.8547, -0.2256, 0.2893, 0.2490, -0.4065, -0.0572, -0.9133, 0.4128, -0.2097, 0.5714,
        ],
    ];

    let param = make_param(&init_params);
    let config = SgdConfig::new(lr).momentum(momentum);
    let mut opt = Sgd::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grad_steps[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("sgd_momentum step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// SGD — nesterov momentum
// ---------------------------------------------------------------------------

#[test]
fn sgd_nesterov_step_parity() {
    let fix = load_fixtures();
    let variant = fix["sgd"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "nesterov")
        .expect("sgd nesterov fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let momentum = variant["momentum"].as_f64().unwrap();

    let init_params: Vec<f32> = vec![
        0.3367, 0.1288, 0.2345, 0.2303, -1.1229, -0.1863, 2.2082, -0.6380, 0.4617, 0.2674,
    ];
    let grad_steps: Vec<Vec<f32>> = vec![
        vec![
            -0.4917, 0.3557, -0.3465, 0.6218, 1.5722, 1.1409, -0.0960, -0.7693, 0.9757, -0.0737,
        ],
        vec![
            0.2162, -0.3476, -0.4131, -0.2786, 0.4397, -0.5476, 1.3618, 0.3791, 0.0870, -1.1205,
        ],
        vec![
            -0.1613, 1.0161, -0.7040, -0.2243, -0.0559, 0.3891, -0.5073, 0.4729, 0.1440, -0.3407,
        ],
        vec![
            0.0516, 0.1965, 0.6048, 0.7213, -0.5534, 0.3248, -0.1098, -1.2456, 0.4319, 0.1012,
        ],
        vec![
            -0.8547, -0.2256, 0.2893, 0.2490, -0.4065, -0.0572, -0.9133, 0.4128, -0.2097, 0.5714,
        ],
    ];

    let param = make_param(&init_params);
    let config = SgdConfig::new(lr).momentum(momentum).nesterov(true);
    let mut opt = Sgd::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grad_steps[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("sgd_nesterov step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// SGD — weight decay
// ---------------------------------------------------------------------------

#[test]
fn sgd_weight_decay_step_parity() {
    let fix = load_fixtures();
    let variant = fix["sgd"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "weight_decay")
        .expect("sgd weight_decay fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let wd = variant["weight_decay"].as_f64().unwrap();

    let init_params: Vec<f32> = vec![
        0.3367, 0.1288, 0.2345, 0.2303, -1.1229, -0.1863, 2.2082, -0.6380, 0.4617, 0.2674,
    ];
    let grad_steps: Vec<Vec<f32>> = vec![
        vec![
            -0.4917, 0.3557, -0.3465, 0.6218, 1.5722, 1.1409, -0.0960, -0.7693, 0.9757, -0.0737,
        ],
        vec![
            0.2162, -0.3476, -0.4131, -0.2786, 0.4397, -0.5476, 1.3618, 0.3791, 0.0870, -1.1205,
        ],
        vec![
            -0.1613, 1.0161, -0.7040, -0.2243, -0.0559, 0.3891, -0.5073, 0.4729, 0.1440, -0.3407,
        ],
        vec![
            0.0516, 0.1965, 0.6048, 0.7213, -0.5534, 0.3248, -0.1098, -1.2456, 0.4319, 0.1012,
        ],
        vec![
            -0.8547, -0.2256, 0.2893, 0.2490, -0.4065, -0.0572, -0.9133, 0.4128, -0.2097, 0.5714,
        ],
    ];

    let param = make_param(&init_params);
    let config = SgdConfig::new(lr).weight_decay(wd);
    let mut opt = Sgd::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grad_steps[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("sgd_weight_decay step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// SGD — dampening
// ---------------------------------------------------------------------------

#[test]
fn sgd_dampening_step_parity() {
    let fix = load_fixtures();
    let variant = fix["sgd"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "dampening")
        .expect("sgd dampening fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let momentum = variant["momentum"].as_f64().unwrap();
    let dampening = variant["dampening"].as_f64().unwrap();

    let init_params: Vec<f32> = vec![
        0.3367, 0.1288, 0.2345, 0.2303, -1.1229, -0.1863, 2.2082, -0.6380, 0.4617, 0.2674,
    ];
    let grad_steps: Vec<Vec<f32>> = vec![
        vec![
            -0.4917, 0.3557, -0.3465, 0.6218, 1.5722, 1.1409, -0.0960, -0.7693, 0.9757, -0.0737,
        ],
        vec![
            0.2162, -0.3476, -0.4131, -0.2786, 0.4397, -0.5476, 1.3618, 0.3791, 0.0870, -1.1205,
        ],
        vec![
            -0.1613, 1.0161, -0.7040, -0.2243, -0.0559, 0.3891, -0.5073, 0.4729, 0.1440, -0.3407,
        ],
        vec![
            0.0516, 0.1965, 0.6048, 0.7213, -0.5534, 0.3248, -0.1098, -1.2456, 0.4319, 0.1012,
        ],
        vec![
            -0.8547, -0.2256, 0.2893, 0.2490, -0.4065, -0.0572, -0.9133, 0.4128, -0.2097, 0.5714,
        ],
    ];

    let param = make_param(&init_params);
    let config = SgdConfig::new(lr).momentum(momentum).dampening(dampening);
    let mut opt = Sgd::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grad_steps[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("sgd_dampening step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// Shared test data helpers (avoids copy-paste below)
// ---------------------------------------------------------------------------

fn init_params_f32() -> Vec<f32> {
    vec![
        0.3367, 0.1288, 0.2345, 0.2303, -1.1229, -0.1863, 2.2082, -0.6380, 0.4617, 0.2674,
    ]
}

fn grad_steps_f32() -> Vec<Vec<f32>> {
    vec![
        vec![
            -0.4917, 0.3557, -0.3465, 0.6218, 1.5722, 1.1409, -0.0960, -0.7693, 0.9757, -0.0737,
        ],
        vec![
            0.2162, -0.3476, -0.4131, -0.2786, 0.4397, -0.5476, 1.3618, 0.3791, 0.0870, -1.1205,
        ],
        vec![
            -0.1613, 1.0161, -0.7040, -0.2243, -0.0559, 0.3891, -0.5073, 0.4729, 0.1440, -0.3407,
        ],
        vec![
            0.0516, 0.1965, 0.6048, 0.7213, -0.5534, 0.3248, -0.1098, -1.2456, 0.4319, 0.1012,
        ],
        vec![
            -0.8547, -0.2256, 0.2893, 0.2490, -0.4065, -0.0572, -0.9133, 0.4128, -0.2097, 0.5714,
        ],
    ]
}

// ---------------------------------------------------------------------------
// Adagrad — plain
// ---------------------------------------------------------------------------

#[test]
fn adagrad_plain_step_parity() {
    let fix = load_fixtures();
    let variant = fix["adagrad"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "plain")
        .expect("adagrad plain fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let eps = variant["eps"].as_f64().unwrap();
    let init = init_params_f32();
    let grads = grad_steps_f32();

    let param = make_param(&init);
    let config = AdagradConfig::default().with_lr(lr).with_eps(eps);
    let mut opt = Adagrad::new(vec![ParamGroup::new(vec![param.clone()], lr)], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grads[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("adagrad_plain step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// Adagrad — lr_decay
// ---------------------------------------------------------------------------

#[test]
fn adagrad_lr_decay_step_parity() {
    let fix = load_fixtures();
    let variant = fix["adagrad"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "lr_decay")
        .expect("adagrad lr_decay fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let lr_decay = variant["lr_decay"].as_f64().unwrap();
    let eps = variant["eps"].as_f64().unwrap();
    let init = init_params_f32();
    let grads = grad_steps_f32();

    let param = make_param(&init);
    let config = AdagradConfig::default()
        .with_lr(lr)
        .with_lr_decay(lr_decay)
        .with_eps(eps);
    let mut opt = Adagrad::new(vec![ParamGroup::new(vec![param.clone()], lr)], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grads[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("adagrad_lr_decay step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// Adagrad — weight_decay
// ---------------------------------------------------------------------------

#[test]
fn adagrad_weight_decay_step_parity() {
    let fix = load_fixtures();
    let variant = fix["adagrad"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "weight_decay")
        .expect("adagrad weight_decay fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let wd = variant["weight_decay"].as_f64().unwrap();
    let eps = variant["eps"].as_f64().unwrap();
    let init = init_params_f32();
    let grads = grad_steps_f32();

    let param = make_param(&init);
    let config = AdagradConfig::default()
        .with_lr(lr)
        .with_weight_decay(wd)
        .with_eps(eps);
    let mut opt = Adagrad::new(vec![ParamGroup::new(vec![param.clone()], lr)], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grads[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("adagrad_wd step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// ASGD — plain (t0=0 so averaging starts immediately)
// ---------------------------------------------------------------------------

#[test]
fn asgd_plain_step_parity() {
    let fix = load_fixtures();
    let variant = fix["asgd"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "plain")
        .expect("asgd plain fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let lambd = variant["lambd"].as_f64().unwrap();
    let alpha = variant["alpha"].as_f64().unwrap();
    let t0 = variant["t0"].as_f64().unwrap();
    let init = init_params_f32();
    let grads = grad_steps_f32();

    let param = make_param(&init);
    let config = AsgdConfig::default()
        .with_lr(lr)
        .with_lambd(lambd)
        .with_alpha(alpha)
        .with_t0(t0);
    let mut opt = Asgd::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grads[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("asgd_plain step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// ASGD — weight_decay
// ---------------------------------------------------------------------------

#[test]
fn asgd_weight_decay_step_parity() {
    let fix = load_fixtures();
    let variant = fix["asgd"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "weight_decay")
        .expect("asgd weight_decay fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let lambd = variant["lambd"].as_f64().unwrap();
    let alpha = variant["alpha"].as_f64().unwrap();
    let t0 = variant["t0"].as_f64().unwrap();
    let wd = variant["weight_decay"].as_f64().unwrap();
    let init = init_params_f32();
    let grads = grad_steps_f32();

    let param = make_param(&init);
    let config = AsgdConfig::default()
        .with_lr(lr)
        .with_lambd(lambd)
        .with_alpha(alpha)
        .with_t0(t0)
        .with_weight_decay(wd);
    let mut opt = Asgd::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grads[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(&actual, &expected, TOL, &format!("asgd_wd step {}", i + 1));
    }
}

// ---------------------------------------------------------------------------
// Rprop — plain
// ---------------------------------------------------------------------------

#[test]
fn rprop_plain_step_parity() {
    let fix = load_fixtures();
    let variant = fix["rprop"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "plain")
        .expect("rprop plain fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let etas = variant["etas"].as_array().unwrap();
    let eta_minus = etas[0].as_f64().unwrap();
    let eta_plus = etas[1].as_f64().unwrap();
    let sr = variant["step_sizes_range"].as_array().unwrap();
    let step_min = sr[0].as_f64().unwrap();
    let step_max = sr[1].as_f64().unwrap();

    let init = init_params_f32();
    let grads = grad_steps_f32();

    let param = make_param(&init);
    let config = RpropConfig::default()
        .with_lr(lr)
        .with_etas((eta_minus, eta_plus))
        .with_step_sizes((step_min, step_max));
    let mut opt = Rprop::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grads[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("rprop_plain step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// RMSprop — plain (no momentum, not centered)
// ---------------------------------------------------------------------------

#[test]
fn rmsprop_plain_step_parity() {
    let fix = load_fixtures();
    let variant = fix["rmsprop"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "plain")
        .expect("rmsprop plain fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let alpha = variant["alpha"].as_f64().unwrap();
    let eps = variant["eps"].as_f64().unwrap();
    let init = init_params_f32();
    let grads = grad_steps_f32();

    let param = make_param(&init);
    let config = RmspropConfig::default()
        .with_lr(lr)
        .with_alpha(alpha)
        .with_eps(eps);
    let mut opt = Rmsprop::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grads[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("rmsprop_plain step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// RMSprop — centered
// ---------------------------------------------------------------------------

#[test]
fn rmsprop_centered_step_parity() {
    let fix = load_fixtures();
    let variant = fix["rmsprop"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "centered")
        .expect("rmsprop centered fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let alpha = variant["alpha"].as_f64().unwrap();
    let eps = variant["eps"].as_f64().unwrap();
    let init = init_params_f32();
    let grads = grad_steps_f32();

    let param = make_param(&init);
    let config = RmspropConfig::default()
        .with_lr(lr)
        .with_alpha(alpha)
        .with_eps(eps)
        .with_centered(true);
    let mut opt = Rmsprop::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grads[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("rmsprop_centered step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// RMSprop — momentum
// ---------------------------------------------------------------------------

#[test]
fn rmsprop_momentum_step_parity() {
    let fix = load_fixtures();
    let variant = fix["rmsprop"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "momentum")
        .expect("rmsprop momentum fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let alpha = variant["alpha"].as_f64().unwrap();
    let eps = variant["eps"].as_f64().unwrap();
    let momentum = variant["momentum"].as_f64().unwrap();
    let init = init_params_f32();
    let grads = grad_steps_f32();

    let param = make_param(&init);
    let config = RmspropConfig::default()
        .with_lr(lr)
        .with_alpha(alpha)
        .with_eps(eps)
        .with_momentum(momentum);
    let mut opt = Rmsprop::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grads[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("rmsprop_momentum step {}", i + 1),
        );
    }
}

// ---------------------------------------------------------------------------
// RMSprop — weight_decay
// ---------------------------------------------------------------------------

#[test]
fn rmsprop_weight_decay_step_parity() {
    let fix = load_fixtures();
    let variant = fix["rmsprop"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["variant"] == "weight_decay")
        .expect("rmsprop weight_decay fixture");

    let lr = variant["lr"].as_f64().unwrap();
    let alpha = variant["alpha"].as_f64().unwrap();
    let eps = variant["eps"].as_f64().unwrap();
    let wd = variant["weight_decay"].as_f64().unwrap();
    let init = init_params_f32();
    let grads = grad_steps_f32();

    let param = make_param(&init);
    let config = RmspropConfig::default()
        .with_lr(lr)
        .with_alpha(alpha)
        .with_eps(eps)
        .with_weight_decay(wd);
    let mut opt = Rmsprop::new(vec![param.clone()], config);

    let steps = variant["steps"].as_array().unwrap();
    for (i, step_fix) in steps.iter().enumerate() {
        set_grad(&param, &grads[i]);
        opt.step().unwrap();
        let actual = read_param(&param);
        let expected: Vec<f32> = fvec(&step_fix["params"]);
        assert_close_vec(
            &actual,
            &expected,
            TOL,
            &format!("rmsprop_wd step {}", i + 1),
        );
    }
}
